### ISSUE TITLE
Change "AnthonOS" in Mirror Status to "AOSC OS"

### ISSUE THREAD

**Issue by MingcongBai** [ustclug/discussions#1]
AnthonOS was renamed to AOSC OS as of September, 2014.

**Comment by pudh4418** [comment]
Done.

**Comment by MingcongBai** [comment]
Appreciate it.

-----原始邮件-----
发件人: "pudh4418" <notifications@github.com>
发送时间: ‎2015/‎3/‎1 19:47
收件人: "ustclug/discussions" <discussions@noreply.github.com>
抄送: "Jeff Bai" <jeffbaichina@members.fsf.org>
主题: Re: [discussions] Change "AnthonOS" in Mirror Status to "AOSC OS"(#1)

Done.
