### ISSUE TITLE
Kali源同步滞后。

### ISSUE THREAD

**Issue by MoKarma** [ustclug/discussions#100]
非常感谢你们对ustc moirrors的维护!

- **故障镜像的名称**：[Kali Linux](http://mirrors.ustc.edu.cn/kali/) 
- **首次观察到故障的时间**：2016年底
- **故障描述**：软件源比官方镜像滞后很多
   今天(2017.1.17)的对比截图: 
![ustc](https://cloud.githubusercontent.com/assets/15427810/22021715/b1421312-dcf9-11e6-91b3-3bfff4d0c3f9.png)
![offical](https://cloud.githubusercontent.com/assets/15427810/22021719/b81f96b4-dcf9-11e6-85e9-caa7e5009146.png)

   原因：你们rsync了一个非官方的镜像，而且似乎已经不更新了。
![rsync](https://cloud.githubusercontent.com/assets/15427810/22021929/b66a77b6-dcfa-11e6-912b-d52b2dfa3fd8.png)

- **修复建议**：
 1. 按照官方建议建立镜像（推荐）
     [How to Set Up a Kali Linux Mirror](http://docs.kali.org/community/kali-linux-mirrors)
 2. 同步官方[mirrorlist](http://http.kali.org/README.mirrorlist)中的镜像
     **不建议同步官方mirrorlist中根据所在地区推荐的[东软镜像](http://mirrors.neusoft.edu.cn/kali/),非常糟糕！**
 3. 同步[tuna](https://mirrors.tuna.tsinghua.edu.cn/kali/)
     tuna也有一点点滞后。
 
Ps：粗略看了一下其他的镜像,似乎有一些也是rsync第三方，导致有不同情况的滞后。

再次致谢！

**Comment by knight42** [comment]
感谢您的热心反馈! 目前我们正在向 tuna 进行同步.

**Comment by knight42** [comment]
@MoKarma 
现在已经同步完了, 你可以看看是否还存在其它问题.
