### ISSUE TITLE
homebrew的git仓库过期

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#104]
brew.git主仓库停留在1月25号。登录服务器发现crontab中的定时任务被注释掉了。

有谁知道这是出于什么目的停止同步呢？能否恢复同步？

**Comment by knight42** [comment]
@gaoyifan 这是因为现在我在逐渐用新的 ustcmirror(https://github.com/ustclug/ustcmirror) 来接管. 现在只接管了 git 仓库的同步, 所以把 crontab 中跟 git 同步相关的都暂时注释掉了

**Comment by gaoyifan** [comment]
Got it
