### ISSUE TITLE
crates-io.proxy.ustclug.org镜像站可能故障

### ISSUE THREAD

**Issue by ShadowRZ** [ustclug/discussions#105]
故障镜像名称：crates.io-index镜像
初见时间：估计是今天早上发现的。
描述：如图
![capture-2017-2-11](https://cloud.githubusercontent.com/assets/23130178/22851729/2600d39e-f066-11e6-8512-b632e354e308.PNG)
少数情况下正常。

**Comment by knight42** [comment]
你好, 能否看一下 `crates-io.proxy.ustclug.org` 域名的解析结果?

**Comment by ShadowRZ** [comment]
`ping crates-io.proxy.ustclug.org`:
```
正在 Ping crates-io.proxy.ustclug.org [127.0.0.1] 具有 32 字节的数据:
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=128
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=128
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=128
来自 127.0.0.1 的回复: 字节=32 时间<1ms TTL=128

127.0.0.1 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms
```
（其实我也不知道什么指令可以查看域名解析结果）

**Comment by knight42** [comment]
为什么这个域名会解析成本地的呢?

**Comment by knight42** [comment]
我怀疑在你的机子上 `crates-io.proxy.ustclug.org` 这个域名被解析成本地地址的时候, 就是反代不能用的时候. 你用的是自建的 DNS 吗?

**Comment by ShadowRZ** [comment]
@knight42 首先我应该检查hosts文件，可Windows下hosts文件放在那里？

**Comment by knight42** [comment]
https://www.google.com/#q=win+hosts+%E6%96%87%E4%BB%B6

**Comment by ShadowRZ** [comment]
[hosts.txt](https://github.com/ustclug/discussions/files/768267/hosts.txt)
先献上我的hosts文件

**Comment by ShadowRZ** [comment]
另问：无线路由器是否会影响域名解析？

**Comment by ShadowRZ** [comment]
`NSLOOKUP crates-io.proxy.ustclug.org`:
```
服务器:  cache.jlccptt.net.cn
Address:  202.98.0.68

非权威应答:
名称:    crates-io.proxy.ustclug.org.DHCP HOST
Addresses:  202.98.24.125
          202.98.24.122
          202.98.24.124
```
是否可以基于此结果写一个hosts规则？

**Comment by ShadowRZ** [comment]
已修复。
原因：不知为何只有202.98.5.68这个DNS服务器正确解析，202.98.0.68不能。
因此写了这条hosts规则：`202.141.176.93 crates-io.proxy.ustclug.org`
我的错。

**Comment by knight42** [comment]
抱歉, 刚才有点事出去了.

> 无线路由器是否会影响域名解析？

这个取决于是否接受路由器给你推送的 DNS

> 是否可以基于此结果写一个hosts规则？

可以. 不过个人更推荐的解决方案是更换一个可靠性更高的 DNS

>  我的错。

没事, 欢迎反馈你所遇到的问题. 只要力所能及, 我们都愿意解答.

**Comment by ShadowRZ** [comment]
最后附上（可能）正确的解析结果（虽然看起来有点多余）：
```
非权威应答:
名称:    gateway-el.cname.ustclug.org
Address:  202.141.176.93
Aliases:  crates-io.proxy.ustclug.org
```

**Comment by knight42** [comment]
@ShadowRZ 服务器有3个地址:

* 202.38.93.153
* 202.141.162.123
* 202.141.176.93

你可以选择速度较快的那一个

**Comment by marvinpan8** [comment]
近段时间又连不上了？？？？

**Comment by taoky** [comment]
> 近段时间又连不上了？？？？

See https://github.com/ustclug/discussions/issues/325

**Comment by egmkang** [comment]
ping crates-io.proxy.ustclug.org

正在 Ping crates-io.proxy.ustclug.org [127.233.233.233] 具有 32 字节的数据:
来自 127.233.233.233 的回复: 字节=32 时间<1ms TTL=128
来自 127.233.233.233 的回复: 字节=32 时间<1ms TTL=128
来自 127.233.233.233 的回复: 字节=32 时间<1ms TTL=128

127.233.233.233 的 Ping 统计信息:
    数据包: 已发送 = 3，已接收 = 3，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms

**Comment by egmkang** [comment]
NSLOOKUP crates-io.proxy.ustclug.org
服务器:  SH_DNS_Cluster.snda.root.corp
Address:  192.168.102.81

非权威应答:
名称:    crates-io.proxy.ustclug.org
Addresses:  fe80::2333
          127.233.233.233
