### ISSUE TITLE
树莓派 raspi.list 的反向代理地址似乎变了？

### ISSUE THREAD

**Issue by yangxuan8282** [ustclug/discussions#106]
也就是 `archive.raspberrypi.org` 这个地址
昨天看到官方出了高清屏保就想直接下载下来，以前的话反代的地址是 `mirrors.ustc.edu.cn` + 原地址
对屏保这个包来说按原来的规则就应该是
http://mirrors.ustc.edu.cn/archive.raspberrypi.org/debian/pool/ui/c/cantab-screensaver/cantab-screensaver_0.1.tar.xz

现在变成了：

http://mirrors.ustc.edu.cn/archive.raspberrypi.org/pool/ui/c/cantab-screensaver/cantab-screensaver_0.1.tar.xz

也就是说 http://mirrors.ustc.edu.cn/archive.raspberrypi.org 直接指向了 http://archive.raspberrypi.org/debian

相应的配置 `/etc/apt/sources.list.d/raspi.list` 的时候也得改成：

```
deb http://mirrors.ustc.edu.cn/archive.raspberrypi.org/ jessie main ui
#deb-src http://mirrors.ustc.edu.cn/archive.raspberrypi.org/ jessie main ui
```

看首页似乎没有关于更改地址的公告啊，估计不少树莓派用户会受到影响

**Comment by gaoyifan** [comment]
非常抱歉给您带来不便。
`archive.raspberrypi.org`源的目录调整已经一年有余，但当时没有发布公告，也没有修改帮助文档。目前帮助文档已更新（ by @Alkaid-Benetnash ），感谢您的热心提醒。
如果您仍有疑问，请随时打开这个issue。

* * *

另，archive.raspberrypi.org是完整镜像，非反向代理。
注：`mirrors.ustc.edu.cn`域名下的目录为完整镜像。`*.proxy.ustclug.org` 为反向代理。

`archive.raspberrypi.org`镜像修改历史：
在2014年1月17日增加了archive.raspberrypi.org镜像。
2015年8月5日调整了目录结构 （缩减了/debian目录）
