### ISSUE TITLE
WiKi 显示发送邮件失败

### ISSUE THREAD

**Issue by ustcjerry** [ustclug/discussions#107]
[https://lug.ustc.edu.cn/wiki/](url)
不管是注册新用户还是找回原来的密码，都会显示：
![qq 20170301111609](https://cloud.githubusercontent.com/assets/11849381/23444664/724f999c-fe71-11e6-83d6-45746204562a.jpg)

**Comment by gaoyifan** [comment]
duplicate with https://github.com/ustclug/lugwiki/issues/4
