### ISSUE TITLE
debian的源无法解析

### ISSUE THREAD

**Issue by vipzrx** [ustclug/discussions#108]
1 已经确定本地的网络环境是正常的

2 这是网页上访问的报错

![20170317_105303](https://cloud.githubusercontent.com/assets/5094958/24027108/1a6113dc-0b00-11e7-91b6-1b5798df988c.png)

3 debian中升级软件源的报错

kk@D1:~$ sudo apt-get update
Err http://mirrors.ustc.edu.cn stable InRelease         
  
Err http://mirrors.ustc.edu.cn stable-proposed-updates InRelease
  
Err http://mirrors.ustc.edu.cn stable Release.gpg       
  Unable to connect to mirrors.ustc.edu.cn:http:
Err http://mirrors.ustc.edu.cn stable-proposed-updates Release.gpg
  Unable to connect to mirrors.ustc.edu.cn:http:
Reading package lists... Done
W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/stable/InRelease  

W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/stable-proposed-updates/InRelease  

W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/stable/Release.gpg  Unable to connect to mirrors.ustc.edu.cn:http:

W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/stable-proposed-updates/Release.gpg  Unable to connect to mirrors.ustc.edu.cn:http:

W: Some index files failed to download. They have been ignored, or old ones used instead.

4 请问是不是软件源换了地址了？
5 以后从哪里获得变更软件软的信息呢？

**Comment by zhsj** [comment]
https://servers.ustclug.org/2017/03/mirrors-down/
