### ISSUE TITLE
nginx on mirrors2 logrotate未生效

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#114]
最后一次rotate日志是`/var/log/nginx/mirrors/access.log-20170316.xz`。最新的日志（`access.log`）已超过50GB。

**Comment by knight42** [comment]
fixed

**Comment by gaoyifan** [comment]
这是什么原因呢？

**Comment by knight42** [comment]
@gaoyifan log-<date> 与 log-<date>.xz 同时存在, logrotate 报错

**Comment by gaoyifan** [comment]
估计是正在logrotate时，mirrors宕机了：https://servers.ustclug.org/2017/03/mirrors-down/
