### ISSUE TITLE
LUG wiki 旧的历史记录无法显示

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#116]
![image](https://cloud.githubusercontent.com/assets/227180/24703393/a558130c-1a35-11e7-80ff-dc325bb46ef9.png)

 如图 16年9月份之前的历史无法查看，看了下服务器历史还在
![image](https://cloud.githubusercontent.com/assets/227180/24703440/d4902ca4-1a35-11e7-9590-83f52d872e09.png)

网上搜了下，似乎是因为gzip的原因（服务器上旧的历史都是gzip压缩过的）
类似的问题 https://forum.dokuwiki.org/thread/4194;?unb855sess=o9sk79thmd7bd40ce6rpk7ooj4

**Comment by gaoyifan** [comment]
dup #65
