### ISSUE TITLE
VMware Common Logging Service 健康状况警报

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#12]
解决方案参考：https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2112606
@knight42

**Comment by knight42** [comment]
还参考了 https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2143565

现在的状态是: Critical -> Warning, 放日志的分区上的可用空间为 34 %
