### ISSUE TITLE
LUG FTP 给出仅支持 ASCII 字符集的信息

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#120]
![_053](https://cloud.githubusercontent.com/assets/8443926/25071772/4ebcbc94-22f2-11e7-8219-ac909ba6cea8.png)
![_054](https://cloud.githubusercontent.com/assets/8443926/25071773/5392fab2-22f2-11e7-8ff2-52c1e11bc64c.png)

**Comment by gaoyifan** [comment]
@hosiet 至少讲讲如何复现吧......

**Comment by hosiet** [comment]
@gaoyifan Filezilla 默认配置连接一下 LUG FTP 就是这情况了

**Comment by gaoyifan** [comment]
@hosiet

**Comment by hosiet** [comment]
![_055](https://cloud.githubusercontent.com/assets/8443926/25071892/d48ca2ec-22f4-11e7-8eea-1505c442ad25.png)

那么这样配置如何呢？我在用 filezilla 3.24.0

**Comment by gaoyifan** [comment]
这必须不行啊.... 
FTP over LTS是ftps， 然而我们只支持sftp, ftp, http, afp

**Comment by hosiet** [comment]
@gaoyifan 然而配置上写的是”如果可用的话“，那么就是说客户端会进行探测，这个探测的结果是超时，这明显不对劲

**Comment by gaoyifan** [comment]
FTP并没有责任要兼容FTPS。超时只是客户端的实现/配置有问题。

**Comment by hosiet** [comment]
![_056](https://cloud.githubusercontent.com/assets/8443926/25071917/58062e86-22f5-11e7-82c2-de203c537f70.png)

我期望的结果是这样的

**Comment by gaoyifan** [comment]
@hosiet 可以考虑增加FTPS的支持。要不新开个issue？

**Comment by hosiet** [comment]
然而从 ipv6 连接时这个 530 响应是存在的，从 202.141.176.99:21 连接时就是超时，IPv4/v6 的区别会不会造成问题？

**Comment by gaoyifan** [comment]
我连接的就是ipv4

**Comment by hosiet** [comment]
= = 那就不管这个了，考虑一下第二个问题（仅支持 ASCII 编码）吧

**Comment by gaoyifan** [comment]
@hosiet 网上的解决方案都指向一个隐藏选项`utf8_filesystem=YES`，然并卵
不知道怎么修复这个问题...... 
P.S. Filezilla选force UTF-8 mode可以正常读写中文文件名

**Comment by gaoyifan** [comment]
镜像更新至Debian 9，增加`utf8_filesystem=YES`后，问题解决。 估计是Debian 8的vsftpd太老，不支持`utf8_filesystem`选项。
