### ISSUE TITLE
IFTTT 报错无法连接 ustcmirrors

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#129]
如题 ，`mirrors a_t ustc.edu.cn` 正在收到报错邮件。

**Comment by gaoyifan** [comment]
目前ustc-mirrors@googlegroups已经不依赖IFTTT。刚才删掉了IFTTT Applets。

**Comment by hosiet** [comment]
然而今天又有报错邮件了(ノ ﾟ∀。)ノ﻿

**Comment by gaoyifan** [comment]
WordPress Disconnected
