### ISSUE TITLE
Mirrors 上的 registry-mirror 容器无法解析地址

### ISSUE THREAD

**Issue by knight42** [ustclug/discussions#131]
registry-mirror 容器内不知道为什么无法解析任何地址，包括处于同一个 network 的其他容器名，但是 ping 其他容器的 ip 地址（包括外部 ip 地址）能 ping 通。奇怪的是处于同一个 network 的其他容器却没这个问题。

试过删了重新创建 registry-mirror，但是问题依旧存在。

目前一个 ad-hoc 的解决方法是在容器内替换 nameserver 为 8.8.8.8，并在 hosts 里加入 redis 容器的 ip （扶额

Related issue:
* https://github.com/ustclug/mirrorrequest/issues/111
* https://github.com/moby/moby/issues/20026

**Comment by zhsj** [comment]
新建一个 bridge network，然后再建一个新的容器在里面，也不能解析。感觉是 embedded dns bug 了。。

**Comment by zhsj** [comment]
已经好了？似乎重启了下dockerd？

**Comment by knight42** [comment]
@zhsj 因为我操作的时候发现执行 docker 的子命令时很久没有返回，所以就重启了一下。。

**Comment by loverto** [comment]
公司私服代理的 中科大的的镜像，现在不能用了？还有哪家的可以用啊？
https://docker.mirrors.ustc.edu.cn/

**Comment by gaoyifan** [comment]
我刚试了一下，docker.mirrors.ustc.edu.cn似乎可以用。
docker hub源现在是个什么状况呢？ @knight42 @zhsj

**Comment by zhsj** [comment]
On Thu, May 25, 2017 at 4:09 PM, Yifan Gao <notifications@github.com> wrote:
>
> 我刚试了一下，docker.mirrors.ustc.edu.cn似乎可以用。
> docker hub源现在是个什么状况呢？ @knight42 @zhsj


见前面 @knight42 说的 docker 的 bug。重启 docker 之后有时候就没问题了，但又可能在某个时刻坏掉。


-- 
Regards,
Shengjing Zhu

**Comment by knight42** [comment]
升级 Docker 到 17.05.0-ce 版本后，问题似乎已经不能复现了。

**Comment by mimousewu** [comment]
能确定不能复现吗？
这个问题搞了2年了，都是正常运行一段时间，突然就无法通过hostname访问其他容器了。之前是几天，现在遇到正常运行快一个月又突然出现了，一点征兆都没有...
