### ISSUE TITLE
提供并公布彻底销毁科大博客的方式

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#133]
如题，我们需要给出一个彻底销毁科大博客的方式。销毁博客的客观需求存在，且销毁不被使用的博客可以减小针对 WordPress 的攻击面。

**Comment by bojieli** [comment]
现在 WordPress
后台有关闭博客的功能，在后台申请关闭博客，会收到确认邮件，点击邮件中的链接，再输入管理员密码确认，博客就会进入未激活状态，HTTP 返回
502。数据没有删除是为了存档。

相关公告：
https://servers.ustclug.org/2014/06/disable-blog/
