### ISSUE TITLE
KDE相关软件包

### ISSUE THREAD

**Issue by ShadowRZ** [ustclug/discussions#135]
今天想（在虚拟机）体验一下KDE，我原来把Debian的镜像设为你们的。在基本安装后我发现缺少一些KDE相关软件包，还找不到KDE语言包。
请求检查。

Debian 8.8.0

**Comment by zhsj** [comment]
请详细描述遇到的问题

**Comment by hosiet** [comment]
这可能是发行版使用的问题，应当与镜像无关。请联系 Debian 用户支持并检查合适的语言包是否完全安装。如果认为与镜像相关，请提供详细操作信息、系统信息或是截图以描述问题具体情况。

**Comment by ShadowRZ** [comment]
`apt search`不能找到一个叫做`kde-full`的软件包，其他的镜像正常。

**Comment by zhsj** [comment]
请按 https://mirrors.ustc.edu.cn/help/debian.html 正确配置 Debian 源。
