### ISSUE TITLE
关闭bbs.ustclug.org

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#136]
提议关闭bbs.ustclug.org，原因：
* 门可罗雀
* 没有起到bug report的作用
* 也没有起到增进交流的作用

（不得不说 @Alkaid-Benetnash 很有先见之明

大家怎么看？

* * *

- [x] 发公告
- [x] 移除wiki中的说明/链接
- [x] 移除DNS记录
- [x] 关闭虚拟机
- [x] 移除salt client

**Comment by zhsj** [comment]
支持

**Comment by StephenPCG** [comment]
支持

**Comment by bojieli** [comment]
支持

**Comment by Alkaid-Benetnash** [comment]
支持

**Comment by crabmessage** [comment]
滋兹

**Comment by crabmessage** [comment]
滋兹

**Comment by gaoyifan** [comment]
done

**Comment by zhsj** [comment]
建议 bbs.ustclug.org 跳转到 https://servers.ustclug.org/2017/06/shutdown-lug-bbs/

**Comment by gaoyifan** [comment]
@zhsj  👌 已配置301
