### ISSUE TITLE
Spam on git.ustclug.org

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#137]
https://git.ustclug.org/explore/groups?page=10

![image](https://cloud.githubusercontent.com/assets/227180/26716601/ad9a0544-47ac-11e7-98b5-687723bab0ab.png)

**Comment by knight42** [comment]
感觉最多也就加几条记录。。会有什么实质性的影响吗？

**Comment by gloit042** [comment]
需要admin权限来移除这些账号

**Comment by zhsj** [comment]
我觉得可以限制只允许 *.ustc.edu.cn 注册账号。

**Comment by zhsj** [comment]
@knight42 @gaoyifan please give admin role to @gloit042

**Comment by gaoyifan** [comment]
@gloit042 You are admin now
