### ISSUE TITLE
移动出口拥塞

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#138]
由于近期mirrors流量过大，导致我科移动出口严重拥塞。高峰时期占据了近80%的移动上行带宽，导致学校出口丢包率高达18%。

目前想到的方案：

- [x] 将联通用户定向至教育网接入点
- [x] 关闭移动出口的rsync服务

新增：

- [x] 限速

大家怎么看？

* * *

附1：mirrors流量
<img width="622" alt="screen shot 2017-06-04 at 10 06 53" src="https://cloud.githubusercontent.com/assets/5450996/26758327/a51e1c86-490d-11e7-8007-3ea7a8292dfa.png">

附2：学校出口延迟
<img width="624" alt="screen shot 2017-06-04 at 10 08 12" src="https://cloud.githubusercontent.com/assets/5450996/26758335/d7bc5130-490d-11e7-8d29-a29df0baf7d6.png">

附3：学校出口丢包率
<img width="612" alt="screen shot 2017-06-04 at 10 08 26" src="https://cloud.githubusercontent.com/assets/5450996/26758336/df8d4bf8-490d-11e7-97af-44082a517dba.png">

附4：学校出口流量
<img width="533" alt="screen shot 2017-06-04 at 10 03 53" src="https://cloud.githubusercontent.com/assets/5450996/26758315/43f5ce22-490d-11e7-87c3-95c6fa463357.png">

**Comment by Alkaid-Benetnash** [comment]
不可以像电信一样白天限速吗？

**Comment by zhsj** [comment]
@Alkaid-Benetnash +1，进行限速

**Comment by gaoyifan** [comment]
限速只会大幅降低使用体验。改用BBR后，教育网的速度已经在可接受的范围内了，将联通用户转移到教育网出口是比较合理的（rsync同理）。

**Comment by gaoyifan** [comment]
限速450Mbps

**Comment by gaoyifan** [comment]
默认解析改为教育网后，移动出口流量已有显著下降。
