### ISSUE TITLE
LUG Wiki 保存管理设置时 500 Internal Error

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#139]
如题。

https://lug.ustc.edu.cn/wiki/start?do=admin&page=config

页面底部按下“保存”键即可触发。

**Comment by cuihaoleo** [comment]
明天你再试试说不定就好了。这些天遇到修改页面500、上传文件500…… 当时怎么试都不行，但第二天没人修就好了……

2017年6月4日 18:34，"Boyuan Yang" <notifications@github.com>写道：

**Comment by gaoyifan** [comment]
能给个复现的步骤么？

**Comment by hosiet** [comment]
@gaoyifan 已给

**Comment by hosiet** [comment]
现在任意编辑页面保存也会 500，例如编辑小聚页面保存时即 500

**Comment by cuihaoleo** [comment]
如果是权限问题，为啥时好时坏的……

**Comment by gaoyifan** [comment]
@cuihaoleo  如果当前连接过多，用尽了内存缓存，就会使用缓存文件。  如果上传的文件很小，且并发连接很少，就不会用到文件缓存，也就不会触发错误。
