### ISSUE TITLE
更换wiki配色方案

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#141]
@hosiet  目前红色的配色，看久了眼睛容易出现不适的状况，能否考虑更换一个配色方案？

***

> 让眼睛舒服的颜色还有草绿，浅绿色，浅蓝色，浅褐色，亚麻布色。红色也是很刺激眼睛的颜色，看的时间长了，也容易产生眼干、眼涩等症状，加重眼睛疲劳。

**Comment by zhsj** [comment]
唔，我感觉我之前设的那个很好啊 =.=
https://lug.ustc.edu.cn/wiki/start?bootswatch-theme=paper

**Comment by gaoyifan** [comment]
@zhsj +1 同感

**Comment by hosiet** [comment]
暂时切换了回去，不过 paper 的字体是不是太大了点？
