### ISSUE TITLE
lug 正式邮箱转发列表交接

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#142]
需要对 lug at ustc.edu.cn 邮箱转发人员进行更新与添加。

已知待更新人员：

* crtmike (hotmail)
* lijh2015, mail.ustc
* ustchjy, gmail
* lwr1242, mail.ustc
* tigreriessarordinary, gmail

* [x] 添加转发信息
* [x] 在 Wiki 上更新相关页面

**Comment by Alkaid-Benetnash** [comment]
已更新，还差机智的超立方体邮箱不知道，知道的去补一下吧

**Comment by gaoyifan** [comment]
@Alkaid-Benetnash  hypercube@ustclug.org

**Comment by Alkaid-Benetnash** [comment]
转发配完了，wiki上也更新了
现在就差每个人自己配置邮件代发了
