### ISSUE TITLE
mirrors对搜索引擎不友好

### ISSUE THREAD

**Issue by volltin** [ustclug/discussions#145]
目前搜索引擎带的 user-agent 访问 mirrors 会得到一个 HTTP 403，导致 [搜索结果](https://www.baidu.com/s?ie=UTF-8&wd=%E7%A7%91%E5%A4%A7%E6%BA%90) 比较奇怪。

解决方案：

- [ ] 去掉对 robot 的访问限制，使用 robots.txt （参考：[tuna](https://mirrors.tuna.tsinghua.edu.cn/robots.txt)），可能的问题是某些不遵守 robots.txt 的搜索引擎带来较高负载。

- [ ] 改规则，只有首页放行。

**Comment by zhsj** [comment]
I have add https://mirrors.ustc.edu.cn/robots.txt
But https://npm.mirrors.ustc.edu.cn/robots.txt escapes that rule, since it's not resolved to mirrors.

**Comment by gaoyifan** [comment]
https://github.com/ustclug/mirrors-robots.txt
