### ISSUE TITLE
Mirrors debian-cd 镜像同步信息未出现在 status 界面

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#148]
如题。而且貌似 debian-cd 仍然没有被 ustcmirror 管理。

**Comment by gaoyifan** [comment]
@hosiet 去做个镜像？https://github.com/ustclug/ustcmirror-images

**Comment by hosiet** [comment]
说真的我现在玩不转 docker……总之我先记录一下现在的工作方式，供后人参考。

### 原定期运行方式

现在 `debian-cd` 镜像的同步由 mirror 用户直接进行，在 mirror 用户的 crontab 里有这么一行：

```cron
55      23      * * *   /home/mirror/bin/cd-mirror
```

### 原脚本内容

贴在这里供参考。内无敏感信息。新进接手的话，jigdo 相关的内容可能需要额外了解一下。

* `~/bin/cd-mirror`

[cd-mirror.sh.txt](https://github.com/ustclug/discussions/files/1110847/cd-mirror.sh.txt)

#### 原配置文件示例

* `~/etc/debian-cd-mirror.conf`

敏感信息已删减。

```bash
RSYNC_HOST="cdimage.debian.org"
RSYNC_MODULE="private/debian-cd/"
## RSYNC_PATH has no effect for the sync procedure, but for convenience of get-mirror-status script
RSYNC_PATH="private/debian-cd/"
# For authenticated rsync
RSYNC_PASSWORD=[REDACTED]
RSYNC_USER=mirrors.ustc.edu.cn
RSYNC_ADDRESS=202.38.95.110
TO=/srv/repo/debian-cd
ERRORMAIL=root
MIRRORNAME=ftp.cn.debian.org
DELETEFIRST=0
EXCLUDE=
HUB=false
tmpDirBase="/tmp"
LOGDIR=$HOME/log/debian-cd/
jigdoConf=$HOME/etc/jigdo/jigdo-mirror.conf
masterList=$tmpDirBase/master.list
```

**Comment by zhsj** [comment]
https://github.com/ustclug/ustcmirror-images/issues/16
