### ISSUE TITLE
Mirrors 系统升级（例如 Debian 9）

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#149]
Debian 9 已经发布了，因迟早要进行升级，开一个 issue 追踪系统升级事项。时间允许的话暑假可以考虑下手。

**Comment by StephenPCG** [comment]
我感觉，如果不是有特殊的情况（比如必须要升级才能修复的安全漏洞，或者我们要部署一个依赖于debian 9的新程序），没必要刻意去升级吧？

**Comment by hosiet** [comment]
的确是这样，所以这个算长期计划，没有必要刻意定一个时间点。

**Comment by zhsj** [comment]
@StephenPCG 锻炼一下新同学的运维能力？

**Comment by StephenPCG** [comment]
@zhsj 这理由我支持

**Comment by gaoyifan** [comment]
已增强新同学的运维能力😆
https://servers.ustclug.org/2017/09/ustc-mirrors-under-maintenance/
