### ISSUE TITLE
Mirrors debian repogen 需更新

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#150]
前面说到了锻炼新同学动手能力，感觉一些小工作也比较适合，相比更新整个系统更加容易，所以列出一个近期需要完成的小项目供认领。当然直接做掉也可以。

https://mirrors.ustc.edu.cn/repogen/ 这个页面应该是架在 mirrors 服务器上，现在由于 Debian 9 发布而需要更新。建议的步骤如下：

* [x] 找到 repogen 项目源代码托管位置（没记错应该是在 LUG GitLab 上？）和它在 mirrors 服务器上的部署方法
* [x] 合适地更新 repogen 项目内容（如当前 stable 对应 stretch, oldstable 对应 jessie 等等）并提交至代码库
* [x] 用合适的方式将其部署到 mirrors 服务器上，观察效果

步骤中如果有权限不足的情况需要联系管理员协助。

**Comment by knight42** [comment]
项目地址在 https://git.ustclug.org/mirrors/repogen
目前是通过 mirror 用户的 crontab 执行 /srv/www-misc/repogen/main.py 来更新内容的。需要提一下的是，Ubuntu 的相关信息是自动抓取的，而 Debian 我考虑到更新周期比较长，所以现在是人工填写信息，有兴趣的话也可以改为自动抓取。

**Comment by gaoyifan** [comment]
要不要将这个仓库移动到github?

**Comment by knight42** [comment]
@hosiet 看看 http://mirrors.ustc.edu.cn/repogen/ 现在有没有问题？

**Comment by knight42** [comment]
@gaoyifan 感觉现在的质量有点挫。。

**Comment by hosiet** [comment]
@knight42 可以，没什么问题了

**Comment by gaoyifan** [comment]
@knight42   质量搓也没事~  雅俗共赏嘛~
