### ISSUE TITLE
PXE debian preseed 文件更新

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#151]
http://pxe.ustc.edu.cn/boot/conf/preseed.debian.ustc.cfg 中

d-i apt-setup/security_host string mirrors.ustc.edu.cn/debian-security

这行造成 debian-installer 把 security 源位置理解成了 http://mirrors.ustc.edu.cn/debian-security/debian-security

顺便也可以看看 ubuntu, kali 的 preseed 文件有没有什么要改的

**Comment by zhsj** [comment]
debian stretch 的 preseed 参考 https://www.debian.org/releases/stretch/example-preseed.txt

**Comment by gaoyifan** [comment]
@zhsj  Showfom反馈说这个故障已经修好了，看登录记录似乎是 @Alkaid-Benetnash 。
@Alkaid-Benetnash  能反馈一下进展吗？

**Comment by gaoyifan** [comment]
问题似乎已经消失了。
