### ISSUE TITLE
清查 StartCom 证书

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#152]
据消息可知 Chrome/Chromium 61 开始将对 WoSign/StartCom 证书全面取消信任。应重新评估部署的 StartCom 证书并在适当时机进行替换。

工作应当在 Chrome 61 正式版发布之前完成。

**Comment by gaoyifan** [comment]
@hosiet  似乎不用等到Chrome 61，我们的StartSSL证书目前已经被不被信任了

**Comment by Alkaid-Benetnash** [comment]
mirrors，revproxy-el, blog部署完毕https证书了

**Comment by gaoyifan** [comment]
FTP也换成新证书了

**Comment by gaoyifan** [comment]
目前vpn用的仍然是StartSSL证书(AnyConnect, IKEv1/2协议）
由于主流操作系统还没有移除StartSSL证书，因此暂不影响

**Comment by gaoyifan** [comment]
VPN已更换为AlphaSSL。

应该没有其他地方在用StartCom签发的证书了。
