### ISSUE TITLE
FTP 相对路径错误

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#154]
https://ftp.ustclug.org/~zsj 这个页面上的文件路径都是相对于 https://ftp.ustclug.org/ 的。
而 https://ftp.ustclug.org/~zsj/ 这个页面就正常了。

所以还是把目录都自动加上 / 吧。

**Comment by gaoyifan** [comment]
link: https://github.com/ustclug/discussions/issues/153
问题在于我不太会.....  要不还是换回nginx？

**Comment by zhsj** [comment]
换回nginx吧，我又发现个缺失的功能：
不能隐藏目录，nginx列目录的时候和 `ls` 行为一样，会隐藏 `.` 开头的文件的。

**Comment by gaoyifan** [comment]
已换回nginx
