### ISSUE TITLE
ustclug.org 域名清理

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#157]
ustclug.org 域名未备案，为避免风险，停止解析到国内 ip。

**Comment by gaoyifan** [comment]
@zhsj 那就备个案呗

**Comment by StephenPCG** [comment]
@bg6cq 
张老师，域名可以在科大备案吗？还是只能找个云主机厂商备案？

**Comment by bg6cq** [comment]
可以在科大备案，需通过教育网，是个比较麻烦的事。

**Comment by StephenPCG** [comment]
@bg6cq 
如果可以在科大备案，那就太好了，麻烦就麻烦一点，毕竟也是个一劳永逸的事情。张老师能否讲一下大概的流程，我们尽力配合。

此外，不知道这个备案是否可以备到社团或者老师名下，毕竟学生是流动的，毕业之后对社团的事情可能就不那么上心了。

**Comment by bg6cq** [comment]
这种备案特别麻烦，首先校内需要团委同意，然后到教育网那里备案，也是比较复杂的流程。如果方便的话，建议放在境外虚拟机使用，会好用很多。
