### ISSUE TITLE
申请GitHub教育优惠

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#158]
@bg6cq 
张老师，能否帮忙给 https://github.com/ustclug 这个组织申请教育优惠？
去年的时候尝试申请过，但 GitHub 要求指导老师来申请，学生不能自己申请。

下面是之前和 GitHub 工作人员的邮件往来：
```
There are two exceptions:
* You may ask your teacher to create an organization account for classroom-use.
  Teachers with proof of school affiliation may apply for free private repositories.
* If you are part of an official research organization or school club that is ongoing
  from year to year, you may ask your faculty advisor to apply for free private
  repositories.

Teachers or faculty members may apply here:
https://education.github.com/discount

Cheers,
Scott
```

```
Your advisor will simply need to apply providing proof of academic enrollment
and vouch for your club.

Cheers,
Scott
```

**Comment by bg6cq** [comment]
请告诉我需要多少repo，还有How do you plan to use GitHub in your student group?我来申请

**Comment by zhsj** [comment]
* 多少 repo

20（这个数字其实没有意义，GithHub 最后批下来是无限的）

* How do you plan to use GitHub in your student group?

We use GitHub to coordinate our software development, GitHub issue for discussion, task assignment. Our documents are also in Git control, but some are confidential. So we need private repos to hold them.

**Comment by bg6cq** [comment]
早晨我申请了，暂时没有信息回来

**Comment by bg6cq** [comment]
申请未通过，原因可能是科大的一卡通没有任何日期有关的信息。
Hey Zhang Huanjie,

Unfortunately, we weren't able to approve your educational discount request. The most common reason is that we weren't able to verify your academic status.

You are welcome to reapply at https://education.github.com.

Your application is most likely to be quickly reviewed if you use a recognizable school-issued email address.

If you do not have a school-issued email address, or your application using a school-issued email address is denied, you may reapply using the "I do not have a school-issued email" drop-down option to attach supplementary proof of academic affiliation (e.g. a school ID card, transcript, or affiliation/enrollment verification letter.) Make sure your supplementary proof is official and dated.

If you have any questions, contact us at https://education.github.com/contact.

Have an Octotastic day!

- The GitHub Education Team

**Comment by zhsj** [comment]
我给自己账户申请的时候，就直接去教务系统里截图了下课程表，教师有什么类似的带时间的吗？
另外选"I do not have a school-issued email"，不选有邮箱是因为现在 edu.cn 邮箱已经很难通过了（滥用的结果）。

**Comment by bg6cq** [comment]
通过了！

Hey Zhang Huanjie, we have some awesome newsWe've upgraded @ustclug to an organization plan with unlimited free private repositories and unlimited seats.If you need help getting started with Git and GitHub, check out:https://help.github.com/articles/good-resources-for-learning-git-and-githubIf you have any questions, contact us:https://education.github.com/contactSpread the word: we love giving educational discounts to students, teachers, administrators, and researchers! Please send them to:https://education.github.comHave an Octotastic day!- The GitHub Education Team
--

**Comment by gaoyifan** [comment]
@bg6cq 谢谢老师！
