### ISSUE TITLE
LUG FTP 连接时显示"425 Bad IP Connecting"

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#159]
不知道是否做了 IP 限制，现在在校外连接 FTP 协议会出现这样的情况。

运营商：成都电信

**Comment by gaoyifan** [comment]
未能复现这个问题。如果能提供更加详细的故障说明，请重新打开这个issue。

**Comment by hosiet** [comment]
@gaoyifan 等我回去抓一个包看看

**Comment by gaoyifan** [comment]
@hosiet 请说明一下什么协议？能否ping通？如何复现？
https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html

**Comment by hosiet** [comment]
@gaoyifan FTP 协议，握手没问题，425是 FTP 协议中的返回码，具体等我回去看看

**Comment by hosiet** [comment]
@hosiet 另外用户用的 ftp，密码同样，连接方式 firefox

**Comment by gaoyifan** [comment]
我在本机使用FireFox没能复现这个问题。全球27个测试点使用lftp连接，亦未能复现故障。
建议尝试更换客户端、更换网络环境。确定一下是软件故障还是网络故障。
如果是网络故障，建议抓包看看是否存在异常数据包。
