### ISSUE TITLE
个人文件夹从主页至 LUG FTP 的跳转失效

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#162]
如题。希望做到如下效果：

* 访问 `https://lug.ustc.edu.cn/~myusernameinlug/` 及下面的各项链接
* 302 跳转至 `https://ftp.ustclug.org/~myusernameinlug/` 下面的对应链接

之前配过一次生效了，现在不知道为什么又失效了。

**Comment by gaoyifan** [comment]
https://github.com/ustclug/lugwiki/commit/7fe4dc2d42c86e5e51a252897c3a1b3911d84a77
这个版本还没有部署

**Comment by gaoyifan** [comment]
done
