### ISSUE TITLE
Mirros伪端口聚合

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#163]
目标：充分利用两块网卡
原理：

`iptables`:

```
-A OUTPUT -m statistic --mode nth --every 2 --packet 0 -j MARK --set-xmark 0x1/0xffffffff
-A OUTPUT -m statistic --mode nth --every 2 --packet 1 -j MARK --set-xmark 0x2/0xffffffff
```

`ip rule`:
```
from 202.38.95.110 fwmark 0x1 lookup cernet
from 202.38.95.110 fwmark 0x2 lookup cernet2
from 202.141.160.110 fwmark 0x1 lookup telecom
from 202.141.160.110 fwmark 0x2 lookup telecom2
from 202.141.176.110 fwmark 0x1 lookup mobile
from 202.141.176.110 fwmark 0x2 lookup mobile2
```

状态：
已部署完成，观察效果中。

**Comment by zhsj** [comment]
这个原理是啥？为啥同样的源 ip，可以通过不同的物理网卡出去？
那交换机那边看到的是一个 ip 有两个 mac 地址？

**Comment by gaoyifan** [comment]
给本地发出的包按照顺序打标记，策略路由匹配不同的标记走不同的接口。因此不同网卡发出的数据包MAC地址是不同的。

对于交换机来说，交换机不关心IP地址，这种配置不会影响到交换机。
对于路由器（或三层交换），ARP表更新时，IP对应的MAC取决于哪块网卡先回复ICMP。
因此这种负载均衡只能用于上行，无法适用于下行。对于mirrors来说，下行带宽并不紧张，只有上行有均衡的需求。

Linux自带的multipath route也可以起到类似的效果，但multipath route的均衡策略是基于目的地址的，如果不同目标流量差异较大，效果就不太好。

**Comment by gaoyifan** [comment]
目前运行效果良好。
实测教育网IPv4、教育网IPv6、电信线路峰值可以达到2Gbps；移动线路峰值仅1Gbps。估计交换机上只接了1G的移动端口。
P.S. 所有峰值速率测试均在校内进行。

**Comment by gaoyifan** [comment]
这种做法会导致某些特定版本的协议栈无法正常工作。
确认 #167 与这项修改有关，怀疑 #166 有关。

**Comment by gaoyifan** [comment]
从抓包结果来看，添加“伪端口聚合”前后，唯一有区别的就是数据包的顺序。添加后，乱序情况变得十分严重，内核和网卡对tcp的多项优化无法正常工作。

将路由策略更换为`multipath route`后，PXE已经恢复正常。

**Comment by gaoyifan** [comment]
从这段时间的观察来看，问题已经解决了。

**Comment by gaoyifan** [comment]
内核原生提供类似的bonding策略，看来是重复造了个轮子
已更换为transmit load balancing
