### ISSUE TITLE
mirrors reboot

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#17]
feature：bcache
bugfix: #6 #7 #9 

- [ ] 删除同步过程中的缓存逻辑
- [x] 删除nginx中的缓存配置
- [x] 编译、安装新内核
- [x] 格式化ssd
- [ ] 转换array0、array1 (https://github.com/g2p/blocks)
- [x] 添加bcache设备
- [x] 重启
- [ ] 检查array0的状态

@knight42 @Alkaid-Benetnash @zhsj @hosiet  大家看看有没有什么问题？

@knight42 找个时间大家去趟机房？联系一下jameszhang ？

**Comment by hosiet** [comment]
今后 ssd 做什么用？用途有变化吗？

在 2016年9月1日週四 18:51，Yifan Gao <notifications@github.com> 寫道：

**Comment by gaoyifan** [comment]
> 今后 ssd 做什么用？用途有变化吗？

仍然用作缓存。但切换到bcache后，从文件级缓存变为块缓存。可以同时为ftp、rsync、git、http(s)提供加速。同时不再需要手动维护cache-index.

**Comment by pudh4418** [comment]
看样子 Debian 又发布关于 linux 内核的[安全更新](https://www.debian.org/security/2016/dsa-3616)了。要是重启的话就一并使用新的内核吧。

话说，zhsj 搭建的自动编译内核并上传的的机制还好使吗？

**Comment by zhsj** [comment]
@pudh4418 现在并没有自动编译并上传了，因为更新内核反正得重启。一般都长时间不重启，所以也没这个需求，就不搞了。。

**Comment by zhsj** [comment]
不过 debian 自己签名的内核貌似已经进入 unstable 了，不知道使用姿势是怎样的。
https://tracker.debian.org/pkg/linux-signed

**Comment by zhsj** [comment]
debian unstable 已经默认使用签名内核，建议直接从 unstable 里下载 deb 包[1] 装上就可以了。

另外 debian 默认没有设置 CONFIG_MODULE_SIG_FORCE，也就是说没签名的模块也可以插入。这个行为可以通过启动时修改内核参数更改，相应的参数[2] 是 module.sig_enforce=1

鉴于 mirrors 运行至今都没有使用过除 debian 源里任何第三方内核模块，也没有任何 dkms 相关的包，所以应该没有必要掌握用于签名的私钥。

[1] https://packages.debian.org/sid/linux-image-4.7.0-1-amd64
[2] https://www.kernel.org/doc/Documentation/module-signing.txt

**Comment by gaoyifan** [comment]
确定要使用这么新的内核吗？ 我比较担心遇到稳定性问题。

**Comment by zhsj** [comment]
建议增加一条，重启时进内部阵列的raid卡看下磁盘状况。

**Comment by gaoyifan** [comment]
那就需要去机房了

**Comment by pudh4418** [comment]
不是有命令行工具可以直接在运行时操控内部阵列么？

> 在 2016年9月15日，下午5:11，Shengjing Zhu <notifications@github.com> 写道：
> 
> 建议增加一条，重启时进内部阵列的raid卡看下磁盘状况。
> 
> 
>

**Comment by zhsj** [comment]
@pudh4418 那个storcli吗？不是很会用，能看得到系统配置，比如哪些盘，怎么组的raid，但看不到日志。

**Comment by pudh4418** [comment]
这种东西搜搜就有了，比如：
storcli /c0 show events file=log.txt

就是查看日志了。反正手册网上都有～

**Comment by gaoyifan** [comment]
note: 由于mirrors外部阵列出现故障，在维护过程中已重启。
