### ISSUE TITLE
vm-nfs根分区磁盘损坏

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#175]
坏掉的是一块32GB的SSD，目前很多命令执行不了（由于读不出来数据），不建议重启。

目前这台机器运行的服务：
1.  vSphere虚拟化集群的存储器(via NFS)
2. vSphere虚拟化集群备用DNS
3. 图书馆机房内网主机与tinc的交换节点

目前想到的方案：
1. 换一块SSD，并重装系统，以便恢复服务
2. 将虚拟机存储迁移到vdp，这台机器就不修了

@Smart-Hypercube ？

**Comment by Smart-Hypercube** [comment]
我还有点没搞明白，意思是vpn、light、gateway-el等虚拟机的存储其实都在vm-nfs上吗？换句话说就是它们随时可能因为vm-nfs后续坏盘而损坏？
如果这样的话，考虑到之前你说它的硬盘都已经不太行了，似乎是直接把其上服务移走比较好

**Comment by gaoyifan** [comment]
是的。这些虚拟机实际存放在vm-nfs上，且磁盘的状况不太好，但并没有坏，只有根分区坏了。
vm-nfs存储使用的是RAID1，再坏一块机械硬盘，虚拟机并不会跪。但如果设备断电（重启），有很大可能性启动不起来（然后虚拟机就跪了）。

**Comment by bojieli** [comment]
坏机器如果是捐赠的那批比较老的服务器，还是不要修了吧，太麻烦。现在我们有台老 mirrors，应该是相当稳定的，可以考虑往上迁移。

**Comment by gaoyifan** [comment]
目前SSH已经连不上了

**Comment by volltin** [comment]
这台机器的功能已经由 gateway-el 替代，目前 vm-nfs 已经没有使用。
