### ISSUE TITLE
Mirrors增加联通线路

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#179]
From @bg6cq :

> 学校的联通出口已升级为2G，目前利用率不高，请问是否可以把mirrors流量转移部分过去？
> 联通出口网段vlan是11，可用IP是218.104.71.170/255.255.255.240，网关218.104.71.161，请测试是否可用。

***

- [x] 更新网路配置
- [x] nginx增加新的监听地址
- [x] rsync-huai增加新站点配置
- [x] 更新DNS
- [x] 发布公告

**Comment by gaoyifan** [comment]
我的想法是默认解析改成联通， 电信、移动、教育网用户仍然走原本的运营商。
不过这两天mirrors负载很高，感觉zfs性能实在💊

**Comment by zhsj** [comment]
我觉得有个认知的问题：
>请问是否可以把mirrors流量转移部分过去
这不是“转移”，这是“增加”，别的出口流量不会减少，新的出口流量继续增加 🙈 

USTC 流量有望超过 TUNA 了 🙈

**Comment by gaoyifan** [comment]
@zhsj  默认解析改成联通，那么教育网IP的流量就会大幅减少

**Comment by zhsj** [comment]
>@zhsj 默认解析改成联通，那么教育网IP的流量就会大幅减少

啊，教育网是的，因为从来没饱和过。我觉得“转移”本意是希望转移部分移动和电信的吧？

**Comment by gaoyifan** [comment]
“转移”的本意还不不要臆测了~ 问下张老师吧 @bg6cq 

电信和移动流量一直比较低。最近30小时平均值：
* 电信200.0Mbps
* 移动149.6Mbps
* 教育网579.2Mbps

当然，总流量也不高。

**Comment by zhsj** [comment]
>当然，总流量也不高

应该是zfs的问题。。校内最近时常会出现只有几十k的速度。。

**Comment by gaoyifan** [comment]
@zhsj  所以我们要不要换掉zfs？

**Comment by zhsj** [comment]
@gaoyifan 把 @happyaron 拉来开讲(xiu)座(zfs)啊

**Comment by gaoyifan** [comment]
上次 Aron 调了参数，然而load变得更高了🙈🙈🙈。我感觉这是zfs自身的问题。
还有种可能是RAIDZ-3校验负担太重。
anyway，不重建阵列始终无法从根本上解决问题

**Comment by gaoyifan** [comment]
已增加联通线路

**Comment by gaoyifan** [comment]
https://servers.ustclug.org/2017/09/mirrors-add-unicom-route/

目前 mirrors.ustc.edu.cn 策略为，电信、移动、教育网用户走各自的线路，其余用户走联通线路。
rsync.mirrors.ustc.edu.cn 策略为，移动、教育网用户走各自的线路，其余用户走联通线路。
