### ISSUE TITLE
debian push mirror 没有正常工作

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#180]
场景：
第一次收到 push，开始同步
第二次收到 push，但由于第一次还没同步完，ustcmirror 因为名为 syncing-debian 的 container 已经在了，就会直接退出。

但实际上，第二次收到 push 的时候，ftpsync 如果检测到原来的同步没完成，就会创建 need update 的文件，告诉那个在同步的 ftpsync 要再同步一次。

@knight42

**Comment by gaoyifan** [comment]
所以不该直接退出？正常运行一遍就好了？

**Comment by zhsj** [comment]
@gaoyifan 应该是的

**Comment by gaoyifan** [comment]
@zhsj 直接原因应该是zfs💊。导致同步时间变长，无法在两次push的时间间隔内同步完成。

**Comment by zhsj** [comment]
@gaoyifan 如果第一次不是push而是cron触发的，第二次收到push也会这样。而这两个之间的时间是不可预计的，有可能不会很长

**Comment by gaoyifan** [comment]
@zhsj 我觉得重点不是ftpsync/yuki，当务之急是解决zfs的性能问题

**Comment by wsy2220** [comment]
`# aptitude update
Get: 1 http://202.141.160.110/debian sid InRelease [234 kB]
Get: 2 http://202.141.160.110/debian sid/contrib Sources.diff/Index [27.8 kB]
Get: 3 http://202.141.160.110/debian sid/main Sources.diff/Index [27.9 kB]
Ign http://202.141.160.110/debian sid/main Sources.diff/Index
Get: 4 http://202.141.160.110/debian sid/contrib Sources.diff/Index [27.8 kB]
Ign http://202.141.160.110/debian sid/contrib Sources.diff/Index
Get: 5 http://202.141.160.110/debian sid/main amd64 Packages.diff/Index [27.9 kB]
Ign http://202.141.160.110/debian sid/main amd64 Packages.diff/Index
Get: 6 http://202.141.160.110/debian sid/main Translation-en.diff/Index [27.9 kB]
Ign http://202.141.160.110/debian sid/main Translation-en.diff/Index
Get: 7 http://202.141.160.110/debian sid/contrib amd64 Packages 2017-09-15-0218.33.pdiff [416 B]
Get: 8 http://202.141.160.110/debian sid/contrib amd64 Packages 2017-09-15-0218.33.pdiff [416 B]
Get: 9 http://202.141.160.110/debian sid/main Sources [7661 kB]
Err http://202.141.160.110/debian sid/main Sources
  File has unexpected size (7663268 != 7660968). Mirror sync in progress?
Hashes of expected file:
 - Filesize:7660968 [weak]
 - SHA256:1abbcc39e29d734c42411da2964b1bf2040091162fc893a0ba2cf8166569ebaf
 - MD5Sum:187a626d668178e6cbbc5ada0dd2336e [weak]
Release file created at: Fri, 15 Sep 2017 08:31:07 +0000

Get: 10 http://202.141.160.110/debian sid/contrib Sources [51.3 kB]
Err http://202.141.160.110/debian sid/contrib Sources
Get: 11 http://202.141.160.110/debian sid/main amd64 Packages [7651 kB]
Err http://202.141.160.110/debian sid/main amd64 Packages
Get: 12 http://202.141.160.110/debian sid/main Translation-en [5802 kB]
Err http://202.141.160.110/debian sid/main Translation-en
Fetched 346 kB in 0s (397 kB/s)
W: Failed to fetch http://202.141.160.110/debian/dists/sid/main/source/Sources.xz: File has unexpected size (7663268 != 7660968). Mirror sync in progress?
   Hashes of expected file:
    - Filesize:7660968 [weak]
    - SHA256:1abbcc39e29d734c42411da2964b1bf2040091162fc893a0ba2cf8166569ebaf
    - MD5Sum:187a626d668178e6cbbc5ada0dd2336e [weak]
   Release file created at: Fri, 15 Sep 2017 08:31:07 +0000
W: Failed to fetch http://202.141.160.110/debian/dists/sid/contrib/source/Sources.xz: 
W: Failed to fetch http://202.141.160.110/debian/dists/sid/main/binary-amd64/Packages.xz: 
W: Failed to fetch http://202.141.160.110/debian/dists/sid/main/i18n/Translation-en.bz2: 
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by zhsj** [comment]
直接在 ~mirror/bin/ssh-push-proxy 里，先 `touch /srv/repo/debian/Archive-Update-Required-mirrors.ustc.edu.cn`，然后再运行 `ustcmirror sync debian`

效果应该一样。
