### ISSUE TITLE
Add PXE iso to Fedora development

### ISSUE THREAD

**Issue by sztsian** [ustclug/discussions#186]
See http://mirrors.ustc.edu.cn/fedora/development/27/Server/x86_64/os/
With http://dl.fedoraproject.org/pub/fedora/linux/development/27/Server/x86_64/os/
'images' directory is missing.
And if you look into this directory, http://mirrors.ustc.edu.cn/fedora/development/27/Server/x86_64/iso/ , actually there are no ISO there.

**Comment by zhsj** [comment]
这是目前的rsync配置
```
"RSYNC_PATH": "fedora-enchilada/linux/",
"RSYNC_EXCLUDE": "--exclude=/core --exclude=/extras --exclude=/development/**/*.iso --exclude=/development/**/images/"
```

**Comment by zhsj** [comment]
感觉可以只exclude iso，pxe的内容不大，但应该会比较有用
 http://dl.fedoraproject.org/pub/fedora/linux/development/27/Server/x86_64/os/images/pxeboot/

**Comment by gaoyifan** [comment]
@sztsian 
I'm sorry for your inconvenience. 
Due to frequent change of development ISO,  we can hardly finish syncing within a period. In order to improve timeliness of Fedora repo, development ISO was excluded intentionally.

***
@zhsj 
同意~  pxe 性价比确实比较高。

**Comment by sztsian** [comment]
I am fine if you exclude ISO, as I know it will never finish if you sync ISO (due to network speed). But exclude pxe files makes the development tree much less useful, especially pxe files are pretty small. As this is intended, I agree this can be closed. However I hope the pxe files can be added back.

Thanks.

**Comment by gaoyifan** [comment]
Exclude parameter:
```
--exclude=/core \
--exclude=/extras \
--include=/development/**/pxeboot/***  \
--exclude=/development/**/*.iso \
--exclude=/development/**/images/
```

@sztsian 
PXE iso will be back in the next few hours.

**Comment by sztsian** [comment]
> --exclude=/development/**/images/

If you mean this line is still there, I believe the pxe related files will still be missing ;-)

**Comment by gaoyifan** [comment]
Thanks for your remind.  Maybe this works:

```
--exclude=/core \
--exclude=/extras \
--include=/development/**/pxeboot/***  \
--exclude=/development/**/*.iso \
--exclude=/development/**/*.raw.xz \
--exclude=/development/**/CloudImages/
```
