### ISSUE TITLE
更新mirrors ISO跳转规则

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#190]
近期mirrors带宽紧张，而ISO流量占用了大量带宽。
![image 2017-10-24 03 00 43](https://user-images.githubusercontent.com/5450996/31907825-8d76bd8a-b867-11e7-9b2d-e522d94379b6.jpg)
![image 2017-10-24 03 00 36](https://user-images.githubusercontent.com/5450996/31907827-8ff29cbe-b867-11e7-8cec-8a008d842017.jpg)

根据群组中的讨论结果，计划将部分iso文件跳转至阿里云。

**Comment by gaoyifan** [comment]
done.

/snippets/redirect-iso-to-other-sites
```nginx
location ~* ^/(ubuntu-releases|centos|fedora)/.+\.iso$ {
    if ($ustcnet ~ "0") {
        rewrite ^(/.*)$ $scheme://mirrors.aliyun.com$1;
    }
}
```

**Comment by zhsj** [comment]
电信似乎还是走了verify.iso?

**Comment by gaoyifan** [comment]
@zhsj  似乎是因为iso.mirrors的跳转优先级比阿里云的跳转高：

```nginx

location ~* ^/(ubuntu-releases|centos|fedora)/.+\.iso$ {
    if ($ustcnet ~ "0") {
        rewrite ^(/.*)$ $scheme://mirrors.aliyun.com$1;
    }
}

if ($http_user_agent ~ "Mozilla" ) {
    rewrite ^/(.*\.iso)$ http://iso.mirrors.ustc.edu.cn/$1;
}

```

**Comment by gaoyifan** [comment]
改成了这样，先看看效果：

```
location ~* \.iso$ {
    if ($http_user_agent ~ "Mozilla" ) {
        rewrite ^/(.*\.iso)$ http://iso.mirrors.ustc.edu.cn/$1;
    }
}
```

**Comment by gaoyifan** [comment]
目测正常了

**Comment by gaoyifan** [comment]
目测正常了

**Comment by zhsj** [comment]
![image](https://user-images.githubusercontent.com/227180/32033080-1068386e-ba3d-11e7-8a39-2c739d34700e.png)

还是没302到aliyun，但用curl测试却转跳了，不知道问题在哪里

**Comment by zhsj** [comment]
似乎是我的代理插件的问题。。。ustc的域名走了light。。
