### ISSUE TITLE
Stack的setup配置文件更新

### ISSUE THREAD

**Issue by zhen-yu** [ustclug/discussions#192]
新电脑第一次 `stack setup`，自动下载`ghc`和`msys2`，前者下载成功，后者失败、

根据错误提示定位发现，应该是
<http://mirrors.ustc.edu.cn/stackage/stack-setup.yaml>
中的`msys2`版本过期了、、目前的配置还是20150512，
而<http://mirrors.ustc.edu.cn/msys2/distrib/x86_64/>已没有对应版本，应当改为最新的20161025

**Comment by gloit042** [comment]
已成功更新，请再尝试一下

**Comment by zhen-yu** [comment]
测试：
因已用其他源安装成功，Windows下先定位到`C:\Users\<Username>\AppData\Local\Programs\stack\x86_64-windows`
删除`msys2-20161025`文件夹和`msys2-20161025.installed` `msys2-20161025.tar.xz`文件

终端下再次`stack setup`，安装msys2成功
