### ISSUE TITLE
bioc 镜像的软链接同步似乎有问题

### ISSUE THREAD

**Issue by ckj996** [ustclug/discussions#193]
* 镜像： https://mirrors.ustc.edu.cn/bioc/
* 上次同步： 11/14/2017, 2:44:10 AM
* 上游： rsync://master.bioconductor.org/

## 问题描述

```nohl
$ rsync -avSHP rsync://mirrors.ustc.edu.cn/bioc/packages/release ~/

receiving incremental file list
release -> 3.5
```

```nohl
$ rsync -avSHP rsync://master.bioconductor.org/packages/release ~/

receiving incremental file list
release -> 3.6
```

devel 同理，ustc 镜像站是 3.6，上游是 3.7。

昨天发现的这个现象，今天同步之后依然是这样。
不知是什么引起的，希望管理员能检查一下。

**Comment by gaoyifan** [comment]
`/srv/repo/` 中的数据已经更新了，但rsync的索引 `/srv/repo/rsync-attrs/` 没有更新，暂不清楚原因。

我刚才手动执行了一次索引同步。

**Comment by gaoyifan** [comment]
调查了一下，这是由于yukid与post-sync.sh脚本的问题。
bioc的配置中`storageDir=/srv/repo/bioc/packages/` ，导致bioc仓库被同步到了`/srv/rsync-attrs/packages`。

@knight42 你觉得这个问题怎么解决比较好呢？

**Comment by knight42** [comment]
这是配置的问题吧，为什么要这么写？直接同步到 `/srv/repo/bioc/` 会有什么问题吗？

**Comment by gaoyifan** [comment]
@knight42  我也不太清楚为什么当初bioc要这么配置....
我猜是兼容性考虑？

**Comment by gaoyifan** [comment]
@knight42  如果storageDir只能是形如 `$BASE/$reponame` 这种形式，那么storageDir不就冗余了嘛。
反之，如果storageDir是不必遵守固定的形式，那么post-sync.sh就需要处理 `$NAME != $(basename $1)`的情况。

我有个建议，能否让yukid调用post-sync脚本时，将所有的信息都配置为环境变量。相比于目前配置调用参数的方法`"/home/mirror/bin/post_sync.sh ${storageDir}"`，环境变量的灵活性会更高一些。

**Comment by Alkaid-Benetnash** [comment]
当初好像是我配的，旧mirrors的阵列挂掉之后初始同步那次。有git记录3f2f6。参考别的镜像的结构，建了一个packages文件夹。
https://mirror.aarnet.edu.au/pub/bioconductor/
https://bioconductor.riken.jp/

**Comment by knight42** [comment]
@gaoyifan `storageDir` 确实不需要遵循固定的形式，但得是那个源的根目录。

`post_sync.sh` 本身就是我为了在同步结束后执行 `rsync-huai` 临时写的一个 workaround，没有考虑太多情况，你可以自由修改。

另外，我觉得通过配置参数比起环境变量的方式要更明晰一点，不知道你说的灵活性具体是指哪一方面？

**Comment by knight42** [comment]
@Alkaid-Benetnash 唔.. 那你方便调整一下同步参数，让 `storageDir` 变为 `/srv/repo/bioc/` 吗？

**Comment by JackieMium** [comment]
这个问题好像还在？一直提示 Bioconductor 有更新，但是同过 USTC 就是更新不上去。
运行一楼 @ckj996 的命令结果一样。

**Comment by gaoyifan** [comment]
fixed

1.  去掉了子目录 `/packages`
2. 增加兼容性重定向
