### ISSUE TITLE
gateway-el kernel panic

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#194]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/5450996/32985247-7d47951c-ccf1-11e7-95d1-522220db3040.png">

故障时间：11月19日05时36分

**Comment by gaoyifan** [comment]
于 Nov 19 06:20 重置虚拟机  服务恢复

**Comment by gaoyifan** [comment]
更新一下，强制重启后，GRE隧道配置没有恢复，已手动修复。

kernel panic原因不明，看调用栈应该是处理中断的时候出现了问题，像是ipsec模块的锅。 可能是内核的bug。 

可以考虑升级一下内核，顺便把debian也升级到9.

**Comment by yangzhaofeng** [comment]
似乎又掛了。。。從VPN連接的情況來看

**Comment by gaoyifan** [comment]
update 2017.11.22  17:16
<img width="722" alt="image" src="https://user-images.githubusercontent.com/5450996/33119118-f3d80874-cfa8-11e7-9344-d5498723e316.png">

**Comment by gaoyifan** [comment]
升级系统后，一个月内故障未见重现。
