### ISSUE TITLE
移除 ftp.cn.d.o 相关的文案

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#199]
目前已知：
* [x] http://mirrors.ustc.edu.cn/ 底部，“Debian 在中国的官方镜像”
* [x] rsync://rsync.mirrors.ustc.edu.cn/ motd 中 ”Debian primary mirror in China mainland (ftp.cn.debian.org)“

**Comment by cuihaoleo** [comment]
这个这么容易修都没人搞么（（

**Comment by hosiet** [comment]
现状是这样的，供参考：

https://lists.debian.org/debian-chinese-gb/2017/10/msg00012.html
