### ISSUE TITLE
将历史邮件中的镜像请求整理至GitHub

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#2]

**Comment by zhsj** [comment]
大概浏览到了 July 1 2014

其中 OpenSUSE 的 Tumbleweed 未新建 Issue，Tumbleweed 貌似没有在 OpenSUSE 提供的 rsync 地址里发现。

**Comment by gaoyifan** [comment]
太旧的加源请求意义也不大。这个issue先关了。
