### ISSUE TITLE
mirrors帮助按钮消失

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#20]
诸多源的help链接消失。

![ustc_open_source_software_mirror](https://cloud.githubusercontent.com/assets/5450996/18223656/e32bfa1a-71f0-11e6-9623-f8fc0027866b.png)

怀疑与近期lug.ustc.edu.cn变卡有关

**Comment by knight42** [comment]
是的, 访问超时后会认为对应的 help 链接不存在
