### ISSUE TITLE
关闭linode.s.ustclug.org

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#201]
该vps用于提供科大博客第三方域名反代。目前科大博客系统已关闭，该vps没有任何用处，计划在近期停止续费。
 
- [x] 移除相关 DNS 记录
- [x] 移除 salt host

**Comment by gaoyifan** [comment]
@Smart-Hypercube   请更新一下Google Docs上的服务器列表（我找不见地址了....）

**Comment by Smart-Hypercube** [comment]
Done.
