### ISSUE TITLE
wine的镜像失效了

### ISSUE THREAD

**Issue by abcfy2** [ustclug/discussions#204]
```
错误:39 https://mirrors.ustc.edu.cn/wine/wine-builds/ubuntu xenial Release                                                                       
  404  Not Found
```

经检查发现，是上游`ftp://ftp.winehq.org/pub`已经移除了`wine-builds`目录

**Comment by gaoyifan** [comment]
感谢反馈。 目前我们缺少可靠的同步工具用于同步`wine-builds/`目录。
可能短期内无法修复。

**Comment by wangling12** [comment]
我也来请求一波,按`winehq`官方的方法添加源后,发现最新版本除`dl.winehq`外有一个附加地址:
`https://download.opensuse.org/repositories/Emulators:/Wine:`
显然这东西是`opensuse`的`repositories`部分,能不能曲线救国,把这部分同步了?

**Comment by taoky** [comment]
相关讨论移至 https://github.com/ustclug/mirrorrequest/issues/117
