### ISSUE TITLE
repodata.json in conda R Channel is incomplete, missing m2w64-* entries.

### ISSUE THREAD

**Issue by zcattacz** [ustclug/discussions#206]
-    All m2w64-* entries are missing from repodata.json, only show up as dependencies:
`http://mirrors.ustc.edu.cn/anaconda/pkgs/r/win-32/repodata.json`
-    while all m2w64-* packages are in the repo `http://mirrors.ustc.edu.cn/anaconda/pkgs/r/win-32` directory.
-   thus r-base can't be installed from ustclug mirror without official repo, though all packages are already there.

**Comment by zcattacz** [comment]
I think I got it. These `m2w64-*` packages are not supposed to be in `r/win32` but `msys2/win32`.
Nothing is missing in `repodata.json`,  its the file sync that is a bit messed up. Looking at the official `https://anaconda.org/r/repo` , you get nothing `^m2w64`, all those packages are in `msys2`. 
Maybe, you guy might like to move them into a cloud/msys2/win32 repo, which is currently missing ?

**Comment by gaoyifan** [comment]
@shankerwangmiao   Could you have a look and give some advice, please? Thanks.

**Comment by shankerwangmiao** [comment]
The script in question is https://github.com/tuna/tunasync-scripts/blob/master/anaconda.py and @bigeagle
