### ISSUE TITLE
恢复新闻站 news.ustclug.org

### ISSUE THREAD

**Issue by cuihaoleo** [ustclug/discussions#207]
USTC LUG 新闻 news.ustclug.org（原 lug.ustc.edu.cn/blog）由于科大博客停止服务而一并关闭。

自2010年以来，每次 LUG 重要活动都会在新闻站上面发布公开新闻稿。该站是作为学生社团的 LUG 的最重要的新闻发布平台。

请即时恢复新闻站，并坚持活动后发布公开新闻稿的良好习惯！

参考：[Internet Archive 于 2017年6月11日 归档的页面](https://web.archive.org/web/20170611182546/https://news.ustclug.org/)

**Comment by Smart-Hypercube** [comment]
done.
现在在 https://github.com/ustclug/news 的 GitHub Pages
