### ISSUE TITLE
申请成为archlinux tier1源

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#209]

**Comment by noirgif** [comment]
USTC Archlinux 现在为Tier 2镜像，其上游为TUNA的镜像，现讨论申请成为Tier 1，直接同步Archlinux官方镜像，理由有：

1. TUNA采用两台机器进行LB，然而这两台机器分别同步上游，之间没有交互。因此，USTC镜像同步时可能会遇到返回结果不一致的问题。

2. 另外，独立于TUNA Archlinux镜像有助于实现互为热备的目标。USTC LUG和TUNA为姊妹社团，是互相302的关系。但现情况，如果TUNA的Archlinux镜像出现问题，USTC的也会不可用。成为Tier 1有助于缓解这种问题。

**Comment by zhsj** [comment]
https://bugs.archlinux.org/task/57973

**Comment by zhsj** [comment]
tier1 now.

**Comment by cuihaoleo** [comment]
官方这么爽快的嘛

**Comment by BruceZhang1993** [comment]
资辞啊！

**Comment by kosmosoahc** [comment]
漂亮
