### ISSUE TITLE
pxe 上的 Fedora 地址不对！

### ISSUE THREAD

**Issue by sztsian** [ustclug/discussions#212]
http://202.38.93.94/boot/menu.cgi

还使用了老的地址结构
http://mirrors.ustc.edu.cn/fedora/linux/releases/27/Fedora/i386/os/images/pxeboot/vmlinuz
现在的地址大约为
http://mirrors.ustc.edu.cn/fedora/releases/27/Everything/x86_64/os/images/pxeboot/vmlinuz
此外 Fedora 27 开始 i386 已经成为 Secondary Architecture 了.
(Mention to tracking https://github.com/FZUG/issues/issues/1 )

**Comment by zhsj** [comment]
欢迎PR https://git.ustclug.org/pxe/pypxe/blob/master/menulib.py#L188

**Comment by sztsian** [comment]
呃，我倒是很愿意提PR, 可我访问不了 git.ustclug.org

**Comment by sztsian** [comment]
PR Sent. https://git.ustclug.org/pxe/pypxe/merge_requests/1

**Comment by zhsj** [comment]
merged
