### ISSUE TITLE
將聯通的公網IP地址從mirrors上剝離

### ISSUE THREAD

**Issue by yangzhaofeng** [ustclug/discussions#213]
目前其他的服務使用聯通線路的需求也在增加，但是拿到聯通的公網IP十分困難，因此我覺得可以將mirrors上的聯通IP剝離出來，建一個gateway-unicom，通過內網+端口映射，達到IP地址復用的目的。

**Comment by yangzhaofeng** [comment]
具體設想方案如下：
在舊的mirrors上面開一台虛擬機，分配聯通的公網地址及千兆網卡
各台需要使用聯通出口的服務器通過校內隧道連接至這台網關機器，mirrors可以考慮物理連接
將網關的端口映射到各台服務器，如80和443映射到mirrors，53映射到neat DNS，1194映射到VPN等
其餘流量可以走NAT

**Comment by gaoyifan** [comment]
FYI, 新旧mirrors服务器均没有空闲的物理接口。

***

端口映射有可能会带来一些新问题：
1. 目前，mirrors、neatdns的默认网关是10.254.0.254(gw-el)。如果使用隧道的方式，需要配置策略路由。 然而neatdns是docker容器，实现起来会比较麻烦，另外可能会影响到容器的可迁移性。
2. mirrors 部分同步任务，需要绑定联通出口（即，通过绑定源地址的方式，配合策略路由，强制走联通线路向上游同步）。  如果采用隧道+端口映射的方案，记得特别更新这部分的配置。

***

关于网关，有一些问题：
1.  gateway-nic是一个位于网络信息中心的网关。目前只是一个tinc节点，为网络信息中心的纯内网虚拟机提供LUGI的接入服务。其实并没有起到网关(or 出口)的作用。 可以考虑直接将这台机器作为联通网关，这样也方便未来实现双机房的冗余。
2.  如果所有需要联通线路的服务都需要单独建一个到新网关的隧道，这会严重牺牲可扩展性。
目前，我们docker容器、内网虚拟机可以运行在任意一个物理节点上。这依赖于统一的内网网关。 如果存在两个网关，所有接入联通线路的服务都需要建设隧道，那么这个特性就不存在了。 如果出现物理服务器宕机，机房间迁移虚拟机就变得很不方便。 并且每个需要联通接口的新服务都需要新建隧道。

***

我有个想法，请大家看看靠不靠谱？ 即，网关实现透明的数据交换。 
保持后端服务的默认网关10.254.0.254不变，当前的默认网关gw-el 与 新网关 之间互相交换数据。 如果网关收到自己conntrack表中没有的数据包（conn-state == invaild && src-mac ！= gw-*），则转发给另一台；反之亦然。 好处是后端服务完全不需要做修改，也不需要隧道，对后端完全透明。 缺点嘛，网关配置会变复杂啦。

也可以尝试用VRRP协议，将10.254.0.254配置为虚地址，从而实现冗余。#165

***

个人比较倾向于在mirrors上给vpn开个端口映射（or隧道）。**如果不是打算锻炼技术，只是希望改进vpn的速度，不建议新建联通网关。坑真的很多。**

***

之前我们有讨论过一些相关的话题，供参考。 #183 #103 #165

**Comment by yangzhaofeng** [comment]
感覺使用nic確實是一個好方案
然後el和新網關之間的數據交換感覺有一個簡單一些的方案，即el和nic之間建立隧道，然後將el作為聯通內網的一台交換機來使用，或者再來一次NAT也可以
不過這麼說來好像mirrors和nic之間的隧道無論如何都需要建了，除非把mirrors物理接到nic上

**Comment by gaoyifan** [comment]
理论上，旧mirrors也可以接入联通的 vlan（即：给 gw-nic 增加一个联通的虚拟网卡）。 
但是，mirrors 的联通流量走 tinc 应该是不可行的（tinc性能不足）。

这么看来，有两种方式：
1.  mirrors2 <-> gw-nic 打隧道
2. 物理交换机上新增一个vlan，将新旧mirrors放在其中。交换机转发的性能可能会更好一些。

***

另外，还有个麻烦事：  mirrors目前联通带宽用得较多，峰值超过1Gbps。  如果将联通线路移到 gw-nic， 就只有1Gbps的峰值性能了。
我还没想到什么好的解决方案。
