### ISSUE TITLE
gw-nic增加聯通IP

### ISSUE THREAD

**Issue by yangzhaofeng** [ustclug/discussions#217]
張老師給了我們一個新的聯通IP地址，
218.104.71.110/28 gateway 218.104.71.97
需要加到gw-nic上。

**Comment by Smart-Hypercube** [comment]
加到nic上之后做什么呢？因果关系应该不是“因为张老师给了我们地址，所以就要加上去”吧。。。

**Comment by yangzhaofeng** [comment]
目前出國隧道基本都是走移動，到香港和新加坡還好，到日本就延遲比較高了。到俄羅斯會繞路。
而聯通到日本和俄羅斯的延遲比較低，這也是我當時說要聯通IP的主要原因。

**Comment by gaoyifan** [comment]
此issue重复，讨论至 #218
