### ISSUE TITLE
關於VPN（以及部分其他服務）增加聯通IP

### ISSUE THREAD

**Issue by yangzhaofeng** [ustclug/discussions#218]
目前張老師從聯通拿到了16（實際是13）個IP，lug的服務有可能增加聯通的接入點。
對於在圖書館的機器，有幾種方案：
1 通過隧道接入至網絡中心。參見 https://servers.ustclug.org/2017/04/lug-vpn-change-cmcc-ip/
2 將需要聯通IP的機器移至網絡中心
3 在圖書館增加聯通的VLAN，需要拜託老師。

各位認為哪個方案比較靠譜

**Comment by gaoyifan** [comment]
方案 | 优势 | 缺点
-- | -- | --
1 | 配置相对简单，除了隧道，不需要做其他调整 | 有一定性能损失；与对端强耦合；降低了线路的可用性
2 | 原生网卡性能 | 由于更换机房，需要重新申请其他线路的IP地址； 需要大幅修改配置，迁移较为繁琐；可能会引入较长的停机时间
3 | 原生网卡性能；配置简单 | LUG设备所在机架的所有网口都已经分配给了特定VLAN，增加VLAN可能会有些麻烦


如果从未来可维护性的角度考虑， 排序：方案3 > 方案2 > 方案1

个人建议，先试试方案3。 
关于方案2： 我们在网络中心机房的宿主机的内存几乎用尽了（还剩4.2GB内存），如果要迁移到网络中心机房可能需要：
1. 做一些虚拟机编排上的调整
2. 或 从图书馆机房搬一台宿主机（考虑到机器已经比较老了，这么折腾的意义也不太大）
3. 或 向网络中心申请新的宿主机（周期可能会比较长）。

---

方案4. vSphere NSX 支持跨数据中心的 SDN 。 可以将一个数据中心的物理网络借助SDN技术接入到另一个数据中心， 且与虚拟交换机兼容。  与方案1有点像。
如果部署 NSX ， 虚拟机就可以跨数据中心迁移， 而不需要关心具体的网段， 虚拟机也不需要修改任何配置。

**Comment by BROBIRD** [comment]
请问是否有计划为NeatDNS增加联通IP？谢谢！（如果对你们的讨论有影响请删除这条回复
