### ISSUE TITLE
新增证书中心

### ISSUE THREAD

**Issue by volltin** [ustclug/discussions#224]
现在 LUG 的域名证书几乎都换为 Let's Encrypt 的 Wildcard 证书，目前有以下几个：

- ustclug.org *.ustclug.org
- *.proxy.ustclug.org
- lug.ustc.edu.cn *.lug.ustc.edu.cn

之后计划增加：

- mirrors.ustc.edu.cn *.mirrors.ustc.edu.cn
- centos.ustc.edu.cn debian.ustc.edu.cn

由于 Wildcard 类型证书仅支持 DNS 方式验证，建议设置一个证书中心统一处理申请，并且分发到各个服务器，具体方案还需讨论。

**Comment by volltin** [comment]
目前需要部署证书的机器列表如下：

- gateway-el (/etc/nginx/key)
- gateway-hk (/etc/nginx/key)
- web-el (/etc/nginx/key)
- gitlab (/etc/nginx/key)
- ldap (/etc/apache2/ssl/)

**Comment by volltin** [comment]
Related #22

**Comment by gaoyifan** [comment]
目前LDAP的证书是私有CA签发的，且大部分主机都手动指定了这个私有CA。  如果计划更换LDAP证书，可能需要先更改各个服务器上LDAP客户端的CA配置。

**Comment by volltin** [comment]
部分需要部署证书的路径和重载命令，可能不完整。

```
#acme.sh --issue --dns -d 'ustclug.org' -d '*.ustclug.org' -d '*.proxy.ustclug.org' -d '*.lug.ustc.edu.cn' -d 'lug.ustc.edu.cn' --yes-I-know-dns-manual-mode-enough-go-ahead-please

[gw-el]
Host=gateway-el.s.ustclug.org
Crt=/etc/nginx/key/lug.crt
Key=/etc/nginx/key/lug.key
Renew=systemctl reload nginx.service

[gw-hk]
Host=gateway-hk.s.ustclug.org
Crt=/etc/nginx/key/lug.crt
Key=/etc/nginx/key/lug.key
Renew=systemctl reload nginx.service

[web-el]
Host=
Crt=
Key=
Renew=

[ftp]
Host=vdp.s.ustclug.org
Crt=/srv/docker/ftp/ssl/server.crt
Key=/srv/docker/ftp/ssl/server.key
Renew=docker restart lugftp

[swarm]
Host=swarm.s.ustclug.org
Crt=/srv/docker/light/ssl/server.crt
Key=/srv/docker/light/ssl/server.key
Renew=docker restart light-server

[gitlab]
Host=gitlab.s.ustclug.org:2222
Crt=/etc/nginx/key/lug.crt
Key=/etc/nginx/key/lug.key
Renew=systemctl reload nginx.service

[ldap]
Host=ldap.s.ustclug.org
Crt=/etc/apache2/ssl/lug-bundle.crt
Key=/etc/apache2/ssl/lug.key
Renew=sudo systemctl reload apache2.service
```

**Comment by volltin** [comment]
Related https://gist.github.com/gaoyifan/b72f680df3e2a5d760b2f928d62d2a4f

**Comment by iBug** [comment]
关于申请这块，我有个办法，就是托管一个 zone 到更方便通过 API 修改记录的地方（比如 `acme-txt.ustclug.org` 到 Hurricane Electrics），然后把需要申请证书的记录（以 `_acme-challenge` 开头）都 CNAME 过去，这样就可以用 GitHub Actions 直接运行 dns-01 验证并把申请到的证书推送进一个仓库，每个需要用证书的主机配个 deploy key 主动 pull 并自行 reload 相关设施即可。

**Comment by iBug** [comment]
我把 `ssl-digitalocean.ustclug.org` 通过 NS 解析到 DigitalOcean 上了，DO 的 DNS 托管服务是免费的，并且支持子域名（*说你呢，Cloudflare*），是个不错的选择，并且 [acme.sh](https://github.com/acmesh-official/acme.sh) 也原生支持其 API。然后需要通过 DNS 验证的域名也都把 `_acme-challenge` 给 CNAME 过去了。

[ustclug/ssl-cert](https://github.com/ustclug/ssl-cert) 已经配置好 GitHub Actions 自动申请与更新了，运行时间我目前设的是 `8 8 * * 0`，理论上每 63 天会更新，剩下就是部署的事情了。

**Comment by taoky** [comment]
证书自动更新与监控已配置完成。
