### ISSUE TITLE
监控数据丢失

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#229]
2018年1月1日~ 2018年8月6日19:02的监控数据丢失。

**Comment by gaoyifan** [comment]
ping @volltin  @Smart-Hypercube

**Comment by volltin** [comment]
已经确认 2018 年 1 月 1 日 ~ 2018 年 8 月 7 日 00:19 数据丢失，无备份。

删除数据的语句是从 monitor.ustclug.org 前端执行的： `DELETE WHERE time > '2018-01-01';` 。
能执行的原因由于我们的 InfluxDB 配置错，没有开启认证，2018 年 8 月 7 日 00:19 已经修复权限。

改动：https://github.com/ustclug/documentations/commit/c22c515a00d4e3e405c6650f4b9add93d023accb
