### ISSUE TITLE
Server News 独立运行

### ISSUE THREAD

**Issue by volltin** [ustclug/discussions#230]
每次 LUG 服务器挂掉，servers.ustclug.org 几乎都会跟着挂掉。。。

同时留一个 Server News Telegram channel/bot 备用发消息的方法。

**Comment by gaoyifan** [comment]
servers目前运行在docker2上，可以考虑直接在docker2上做反代。

**Comment by iBug** [comment]
已于 2024 年某时间改成 Cloudflare Pages
