### ISSUE TITLE
ArchlinuxCN 源增加 push trigger

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#231]
继续 #211 关于 ArchlinuxCN 源增加 push trigger 的提议。不再 hijack 原 issue。

@lilydjwg 麻烦提供一下 ArchlinuxCN 上游的 SSH 公钥（Ed25519 preferred）

上游 trigger 的方式，`ssh mirror@ipv4.mirrors.ustc.edu.cn`

最近几天校园网在调整，我暂时登不上服务器，稍后再部署。

**Comment by lilydjwg** [comment]
先把 key 生成了：

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHHbNhOZlLhGPJHMaPn6RR8YaTFPcZb9kd3NWek78WFL repo@archlinuxcn-repo-dist
```

实现我明天再弄。另外不用 IPv6 么？这台服务器有 v6 地址。

PS: 收到的服务器指纹如下，请核对。
```
RSA key fingerprint is SHA256:ASoToOYtjVX3UZOZ/dKiNK5ThByAsOINQbvvK+/E7Ok.
```

**Comment by zhsj** [comment]
现在连不上我们的内网。。无法确认 sshd 是否监听了 ipv6 及它的指纹。。。

**Comment by lilydjwg** [comment]
没事，等你部署的时候一并处理就好。

**Comment by zhsj** [comment]
服务器 RSA 指纹正确，我们没有让 sshd 监听 ipv6 地址。
archlinuxcn 的公钥已经添加，请测试。mirrors.ustc.edu.cn/status/ 最右一栏会显示是否正在同步。

**Comment by lilydjwg** [comment]
测试完成，一切工作正常～
