### ISSUE TITLE
Problems with LibreOffice download mirror

### ISSUE THREAD

**Issue by Bambooin** [ustclug/discussions#233]
The download url doesn't redirect to USTC mirror, and the mirror list doesn't contian USTC too.

List of best mirrors for IP address 180.168.166.27, located at 31.045601,121.399696 in China (CN), network 180.168.0.0/16 (autonomous system 4812).

Mirror list info:
https://download.documentfoundation.org/libreoffice/stable/6.0.5/mac/x86_64/LibreOffice_6.0.5_MacOS_x86-64.dmg.mirrorlist

**Comment by taoky** [comment]
https://wiki.documentfoundation.org/Infra/Mirroring#I_want_to_become_a_mirror%21

**Comment by taoky** [comment]
Done.
