### ISSUE TITLE
mirrors电信出口流量限制

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#24]
近期学校电信出口上行压力比较大，建议打开vlan10的流控。
![screen shot 2016-09-13 at 1 40 52 pm](https://cloud.githubusercontent.com/assets/5450996/18462759/bc575208-79b7-11e6-9ee0-6fed19bc9c5f.png)

**Comment by knight42** [comment]
re-enabled

**Comment by gaoyifan** [comment]
@knight42 能发个公告吗？
