### ISSUE TITLE
anheng.com.cn rsync地址修改

### ISSUE THREAD

**Issue by lshw** [ustclug/discussions#244]
服务器地址修改为rsync.anheng.com.cn

发布3个目录
bjlx
loongson
loongson2f

请更新一下， 谢谢

**Comment by zhsj** [comment]
这和现在的有什么不同吗？

现在就是
* http://mirrors.ustc.edu.cn/bjlx rsync://rsync.anheng.com.cn/bjlx
* http://mirrors.ustc.edu.cn/loongson rsync://rsync.anheng.com.cn/loongson
* http://mirrors.ustc.edu.cn/loongson2f rsync://rsync.anheng.com.cn/loongson2f/

参考 http://mirrors.ustc.edu.cn/status/

**Comment by zhsj** [comment]
看了下前几天的同步日志，都是 Connection refused 。
现在已经可以成功同步了。是 anheng 的服务器之前有问题，今天才恢复？

**Comment by lshw** [comment]
看起来，好像是这个原因。。。。。
