### ISSUE TITLE
rustup update failed when use mirrors.ustc.edu.cn

### ISSUE THREAD

**Issue by huoyuanliao** [ustclug/discussions#248]
使用rustup update 更新rustc toolchain时，发现ustc 镜像提供的链接：https://mirrors.ustc.edu.cn/rust-static/dist/channel-rust-nightly.toml  不可访问。导致数据拉去失败，望修复。

**Comment by hosiet** [comment]
测试了一下：虽然不是 rustup 用户，但是直接访问这个链接是能下载到数据的。

**Comment by lilydjwg** [comment]
能访问但是很慢。

**Comment by huoyuanliao** [comment]
> 测试了一下：虽然不是 rustup 用户，但是直接访问这个链接是能下载到数据的。
通过verbose查看，发现下面这个链接也存在访问速率慢，超时失败的情况。
https://mirrors.ustc.edu.cn/rust-static/dist/20
18-10-24/rustc-nightly-x86_64-pc-windows-msvc.tar.xz
