### ISSUE TITLE
mirrors 错误邮件通知

### ISSUE THREAD

**Issue by wangliang1989** [ustclug/discussions#25]
建议发生mirrors错误等严重事件时，向邮件订阅的用户，邮件通知

**Comment by gaoyifan** [comment]
最好是与现有的servers.ustclug.org配合起来：当某个分类下新增文章时，向某个特定账号发邮件。
不知道有没有类似插件....

**Comment by knight42** [comment]
我觉得可以开一个 issue 专门用来发通知, 有需要的可以订阅.

**Comment by zhsj** [comment]
应该有一个 https://status.github.com/ 这样的页面，目前 status.u.o 和 servers.u.o 都不够统一，servers.u.o 上现在各种公告都有，status.u.o 只是监控信息，需要有个像 https://status.github.com/ 一样的网站。

**Comment by gaoyifan** [comment]
用IFTTT做了一个转发，将servers.u.o中mirrors分类下的新文章转发到Google Group中。
https://groups.google.com/forum/#!forum/ustc-mirrors
ustc-mirrors@googlegroups.com
欢迎订阅@wangliang1989
