### ISSUE TITLE
percona 不能使用

### ISSUE THREAD

**Issue by m1911** [ustclug/discussions#252]
percona 镜像里面都是404 是不是无法使用了？

**Comment by gaoyifan** [comment]
从同步日志来看，percona没有遇到显著的同步错误。由于我们这边没有percona用户，无法去尝试复现该问题。
可否提供更多的信息，如：出现404的URL，程序日志等，以便调查故障原因。

**Comment by m1911** [comment]
@gaoyifan 
http://mirrors.ustc.edu.cn/percona/release/7/RPMS/noarch/percona-release-latest.noarch.rpm 这个就是404
https://repo.percona.com/ 你们同步的不是这个吗？
https://repo.percona.com/release/ 这个下面应该有文件夹
http://mirrors.ustc.edu.cn/percona/release 但是你们的没有东西

**Comment by m1911** [comment]
@gaoyifan 
http://mirrors.ustc.edu.cn/percona/release/7/RPMS/noarch/percona-release-latest.noarch.rpm 这个就是404
https://repo.percona.com/ 你们同步的不是这个吗？
https://repo.percona.com/release/ 这个下面应该有文件夹
http://mirrors.ustc.edu.cn/percona/release 但是你们的没有东西

**Comment by gaoyifan** [comment]
官方做出去这种调整之后， 所有镜像站都需要重新同步大量数据，导致 rsync.percona.com 服务器非常繁忙。目前同步速度只有100KB/s，按照这种速度，估计需要一周以上才能同步完。

**Comment by m1911** [comment]
@gaoyifan   等同步完成就可以使用
http://mirrors.ustc.edu.cn/percona/yum/release  来进行yum 安装了吧

**Comment by m1911** [comment]
@gaoyifan 
http://mirrors.ustc.edu.cn/percona/yum/release  现在这个链接还是不存在的吗？

**Comment by gaoyifan** [comment]
软连接存在，但链接指向的目标还没同步完

**Comment by m1911** [comment]
@gaoyifan 
http://mirrors.ustc.edu.cn/percona/yum/release 连接是可以访问了但是下面的目录怎么都是空的呢？

**Comment by taoky** [comment]
（看起来这个问题很早之前就解决好了）
