### ISSUE TITLE
关于kubernetes源的问题

### ISSUE THREAD

**Issue by yw9381** [ustclug/discussions#254]
- 故障镜像的名称
kubernetes

- 首次观察到故障的时间
2018-11-12 22:02:00

- 故障描述
  1. k8s的apt源中缺少gpg公钥，即doc目录(/kubernetes/apt/doc/)
  2. k8s缺少yum源，(/kubernetes/yum/)

- 修复建议（如果有）
  1.  手动下载gpg公钥并放置
  2. 同步yum源

**Comment by taoky** [comment]
1. 关于公钥，如果需要验证从镜像站下载得到的文件的完整性，最好的方法是直接从上游获取公钥。见 <https://github.com/tuna/issues/issues/1114>
2. Yum 源已经添加。见 <https://github.com/ustclug/mirrorrequest/issues/105#issuecomment-771301958>
