### ISSUE TITLE
crates.io (Rust) 更新不及时，库新版出来好几天了也没同步过去，希望能看一看？

### ISSUE THREAD

**Issue by biluohc** [ustclug/discussions#255]
https://mirrors.ustc.edu.cn/crates.io-index/cr/os/crossbeam-channel  目前还是 0.30

https://crates.io/crates/crossbeam-channel/0.3.1
Versions
    0.3.1 Nov 9, 2018
    0.3.0 Nov 4, 2018

**Comment by ksqsf** [comment]
Looks good now. Please reopen this issue if it still doesn't work.
