### ISSUE TITLE
ustclog.org域名证书到期了

### ISSUE THREAD

**Issue by abcfy2** [ustclug/discussions#260]
apt update报错如下:

```
E: 仓库 “https://launchpad.proxy.ustclug.org/graphics-drivers/ppa/ubuntu bionic Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://launchpad.proxy.ustclug.org/jonathonf/ffmpeg-4/ubuntu bionic Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://launchpad.proxy.ustclug.org/remmina-ppa-team/remmina-next/ubuntu bionic Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://launchpad.proxy.ustclug.org/timescale/timescaledb-ppa/ubuntu bionic Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
```

点开上述链接看了下，的确证书到期了，希望解决一下。

**Comment by volltin** [comment]
thanks! fixed.

**Comment by huxuan** [comment]
貌似 ppa 还是会显示证书过期，不确定是不是内部网络有缓存的原因

**Comment by taoky** [comment]
> 貌似 ppa 还是会显示证书过期，不确定是不是内部网络有缓存的原因，网页打开证书确实已经更新了。

https://servers.ustclug.org/2021/10/mirrors-letsencrypt-cert-update/

> Update 1 (2021/10/15): 镜像站中反向代理的域名（*.proxy.ustclug.org）由于考虑其同时包含面向浏览器与命令行工具的反向代理，目前证书链中仍然包含 DST Root CA X3。如使用时遇到证书问题，可按照 https://github.com/tuna/issues/issues/1342#issuecomment-931412628 的指导更新系统的相关软件包。

**Comment by huxuan** [comment]
> > 貌似 ppa 还是会显示证书过期，不确定是不是内部网络有缓存的原因，网页打开证书确实已经更新了。
> 
> https://servers.ustclug.org/2021/10/mirrors-letsencrypt-cert-update/
> 
> > Update 1 (2021/10/15): 镜像站中反向代理的域名（*.proxy.ustclug.org）由于考虑其同时包含面向浏览器与命令行工具的反向代理，目前证书链中仍然包含 DST Root CA X3。如使用时遇到证书问题，可按照 [tuna/issues#1342 (comment)](https://github.com/tuna/issues/issues/1342#issuecomment-931412628) 的指导更新系统的相关软件包。

Thanks~ 我找时间就试试~
