### ISSUE TITLE
gcr.mirrors.ustc.edu.cn/google_containers/kube-apiserver:v1.13.2 pull的时候出错

### ISSUE THREAD

**Issue by deerjoe** [ustclug/discussions#264]
gcr.mirrors.ustc.edu.cn/google_containers/kube-apiserver:v1.13.2 pull的时候出错

[root@node1 kubespray]# docker pull gcr.mirrors.ustc.edu.cn/google_containers/kube-apiserver:v1.13.2
v1.13.2: Pulling from google_containers/kube-apiserver
73e3e9d78c61: Retrying in 1 second
503f459b2f97: Downloading [=====================>                             ]  12.39MB/28.6MB

73e3e9d78c61这层镜像一直报retrying

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/help/dockerhub.html

另外校内测试 pull 是正常的，所以关闭这个 issue。
