### ISSUE TITLE
kde neon无法从镜像上下载

### ISSUE THREAD

**Issue by xqqy** [ustclug/discussions#268]
通过浏览器试图下载KDE neon时
http://iso.mirrors.ustc.edu.cn/kde-application/neon/images/neon-useredition/20190314-0533/neon-useredition-current.iso
时报告为HTTP404错误。找不到该文件。

**Comment by Smart-Hypercube** [comment]
可能是因为当时我们还没来得及从源站同步这个文件？我这会试了一下并没有遇到问题。如果此问题仍存在，请重开这个 issue。
