### ISSUE TITLE
libgooglepinyin0_0.1.2-4_amd64.deb  Hash 校验和不符

### ISSUE THREAD

**Issue by pape2016** [ustclug/discussions#269]
文件地址：http://mirrors.ustc.edu.cn/debian/pool/main/libg/libgooglepinyin/libgooglepinyin0_0.1.2-4_amd64.deb
安装会报错：
   Hashes of expected file:
    - SHA256:047868c2558616450b912ecc8bab6bc5618ece70fd3a7da58eaf36ca44d64d12
    - MD5Sum:54db74d1439579057798d39d30ddb6e7 [weak]
    - Filesize:535874 [weak]
   Hashes of received file:
    - SHA256:efa87195ea322a033327bcbab538dc2ede6b5fca2eff5d34d5808a1fd28c2a94
    - MD5Sum:04e64513646c53c1a356a5c430a879fb [weak]
    - Filesize:535360 [weak]
   Last modification reported: Wed, 06 Jul 2016 15:21:33 +0000

这个文件的实际大小是535360字节，但是在显示出来的大小是535874，不匹配。实际的SHA和MD5校验值和标识的校验值也不一样。无法下载安装。

**Comment by zhsj** [comment]
libgooglepinyin0_0.1.2-4_amd64.deb 在服务器上的大小是 535874，这个是正确值。

Hashes of expected file 这句英文的意思是：期望的文件的哈希值，也就是正确的文件应当有的哈希值。

你下载到的文件是 535360 字节，可能是你的网络被劫持了，请将服务器地址换成 HTTPS (https://mirrors.ustc.edu.cn) 再试一下。
