### ISSUE TITLE
Cargo镜像坏了！

### ISSUE THREAD

**Issue by luojia65** [ustclug/discussions#273]
我在跑`futures-preview`，它的最新版本是`0.3.0-alpha.15`，贵校的镜像一直停留在被yank的`0.2.2`。据群友反映，大约一天前这个问题已经存在，怀疑是同步时间间隔过低造成。请处理，十分感谢！

![TIM图片20190502163818](https://user-images.githubusercontent.com/40385009/57064384-b1ab6600-6cf8-11e9-878b-14bcb4fcccd5.png)

可能有用的信息：
```
C:\Users\luojia65>rustc -V
rustc 1.36.0-nightly (9b67bd42b 2019-05-01)
C:\Users\luojia65>rustup -V
rustup 1.18.1 :: 1.18.0+20 (462683b3a 2019-04-25) dirty 1 modification
```
`Cargo.toml`
```
[dependencies]
futures-preview = "*"
```

**Comment by ksqsf** [comment]
I've just applied a hotfix. Should be fixed for now. If not, please reopen this issue and let us know.
