### ISSUE TITLE
mirrors.ustc.edu.cn：HTTP server doesn't seem to support byte ranges. Cannot resume.

### ISSUE THREAD

**Issue by zaoqi** [ustclug/discussions#274]

**Comment by phy25** [comment]
Testcase:

```shell
$ curl --silent --range 20-40 https://curl.haxx.se/docs/manpage.html | wc -c
21
$ curl --silent --range 20-40 https://mirrors.ustc.edu.cn/apache/ | wc -c
23068
$ curl --silent https://mirrors.ustc.edu.cn/apache/ | wc -c
23068
```

是否有可能是 openresty 的特性问题？

**Comment by gaoyifan** [comment]
As @phy25 mentioned, it doesn't support byte ranges for dynamic content, like directory listing. This is a feature inherited from Nginx.

When I test downloading a file, it seems normal:

```
$ curl -s http://mirrors.ustc.edu.cn/alpine/MIRRORS.txt | wc -c
1646
$ curl -s --range 20-40 http://mirrors.ustc.edu.cn/alpine/MIRRORS.txt | wc -c
21
```

**Comment by phy25** [comment]
Sorry, didn't realize that I am testing with a directory listing... @zaoqi You should probably report which specific repo and URL you are using.

**Comment by taoky** [comment]
@zaoqi I'll close this issue. And if the URL you're visiting is not dynamic content and still encounter this problem, you can provide more information and reopen the issue.
