### ISSUE TITLE
SJTUG 备用镜像链接失效

### ISSUE THREAD

**Issue by skyzh** [ustclug/discussions#275]
在 https://git.lug.ustc.edu.cn/mirrors/mirrors-backup/blob/master/redirect.lua 中

mirrors.sjtug.org -> mirrors.sjtug.sjtu.edu.cn 即可

**Comment by iBug** [comment]
感谢反馈，[已修改，等待提交][1]。

  [1]: https://git.lug.ustc.edu.cn/mirrors/mirrors-backup/merge_requests/3
