### ISSUE TITLE
manjaro arm 镜像很久没有更新

### ISSUE THREAD

**Issue by yjh1021317464** [ustclug/discussions#276]
在 manjaro arm 19.04 上会出现系统自带包比 mirror 更新的现象
mirror 中最后更新于 2018/8/17

**Comment by iBug** [comment]
New upstream: `rsync://mirrors.dotsrc.org/manjaro-arm/`

**Comment by woyuchengfengerqu** [comment]
收到回复后我把里面的所有源都看了下🤭：
https://www.uex.dk/public/manjaro-arm/		最新更新	07-Feb-2020 21:34 
https://manjaro-arm.moson.eu			最新更新	07-Feb-2020 20:34
https://smail.net.pl/manjaro-arm/		最新更新	2020-02-07 21:34
https://manjaro-arm.moson.org		最新更新	07-Feb-2020 20:34
http://natrox.jp/pub/manjaro-arm/		最新更新	08-Feb-2020 05:34
https://mirror.scachemaille.ch/manjaro-arm/	最新更新	2020-01-07 23:15
https://ftp-osl.osuosl.org/pub/manjaro-arm/repo/	最新更新	2020-02-07 20:34

**Comment by taoky** [comment]
> 收到回复后我把里面的所有源都看了下🤭：
> https://www.uex.dk/public/manjaro-arm/	最新更新 07-Feb-2020 21:34
> https://manjaro-arm.moson.eu	最新更新 07-Feb-2020 20:34
> https://smail.net.pl/manjaro-arm/	最新更新 2020-02-07 21:34
> https://manjaro-arm.moson.org	最新更新 07-Feb-2020 20:34
> http://natrox.jp/pub/manjaro-arm/	最新更新 08-Feb-2020 05:34
> https://mirror.scachemaille.ch/manjaro-arm/	最新更新 2020-01-07 23:15
> https://ftp-osl.osuosl.org/pub/manjaro-arm/repo/	最新更新 2020-02-07 20:34

前几天我私人给 dotsrc 发了封邮件……虽然没有收到回复，但是我今天看了看，他们确实恢复了 manjaro-arm 镜像的更新。目前 mirrors 的内容应该是新的。
