### ISSUE TITLE
Termux 上游已变更

### ISSUE THREAD

**Issue by wbsdty331** [ustclug/discussions#279]
原地址已经废弃
现在新的上游地址是 https://dl.bintray.com/termux

**Comment by iBug** [comment]
原来的上游还能用，暂时不需要更新，这个 issue 也先挂在这不关

**Comment by iBug** [comment]
经过调研，Bintray 上的新仓库提供的是为 Android 7 以上 (API 24+) 专门编译的包，可能不适合 API 23 以下的设备，同时也需要 Termux 版本 0.67 以上，因此不能直接替换。你可以暂时使用 https://bintray.proxy.ustclug.org/termux/termux-packages-24 来访问。
