### ISSUE TITLE
LEDE 镜像不完整

### ISSUE THREAD

**Issue by amerin** [ustclug/discussions#280]
link：
https://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/luci/
https://mirrors.ustc.edu.cn/lede/releases/18.06.4/packages/mipsel_24kc/luci/

**Comment by gaoyifan** [comment]
感谢报告。
这是由于同步速度过慢造成的问题，目前更换了线路，速度略有提高，但效果仍然不太好。请耐心等一段时间。
