### ISSUE TITLE
cri-tools缺失

### ISSUE THREAD

**Issue by jjyyjjyy** [ustclug/discussions#281]
无法下载 `https://mirrors.ustc.edu.cn/kubernetes/apt/pool/cri-tools_1.13.0-00_amd64_6930e446a683884314deef354fbd8a7c5fc2be5c69c58903ad83b69b42529da4.deb  404  Not Found [IP: 202.38.95.110 443]`

```sh
cat /etc/apt/sources.list.d/kubernetes.list
deb https://mirrors.ustc.edu.cn/kubernetes/apt/ kubernetes-xenial main

lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by phy25** [comment]
FYI https://packages.cloud.google.com/apt/pool/cri-tools_1.13.0-00_amd64_6930e446a683884314deef354fbd8a7c5fc2be5c69c58903ad83b69b42529da4.deb

**Comment by iBug** [comment]
已重新同步，谢谢反馈
