### ISSUE TITLE
mysql-repo同步异常

### ISSUE THREAD

**Issue by qiuker521** [ustclug/discussions#282]
http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/

http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-5.7-community/el/7/x86_64/

版本明显有问题，四月份（23-Apr-2019）更新的mysql 5.7.26到现在还没同步过来

**Comment by taoky** [comment]
很奇怪的事情我这里 http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/ 有 5.7.26，但是换成 https 协议就没了。

```
$ curl https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/ | grep 5.7.26
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56338  100 56338    0     0  41966      0  0:00:01  0:00:01 --:--:-- 41980
$ curl http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/ | grep 5.7.26 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
<IMG SRC="/icons/generic.gif" ALT="[FILE]"> <A HREF="mysql-community-client-5.7.2-1.el7.i686.rpm">mysql-community-client-5.7.26-..&gt;</A> 23-Apr-2019 13:39  23.6M
（以下省略）   
```

Weird.

**Comment by taoky** [comment]
@iBug 向上游提交了一个 bug report: https://bugs.mysql.com/bug.php?id=96174

**Comment by gaoyifan** [comment]
之前曾经遇到过这个问题，推测是CDN缓存引起的。
访问akamai不同的CDN节点，会得到不一样的结果，比如在我的机器上：
```
$ curl -s https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/ | grep 5.7.26 | wc -l
18
$ curl -s http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/ | grep 5.7.26 | wc -l
18
```

之前曾试过通过指定HTTP请求头控制缓存策略，但没有效果。一般，等一段时间（大概数周），等CDN缓存失效后，新版本就出现了。

**Comment by gaoyifan** [comment]
@taoky 啊，看了下报告，已经提到了CDN的问题😂

可能 reposync 能够避开列目录的坑，彻底解决这个问题

**Comment by qiuker521** [comment]
感谢各位老板支持

**Comment by wojiushixiaobai** [comment]
0.5.7.32-1.el7 的版本还没同步过来，请处理下。

**Comment by taoky** [comment]
> 5.7.32-1.el7 的版本还没同步过来，请处理下。
> ustc 只有 5.7.31
> 
> ```
> [root@localhost ~]# yum -y install mysql-community-server
> 已加载插件：fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: mirror.lzu.edu.cn
>  * extras: mirror.lzu.edu.cn
>  * updates: mirrors.huaweicloud.com
> base                                                                                           | 3.6 kB  00:00:00     
> extras                                                                                         | 2.9 kB  00:00:00     
> mysql-connectors-community                                                                     | 2.6 kB  00:00:00     
> mysql-tools-community                                                                          | 2.6 kB  00:00:00     
> mysql57-community                                                                              | 2.6 kB  00:00:00     
> updates                                                                                        | 2.9 kB  00:00:00     
> mysql-connectors-community/x86 FAILED                                          
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-connectors-community/el/7/x86_64/repodata/c22be1b7750198e609725e87be6790bc8788811c-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> To address this issue please refer to the below wiki article 
> 
> https://wiki.centos.org/yum-errors
> 
> If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
> 
> mysql-tools-community/x86_64/p FAILED                                          
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-tools-community/el/7/x86_64/repodata/5dbe4dd186ff9ba523a212f21d845bc0a850e7d5-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> mysql57-community/x86_64/prima FAILED                                          
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-5.7-community/el/7/x86_64/repodata/cae8c564a11e5fca11dbe958c273358f206f1bba-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> mysql-connectors-community/x86 FAILED                                          
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-connectors-community/el/7/x86_64/repodata/c22be1b7750198e609725e87be6790bc8788811c-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> mysql-tools-community/x86_64/p FAILED                                          
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-tools-community/el/7/x86_64/repodata/5dbe4dd186ff9ba523a212f21d845bc0a850e7d5-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> mysql57-community/x86_64/prima FAILED                                          
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-5.7-community/el/7/x86_64/repodata/cae8c564a11e5fca11dbe958c273358f206f1bba-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-connectors-community/el/7/x86_64/repodata/c22be1b7750198e609725e87be6790bc8788811c-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> 正在尝试其它镜像。
> 
> 
>  One of the configured repositories failed (MySQL Connectors Community),
>  and yum doesn't have enough cached data to continue. At this point the only
>  safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
>      1. Contact the upstream for the repository and get them to fix the problem.
> 
>      2. Reconfigure the baseurl/etc. for the repository, to point to a working
>         upstream. This is most often useful if you are using a newer
>         distribution release than is supported by the repository (and the
>         packages for the previous distribution release still work).
> 
>      3. Run the command with the repository temporarily disabled
>             yum --disablerepo=mysql-connectors-community ...
> 
>      4. Disable the repository permanently, so yum won't use it by default. Yum
>         will then just ignore the repository until you permanently enable it
>         again or use --enablerepo for temporary usage:
> 
>             yum-config-manager --disable mysql-connectors-community
>         or
>             subscription-manager repos --disable=mysql-connectors-community
> 
>      5. Configure the failing repository to be skipped, if it is unavailable.
>         Note that yum will try to contact the repo. when it runs most commands,
>         so will have to try and fail each time (and thus. yum will be be much
>         slower). If it is a very temporary problem though, this is often a nice
>         compromise:
> 
>             yum-config-manager --save --setopt=mysql-connectors-community.skip_if_unavailable=true
> 
> failure: repodata/c22be1b7750198e609725e87be6790bc8788811c-primary.sqlite.bz2 from mysql-connectors-community: [Errno 256] No more mirrors to try.
> http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-connectors-community/el/7/x86_64/repodata/c22be1b7750198e609725e87be6790bc8788811c-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
> ```

将上游 URL 从 http 调整为 https 后同步正常。可能是 http 有什么奇怪的缓存（不确定是链路的原因还是上游配置的原因）。

**Comment by wojiushixiaobai** [comment]
@taoky repo里面更新地址为 https 后，报错依旧一样，我已经尝试使用阿里云的云主机排除本地网络问题

**Comment by taoky** [comment]
> @taoky repo里面更新地址为 https 后，报错依旧一样，我已经尝试使用阿里云的云主机排除本地网络问题

Hi，我刚才开了个 CentOS 7 的 container 试了一下，执行 `yum install mysql-community-server` 没有出现报错。能否提供更详细的信息？

**Comment by taoky** [comment]
今天再次收到了 mysql-repo 版本低于上游的反馈，搜索一遍之后看到了 <https://bugs.mysql.com/bug.php?id=89713>：

> Note: the index file is generated on the server side, however due to limitation in CDN system that page might be outdated, files are still present. 

表明 CDN 的问题在于某些节点的文件列表可能过期，但是对应的文件获取是没有问题的。

并且同步日志也确认在昨天的同步中，之前下载下来上游新的包因为连接到的 CDN 节点的 HTML 列表未更新而被删除，导致此镜像中软件包版本出现问题。

目前我打算把 mysql-repo 的同步拆成三个同步任务，分别同步 apt, yum 和零散的文件。Yum 相关同步程序的工作 (<https://github.com/ustclug/ustcmirror-images/pull/63>) 应该能够在近期合并，合并测试没问题之后 mysql-repo 就会拆出来（同时尽量保持现有目录结构不变），之后同步异常的问题应该就能彻底解决了。

**Comment by skyzh** [comment]
> 5.7.34-1 至今未同步，yum安装是会报文件找不到，清华的源又连不上，太难了，帮忙看看

看了一眼，上游 index 没有这个版本。

**Comment by williamxviii** [comment]
> > 5.7.34-1 至今未同步，yum安装是会报文件找不到，清华的源又连不上，太难了，帮忙看看
> 
> 看了一眼，上游 index 没有这个版本，应该是这个 issue 要解决的问题。

mysql-ftp里面已经有了这个版本，链接见下，上游的yum好像确实没更新，清华的源好像是自己做的索引，并不是sync mysql yum repo。

http://mirrors.ustc.edu.cn/mysql-ftp/Downloads/MySQL-5.7/mysql-community-server-5.7.34-1.el7.x86_64.rpm

而且令人不解的是，repodata里面的数据是更新了，就很尴尬，指定了5.7.34-1为最新的版本却不能下载相关的文件，只能从ftp里面复制。

http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/repodata/

**Comment by taoky** [comment]
新的同步程序会在解析上游列出的目录的同时解析 apt/yum 的索引获取额外需要下载的文件，这个问题应该算是解决了。

目前使用的配置参见 <https://github.com/taoky/tsumugu/blob/pudding/examples/mysql-repo.yaml>。
