### ISSUE TITLE
nodesource 镜像似乎有缺失内容?

### ISSUE THREAD

**Issue by copyliu** [ustclug/discussions#285]
镜像地址 https://mirrors.ustc.edu.cn/nodesource/deb/

上游参见  https://deb.nodesource.com/node_12.x/dists/buster/Release 

理论上应该还有 node_11.x 和 node_12.x 才是

**Comment by gaoyifan** [comment]
https://github.com/ustclug/ustcmirror-images/blob/master/nodesource/sync-nodesource.sh#L19

**Comment by ksqsf** [comment]
script updated
