### ISSUE TITLE
建议软件源lede改名为openwrt

### ISSUE THREAD

**Issue by yousong** [ustclug/discussions#286]
LEDE和OpenWrt合并超过一年半了，LEDE这个名字在渐渐淡出

 - 建议同样的内容以`openwrt`这个名字提供 ，原来的`lede`链接依然保留
 - 首页镜像列表中的`lede`换成`openwrt`

**Comment by taoky** [comment]
更名已完成。目前访问 <mirrors.ustc.edu.cn/lede/> 会 301 至 <mirrors.ustc.edu.cn/openwrt/>
