### ISSUE TITLE
crates-io.proxy.ustclug.org down

### ISSUE THREAD

**Issue by wyxloading** [ustclug/discussions#288]
`Couldn't connect to server (Failed to connect to crates-io.proxy.ustclug.org port 443: Connection refused)`

start with Aug 7, 2019 4:19am GMT +0800

**Comment by iBug** [comment]
Thank you for the report. We've been informed by our service provider that the datacenter where one of our servers is running is suffering an outage. The affected server is the one running these proxy services. While we're sorry about our service outage, there's not much we can do for now. We're in close contact with our service provider to try to recover as soon as possible.

**Comment by taoky** [comment]
The services affected by this outage are working now.
