### ISSUE TITLE
mirror在windows和linux下的https证书验证结果不一致

### ISSUE THREAD

**Issue by zsynacl** [ustclug/discussions#290]
坐标菊厂，内网需要走公司代理访问mirror，目前的诉求是使用rust crates代理。已经正确配置了`http_proxy`和`https_proxy`。

现象：在windows下无法正常访问https的源地址，http的可以访问，但是在WSL下可以访问https源地址。另外经过测试，windows下甚至无法通过wget访问`https://mirrors.ustc.edu.cn`。

求教各位大佬帮忙解答一下，是否是网站证书在不同平台下的验证有不一致的情况，或者是其他可能的问题。

操作步骤如下：
1. 在windows中使用`https://mirrors.ustc.edu.cn/crates.io-index`作为crates源，访问失败

```cmd
D:\myrepo\mandelbrot-master>cargo build
    Updating `https://mirrors.ustc.edu.cn/crates.io-index` index
warning: spurious network error (2 tries remaining): [56] Failure when receiving data from the peer; class=Net (12)
warning: spurious network error (1 tries remaining): [28] Timeout was reached; class=Net (12)
^C
D:\myrepo\mandelbrot-master>cargo build
    Updating `https://mirrors.ustc.edu.cn/crates.io-index` index
warning: spurious network error (2 tries remaining): [28] Timeout was reached; class=Net (12)
warning: spurious network error (1 tries remaining): [56] Failure when receiving data from the peer; class=Net (12)
error: failed to query replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://mirrors.ustc.edu.cn/crates.io-index`

Caused by:
  [56] Failure when receiving data from the peer; class=Net (12)
```

wget测试结果如下：
```cmd
c:\Program Files (x86)\GnuWin32\bin>wget https://mirrors.ustc.edu.cn/crates.io-index
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = c:\Program Files (x86)\GnuWin32/etc/wgetrc
--2019-08-14 10:41:27--  https://mirrors.ustc.edu.cn/crates.io-index
正在解析主机 xx.huawei.com... x.x.x.x # 公司内网代理地址
Connecting to xx.huawei.com|x.x.x.x|:xx... 已连接。
ERROR: cannot verify mirrors.ustc.edu.cn's certificate, issued by `xxxx CA':
  Unable to locally verify the issuer's authority.
To connect to mirrors.ustc.edu.cn insecurely, use `--no-check-certificate'.
无法建立 SSL 连接。

c:\Program Files (x86)\GnuWin32\bin>wget https://mirrors.ustc.edu.cn
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = c:\Program Files (x86)\GnuWin32/etc/wgetrc
--2019-08-14 10:42:11--  https://mirrors.ustc.edu.cn/
正在解析主机 xx.huawei.com... xx.xx.xx.xx
Connecting to xx.huawei.com|xx.xx.xx.xx|:xx... 已连接。
ERROR: cannot verify mirrors.ustc.edu.cn's certificate, issued by `xxx CA':
  Unable to locally verify the issuer's authority.
To connect to mirrors.ustc.edu.cn insecurely, use `--no-check-certificate'.
无法建立 SSL 连接。
```

2. 将https地址改为http地址（`http://mirrors.ustc.edu.cn/crates.io-index`），源可以正常访问

3. 在WSL中安装公司内部CA整数，配置https的crates源代理地址（`https://mirrors.ustc.edu.cn/crates.io-index`），源可以正常访问

4. 浏览器访问地址 `https://mirrors.ustc.edu.cn/crates.io-index`，和`http://mirrors.ustc.edu.cn/crates.io-index` 均可以正常访问

**Comment by taoky** [comment]
可能需要配置 GnuWin32 的 wget（虽然我搜了一下没有找到什么资料），因为看起来你访问 mirrors 时的证书是由菊厂自签发的。

**Comment by zhsj** [comment]
> ERROR: cannot verify mirrors.ustc.edu.cn's certificate, issued by `/C=cn/ST=GuangDong/L=Shenzhen/O=Huawei/OU=IT/CN=Huawei Web Secure Internet Gateway CA':

首先，这肯定只是贵司的问题，

然后，我感觉你把贵司内网的东西贴在公网真的没问题吗？

你可以在 WSL 里 `curl -v http://mirrors.ustc.edu.cn` 看一下证书是谁签发的，如果也是 `CN=Huawei Web Secure Internet Gateway CA` 的话，说明你们的代理在两个环境行为是一致的，问题就是你在 Windows 里配的 CA 没配好。

**Comment by zsynacl** [comment]
> 
> 
> > ERROR: cannot verify mirrors.ustc.edu.cn's certificate, issued by `/C=cn/ST=GuangDong/L=Shenzhen/O=Huawei/OU=IT/CN=Huawei Web Secure Internet Gateway CA':
> 
> 首先，这肯定只是贵司的问题，
> 
> 然后，我感觉你把贵司内网的东西贴在公网真的没问题吗？
> 
> 你可以在 WSL 里 `curl -v http://mirrors.ustc.edu.cn` 看一下证书是谁签发的，如果也是 `CN=Huawei Web Secure Internet Gateway CA` 的话，说明你们的代理在两个环境行为是一致的，问题就是你在 Windows 里配的 CA 没配好。

感谢提供帮助。我会把CA信息也抹掉。

**Comment by jackhhh** [comment]
同事你好~

公司代理会强制替换部分https网站的证书为公司签发的证书，因此如果未添加公司CA或程序不认公司CA或者配置错误将会出现SSL错误。且不同软件可能有单独的代理设置。这里安利一下cntlm，配置后可以统一使用类似127.0.0.1:3128的统一地址，比较适合公司内网环境使用~

Reference:
http://3ms.huawei.com/km/groups/3198679/blogs/details/5399511
http://3ms.huawei.com/km/blogs/details/2226019

**Comment by zsynacl** [comment]
在windows和WSL下都重新使用curl测试了一下，在windows下似乎只有其中一个特定的证书才能成功访问（我安装了2个相关的证书）。不知道这个证书使用策略在windows和linux下是否有不同。

**Comment by zsynacl** [comment]
> 
> 
> 同事你好~
> 
> 公司代理会强制替换部分https网站的证书为公司签发的证书，因此如果未添加公司CA或程序不认公司CA或者配置错误将会出现SSL错误。且不同软件可能有单独的代理设置。这里安利一下cntlm，配置后可以统一使用类似127.0.0.1:3128的统一地址，比较适合公司内网环境使用~
> 
> Reference:
> http://3ms.huawei.com/km/groups/3198679/blogs/details/5399511
> http://3ms.huawei.com/km/blogs/details/2226019

之前一直都是使用的cntlm，并不能解决问题哦。而且在WSL里不是很清楚是否有坑。
