### ISSUE TITLE
移除 Fedora 镜像的 development 文件夹与 SRPM 同步

### ISSUE THREAD

**Issue by taoky** [ustclug/discussions#292]
在新的设备购买之前，mirrors2 服务器依旧需要对外正常提供服务。但是由于存储空间不足（尤其是在同步的时候，现在我们存储镜像的 pool 只有几兆的剩余空间了），服务器的 I/O 性能遇到了很严重的问题。之前我删过一些 Fedora 的旧文件（Fedora 镜像的旧文件不会随上游删除 #227），也在备份之后删了一些旧日志，但是都在过了十几天之后又被塞满了。

我注意到 tuna 的 Fedora 镜像[只占用了 1.10 TB](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status)，但我们[占用了 3.80 TB](https://mirrors.ustc.edu.cn/status/)。我粗略对比了一下，发现 tuna 的镜像没有同步 development 和 SRPM（源代码包）。我打算不再同步这两个东西，但是不知道是否有人对 Fedora 的开发版本和源代码包有实际需要。

**Comment by gameltb** [comment]
aosp 镜像似乎有一些临时文件可以删除，例如 /aosp/platform/prebuilts/ndk.git/objects/pack/tmp_pack_EuAnNM 。

**Comment by sztsian** [comment]
SRPM 可以删掉。估计国内用到的人不会太多。影响面很小。
development 可以参照此前单独介绍的情况斟酌。[ ](https://github.com/FZUG/issues/issues/1)
