### ISSUE TITLE
这个Rust crate源响应的有问题！

### ISSUE THREAD

**Issue by yaephin** [ustclug/discussions#297]
### 使用官方配置：
> [source.crates-io]
> replace-with = 'ustc'
> [source.ustc]
> registry = "git://mirrors.ustc.edu.cn/crates.io-index"
`$ cargo build`
![Screenshot from 2019-10-02 17-50-42](https://user-images.githubusercontent.com/26021404/66035393-a2497680-e53d-11e9-9b7c-5feb6b391e41.png)
### 使用github源：
> [source.crates-io]
> registry = "https://github.com/rust-lang/crates.io-index"
`$ cargo build`
![Screenshot from 2019-10-02 17-51-02](https://user-images.githubusercontent.com/26021404/66035494-d329ab80-e53d-11e9-9be3-7b964f8efbc8.png)

OS:ubuntu 18.04
Cargo version: 1.38.0-nightly
还是国内源的速度快，github可以下载但速度还是比较慢的，希望官方能修复下这个问题。

**Comment by taoky** [comment]
因为日志占满了对应的服务器，我刚刚在 crates-io.proxy.ustclug.org 对应的服务器上手动做了一次 log rotation，并 gzip 了最近 nginx 的日志。现在可能正常了，但我不是 Rust 用户，所以能否提供一些有外部依赖的 Rust 仓库，以便我可以看一下 cargo build 是否正常？

**Comment by yaephin** [comment]
已经恢复，极快地下好了，感谢！您可以任意找个项目试一下。

**Comment by wuyanxin** [comment]
一个临时的解决方法是在运行 cargo 的时候加入环境变量 `CARGO_HTTP_MULTIPLEXING=false`。
see  https://mirrors.ustc.edu.cn/help/crates.io-index.html
