### ISSUE TITLE
Fedora 镜像列表里没有 USTC 了

### ISSUE THREAD

**Issue by sztsian** [ustclug/discussions#300]
参见[  ](https://github.com/FZUG/issues/issues/1)
https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/30/x86_64

USTC 再次从列表里消失了。
上次消失的时候我[发邮件咨询过](https://lists.fedoraproject.org/archives/list/mirror-admin@lists.fedoraproject.org/thread/6L6ZANGFU4K5N52C5V2TGCPBA5CNOK2V/)，不知道对这次是否有帮助。

**Comment by taoky** [comment]
在去年八月更新服务器，以及 https://github.com/ustclug/discussions/issues/227#issuecomment-716288559 的 workaround 之后，这个问题应该早已经解决了。<https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/32/x86_64> <https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/33/x86_64> <https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/34/x86_64> 也都有 USTC。
