### ISSUE TITLE
Nginx 镜像建议增加 buster

### ISSUE THREAD

**Issue by StarDuster** [ustclug/discussions#304]
![image](https://user-images.githubusercontent.com/7328584/69157166-887ce680-0b1f-11ea-932c-7029770c6c52.png)

buster 已经是 debian stable，目前看是没有的，感觉可以有

**Comment by taoky** [comment]
可能是镜像站同步的配置有问题，我现在在检查。

**Comment by taoky** [comment]
修复好啦~

如果还有问题的话欢迎回复。
