### ISSUE TITLE
Fedora28以前的源已经失效

### ISSUE THREAD

**Issue by hao-lee** [ustclug/discussions#306]
Fedora已经将28以前的源移动到 `archives.fedoraproject.org`，但是科大镜像没有做对应修改，导致现在28以前的仓库里只有一个README文件，请求同步 `archives.fedoraproject.org`。

**Comment by taoky** [comment]
Fedora 28 已经 End Of Life 了，建议使用更新的版本。

另外现在镜像站磁盘空间很紧张，目前没有同步 `archives.fedoraproject.org` 的计划。
