### ISSUE TITLE
Linux Mint 上游因 iso 下载探测失败而将站点暂时移出列表

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#307]
2019年12月3日由 Linux Mint 上游发来的邮件显示上游通过访问 http://mirrors.ustc.edu.cn/linuxmint-cd/testing/linuxmint-19.3-cinnamon-64bit-beta.iso 而检测镜像站是否正常工作。但我们目前的设置是所有校外 ISO 访问（？）均使用 JavaScript 跳转，因此 Linux Mint 上游的自动探测可能因此失效。

**Comment by iBug** [comment]
不是所有的 ISO 都会跳转，实际上只有少数几个热门的会往固定地方 302，参见 <https://git.lug.ustc.edu.cn/mirrors/nginx-config/blob/master/snippets/redirect-iso-to-other-sites>

**Comment by taoky** [comment]
收到邮件后，已通过更换为官方上游的方式修复。

**Comment by zhsj** [comment]
> ... ISO 访问（？）均使用 JavaScript 跳转

只有 UA 里含有 Mozilla 的才会有 JavaScript Challenge。
https://git.lug.ustc.edu.cn/mirrors/nginx-config/blob/master/snippets/mirrors-redirect-thunder
https://git.lug.ustc.edu.cn/mirrors/nginx-config/blob/master/sites-available/iso.mirrors.ustc.edu.cn
