### ISSUE TITLE
Travis CI 对私有仓库有 build 数量限制

### ISSUE THREAD

**Issue by iBug** [ustclug/discussions#308]
目前只有三个仓库 mirrorhelp, ledger 和 light-doc 在用，其中 mirrorhelp 是公开仓库不计入这 100 个 trial build。虽然后两个 push 频率很低，但是一旦这 100 个 build 用完之后就要开始歇菜了。CircleCI 没有私有/公开仓库的限制，免费版每个月有 1000 分钟的容器时间，应该是非常充足的，我后面会把这两个私有仓库迁移到 CircleCI 上。

![image](https://user-images.githubusercontent.com/7273074/70344712-5399bf00-1895-11ea-9a8f-0c468e9e18b4.png)

**Comment by zhsj** [comment]
https://github.com/features/actions 有2000分钟。

**Comment by iBug** [comment]
> https://github.com/features/actions 有2000分钟。

好主意，但是我没有 GH Actions 的配置经验，回头我学习一下。

**Comment by iBug** [comment]
ledger 的 GitHub Actions 搞定了，已将 Travis CI 从该仓库撤除。

**Comment by taoky** [comment]
> ledger 的 GitHub Actions 搞定了，已将 Travis CI 从该仓库撤除。

light-doc 现在没有 CI（似乎被 @iBug 删掉了）。这个 issue 就先关掉吧。

**Comment by iBug** [comment]
> https://github.com/features/actions 有2000分钟。

更正一下，我们是 GitHub Teams，所以私仓应该是每月 3000 分钟。
