### ISSUE TITLE
salt重启后引导失败，疑似磁盘错误

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#31]
![screen shot 2016-10-08 at 11 39 36 pm](https://cloud.githubusercontent.com/assets/5450996/19214224/b5182b86-8db0-11e6-982f-feb35285cf28.png)
![screen shot 2016-10-08 at 11 41 30 pm](https://cloud.githubusercontent.com/assets/5450996/19214226/c16d212a-8db0-11e6-86aa-d99a5938539d.png)

**Comment by knight42** [comment]
Fixed
