### ISSUE TITLE
crates-io 14.0.5下载出错

### ISSUE THREAD

**Issue by zikunfan** [ustclug/discussions#310]
`error: failed to download from https://crates-io.proxy.ustclug.org/api/v1/crates/jsonrpc-client-transports/14.0.5/download`

**Comment by phy25** [comment]
$ wget https://crates-io.proxy.ustclug.org/api/v1/crates/jsonrpc-client-transports/14.0.5/download
https://crates-io.proxy.ustclug.org/api/v1/crates/jsonrpc-client-transports/14.0.5/download
Resolving crates-io.proxy.ustclug.org (crates-io.proxy.ustclug.org)... 103.121.209.188
Connecting to crates-io.proxy.ustclug.org (crates-io.proxy.ustclug.org)|103.121.209.188|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://static-crates-io.proxy.ustclug.org/crates/jsonrpc-client-transports/jsonrpc-client-transports-14.0.5.crate [following]
https://static-crates-io.proxy.ustclug.org/crates/jsonrpc-client-transports/jsonrpc-client-transports-14.0.5.crate
Resolving static-crates-io.proxy.ustclug.org (static-crates-io.proxy.ustclug.org)... 103.121.209.188
Connecting to static-crates-io.proxy.ustclug.org (static-crates-io.proxy.ustclug.org)|103.121.209.188|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14004 (14K) [application/x-tar]
Saving to: ‘download’

download                      100%[=================================================>]  13.68K  --.-KB/s    in 0s

(57.2 MB/s) - ‘download’ saved [14004/14004]

**Comment by zikunfan** [comment]
Thx, but there still some resources cannot reach out，like：`https://crates-io.proxy.ustclug.org/api/v1/crates/clap/2.33.0/download`

**Comment by zikunfan** [comment]
lets close this issue, cause it can't be solve case-by-case
