### ISSUE TITLE
http://launchpad.proxy.ustclug.org 无法使用

### ISSUE THREAD

**Issue by ricardo0624** [ustclug/discussions#312]
https://www.taterli.com/4394/ 按照这个做了以后,报类似的错误

Err:4 http://launchpad.proxy.ustclug.org/apt-fast/stable/ubuntu bionic InRelease                                                 
  Connection failed [IP: 103.121.209.188 80]
但是这个网址通过代理就能访问,跳转到ppa

**Comment by taoky** [comment]
See #270.

使用 HTTPS 应该可以解决这个问题。

**Comment by ricardo0624** [comment]
恩恩,谢谢,原来是http://launchpad.proxy.ustclug.org

现在使用https 就好了https://launchpad.proxy.ustclug.org
