### ISSUE TITLE
clojars 上游变更

### ISSUE THREAD

**Issue by z4yx** [ustclug/discussions#314]
根据 clojars/clojars-web#735 原有 rsync 服务已不再提供，镜像站可以通过 s3 协议来同步。
参考命令：

`aws --no-sign-request --endpoint-url=https://s3.us-east-2.amazonaws.com/ s3 sync --delete s3://clojars-repo-production/ /local-path`

**Comment by taoky** [comment]
我试试能不能用 <https://github.com/ustclug/ustcmirror-images/tree/master/rclone> 来同步……

**Comment by taoky** [comment]
在上个月 20 号的时候切换到了 rclone s3 同步，并且根据近几次同步日志来看是与上游的同步是正常的。

Closed.
