### ISSUE TITLE
MySQL 源 没有同步

### ISSUE THREAD

**Issue by Mozlk** [ustclug/discussions#315]
MySQL 源 没有同步

**Comment by phy25** [comment]
是什么没有同步呢？


Archive name | Last success | Last status | Update date | Upstream | Size | Syncing
-- | -- | -- | -- | -- | -- | --
mysql-ftp | 2/27/2020, 5:46:20 AM | 🙂 | 2/27/2020, 5:46:20 AM | rsync://ftp5.gwdg.de/pub/linux/mysql/ | 918.65 GB | ⏸️
mysql-repo | 2/27/2020, 5:52:22 AM | 🙂 | 2/27/2020, 5:52:22 AM | http://repo.mysql.com/ | 876.62 GB | ⏸️

**Comment by Mozlk** [comment]
哦哦，可以了😄 可能是我缓存的问题
