### ISSUE TITLE
Rust镜像地址不能使用了

### ISSUE THREAD

**Issue by kylixs** [ustclug/discussions#317]
https://mirrors.ustc.edu.cn/rust-static/rustup 不能访问

**Comment by taoky** [comment]
rust-static 是 https://static.rust-lang.org/ 的反代，而 https://static.rust-lang.org/rustup 同样返回 404。

我不写 Rust，但我看了一眼安装脚本，安装的时候访问的路径是 `${RUSTUP_UPDATE_ROOT}/dist/${_arch}/rustup-init${_ext}`，而 `RUSTUP_UPDATE_ROOT="${RUSTUP_UPDATE_ROOT:-https://static.rust-lang.org/rustup}"`。所以看起来

> https://mirrors.ustc.edu.cn/rust-static/rustup 不能访问

是正常的，因为安装的时候访问的 URL 并不是 https://mirrors.ustc.edu.cn/rust-static/rustup

Closed.
