### ISSUE TITLE
LFS 9.0 镜像的 lfs-bootscripts 有误

### ISSUE THREAD

**Issue by martin2011qi** [ustclug/discussions#319]
LFS 9.0 镜像的 lfs-bootscripts 有误，似乎是 9.0-rc1 的。
http://mirrors.ustc.edu.cn/lfs/lfs-packages/9.0/
lfs-bootscripts-20190524.tar.xz
官网md5sums ：c91b11e366649c9cec60c2552820fed5
ustc md5sums ：8b640ce5a7944c2d55b9f29d3e1f3773

**Comment by phy25** [comment]
官网链接（MD5 如上） http://linuxfromscratch.org/lfs/downloads/9.0/lfs-bootscripts-20190524.tar.xz

USTC 上游链接（MD5 如上） http://ftp.osuosl.org/pub/lfs/lfs-packages/9.0/lfs-bootscripts-20190524.tar.xz

[其它官方上游](http://linuxfromscratch.org/lfs/download.html)：
- http://ftp.lfs-matrix.net/pub/lfs/lfs-packages/9.0/lfs-bootscripts-20190524.tar.xz 8b640ce5a7944c2d55b9f29d3e1f3773
- http://mirror.jaleco.com/lfs/pub/lfs/lfs-packages/9.0/lfs-bootscripts-20190524.tar.xz 8b640ce5a7944c2d55b9f29d3e1f3773

所以并不是 USTC 的问题，请联系官方。

**Comment by martin2011qi** [comment]
联系过官方了，确实是官方换了一个时间戳不同的文件，当然文件内容是一样的。
我也顺便多比较了几个版本，9.0 和 9.1 以及相应的 rc 版也都有 md5sum 不正确的问题。官方似乎已经意识到了，应该会在下一个版本改善。

不过，针对已经发生问题的文件，你们是可以解决的吧？让官方换回以前的文件其实是很困难的，毕竟 md5sum 其实已经写在手册里了。

**Comment by phy25** [comment]
声明一下我与 USTC LUG 无关。个人观点是镜像站通常不应该修改上游提供的文件。

**Comment by martin2011qi** [comment]
如果有流程的话，那就别违反了。我一开始以为你们是自己下载。
