### ISSUE TITLE
lugwiki打开速度缓慢

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#32]
lugwiki首页打开时间超过5秒（用curl测试）
经调试发现：PHP会动态请求gravatar.com的头像。严重拖慢了加载速度。

@hosiet  有办法关掉这个功能吗？或者为头像文件添加缓存？

related: https://github.com/ustclug/discussions/issues/20

**Comment by hosiet** [comment]
@gaoyifan 没了解过 gravatar 究竟用在何处，不是很清楚。

**Comment by gaoyifan** [comment]
@hosiet  最近几个月有安装什么新插件吗？

**Comment by hosiet** [comment]
@gaoyifan 换主题之后没有装新插件。

**Comment by gaoyifan** [comment]
@hosiet  在源码中搜索了一下，似乎是avatar插件在访问gravatar

**Comment by zhsj** [comment]
那把avatar插件去了呗，我怎么没在wiki上看到任何avatar头像啊。。。。

**Comment by gaoyifan** [comment]
昨天，@knight42 已将源码中的gravatar.com修改为反向代理。目前主页秒开。

**Comment by hosiet** [comment]
@gaoyifan 魔改源代码真的没问题吗？过三个月就会忘记的。

**Comment by zhsj** [comment]
讲道理，我真的没看到 gravatar 的图片。。。。

**Comment by knight42** [comment]
我们现在用的模板 `bootstrap3` 里有用到 gravatar, 具体在 `lib/tpl/bootstrap3/tpl_functions.php` 里的 `get_gravatar` 函数, 现在已经把地址改为我们的反代了.

**Comment by gaoyifan** [comment]
@zhsj 
![screen shot 2016-10-13 at 4 05 28 pm](https://cloud.githubusercontent.com/assets/5450996/19341163/ec6a1b56-915e-11e6-9a2b-0f971009ea38.png)

**Comment by zhsj** [comment]
@knight42 我在设置里把gravatar禁用了，可以不用魔改代码了。
参考 https://www.dokuwiki.org/template:bootstrap3#layout

**Comment by knight42** [comment]
@zhsj 赞
