### ISSUE TITLE
Ubuntu Old Releases 源不可用

### ISSUE THREAD

**Issue by licess** [ustclug/discussions#320]
Ubuntu Old Releases 源目前访问都是404，是已经停止了吗？

**Comment by phy25** [comment]
- https://mirrors.ustc.edu.cn/ubuntu-old-releases/releases/
- https://mirrors.ustc.edu.cn/ubuntu-old-releases/releases/ports/releases/

[（来源）](http://mirrors.ustc.edu.cn/help/ubuntu-old-releases.html)目前都跳转到了 http://old-releases.ubuntu.com/ .

一个问题是 old-releases.ubuntu.com 似乎并不支持 443 端口访问：https://www.ssllabs.com/ssltest/analyze.html?d=old-releases.ubuntu.com&hideResults=on

**Comment by taoky** [comment]
https://servers.ustclug.org/2020/04/%e9%95%9c%e5%83%8f%e7%ab%99%e6%95%85%e9%9a%9c%e9%80%9a%e7%9f%a5-2020-04-11/

放置 ubuntu-old-releases 的机器尚未恢复。

**Comment by taoky** [comment]
ubuntu-old-releases（和 bioc）镜像的 HTTP(S) 访问已经恢复。
