### ISSUE TITLE
freebsd-pkg/FreeBSD:12:amd64/latest 没有同步? 文件还是3月2号的

### ISSUE THREAD

**Issue by viruscamp** [ustclug/discussions#321]
http://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD%3A12%3Aamd64/latest/
最后一次更新是2020-3-2的

旁边的 http://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD%3A12%3Aamd64/quarterly/ 4-16更新的，似乎是正常的

**Comment by taoky** [comment]
我看了一下日志，是因为上游 latest 下面的 digests.txz 文件消失了，同步脚本发现 metadata 下载失败，导致 latest 都同步失败了。

我不太清楚 digests.txz 文件是不是 freebsd-pkg 镜像必须要包含的文件，还是一个可选的文件。如果是可选的话，需要修改 <https://github.com/ustclug/ustcmirror-images/blob/master/freebsd-pkg/sync.sh> 的逻辑。

**Comment by ykla** [comment]
> digests.txz contains digests which	lists the cryptographic	checksums for
>      each of the packages in the repository.  This is downloaded when
>      SIGNATURE_TYPE is set to FINGERPRINTS in the repository configuration.
但是实际使用FreeBSD 12 设置该参数，也能够进行pkg update，且没有下载digests.txz。经过测试FreeBSD 11.3 和12.1 在pkg update时都没有下载digests.txz。
下图为FreeBSD 11.3，其源是有该文件的，但是并没有使用。
![QQ图片20200420085643](https://user-images.githubusercontent.com/10327999/79704673-0c144c80-82e5-11ea-8808-74dd71b34d11.png)

**Comment by taoky** [comment]
https://github.com/ustclug/ustcmirror-images/blob/master/freebsd-pkg/sync.sh 已修改，现在正在重新同步 freebsd-pkg。

**Comment by taoky** [comment]
> https://github.com/ustclug/ustcmirror-images/blob/master/freebsd-pkg/sync.sh 已修改，现在正在重新同步 freebsd-pkg。

同步完成了。Closed.
