### ISSUE TITLE
使用ustc cargo mirror编译zCore失败

### ISSUE THREAD

**Issue by kylixs** [ustclug/discussions#322]
使用cargo官方crates.io + socks proxy方式可正常编译，但使用ustc crates registry的方式编译失败，请参考链接 https://github.com/rcore-os/zCore/issues/16

**Comment by taoky** [comment]
我在本地构建了一遍，无法复现你说到的问题。

**Comment by ksqsf** [comment]
复现了，这个问题是配置不正确，设置 registry.index 的话 cargo 计算不正确。换成新配置格式即可修复：

```
[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"
```

**Comment by ksqsf** [comment]
notabug
