### ISSUE TITLE
openSUSE tumbleweed 源更新异常

### ISSUE THREAD

**Issue by KnightBlood** [ustclug/discussions#323]
Retrieving repository 'NON OSS' metadata ........................................................................[error]
Repository 'NON OSS' is invalid.
[NON OSS|http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/non-oss/] Valid metadata not found at specified URL
History:
 - File './repodata/fc1a7ff020bfe0c89fd501b5d9daa2204e874e12a2a27898636fe86f7bca1b7c-primary.xml.gz' not found on medium 'http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/non-oss/'
 - Can't provide ./repodata/fc1a7ff020bfe0c89fd501b5d9daa2204e874e12a2a27898636fe86f7bca1b7c-primary.xml.gz

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'NON OSS' because of the above error.
Retrieving repository 'OSS' metadata ............................................................................[error]
Repository 'OSS' is invalid.
[OSS|http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/oss/] Valid metadata not found at specified URL
History:
 - File './repodata/a4fa8e2c7e90d0d10978a841fcca446a0521ddf9b95d651fa306e3e74cee230e-appdata.xml.gz' not found on medium 'http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/oss/'
 - Can't provide ./repodata/a4fa8e2c7e90d0d10978a841fcca446a0521ddf9b95d651fa306e3e74cee230e-appdata.xml.gz

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'OSS' because of the above error.
Could not refresh the repositories because of errors.

**Comment by taoky** [comment]
可能是在同步的时候上游服务器刚好在更新，所以同步的结果不一致。

**Comment by KnightBlood** [comment]
已修复

**Comment by Sam0523** [comment]
openSUSE 源经常出现这个问题。据我观察软件源刷新时请求的文件（如`primary.xml.gz`）是一个指向另一个真实文件`repodata/fc1a7ff020bfe0c89fd501b5d9daa2204e874e12a2a27898636fe86f7bca1b7c-primary.xml.gz`的软链接。

不知是否可以采用先更新普通文件，后更新软链接的同步策略？

**Comment by iBug** [comment]
> 不知是否可以采用先更新普通文件，后更新软链接的同步策略？

有点困难，我们使用的同步工具是 rsync，默认行为是按文件名顺序同步，如果要实现这个需要魔改工具本身。
