### ISSUE TITLE
epel rsync error. Permission denied.

### ISSUE THREAD

**Issue by Zhang-Xianglong** [ustclug/discussions#324]
OS: CentOS 7
Tool: tunasync
epel upstream: rsync://rsync.mirrors.ustc.edu.cn/epel/

receiving file list ...
rsync: readlink_stat(".fullfilelist.bOODag" (in epel)) failed: Permission denied (13)
rsync: readlink_stat(".fullfilelist.pEODeF" (in epel)) failed: Permission denied (13)
done
IO error encountered -- skipping file deletion

**Comment by taoky** [comment]
这两个文件已经删除了，可能是去年某次不完整的同步留下来的。

**Comment by Zhang-Xianglong** [comment]
@taoky 谢谢
