### ISSUE TITLE
Ubuntu 重复同步

### ISSUE THREAD

**Issue by Zhang-Xianglong** [ustclug/discussions#326]
系统：CentOS 7
工具：tunasync
实际命令：rsync -aHvh --no-o --no-g --stats --exclude .~tmp~/ --delete --delete-after --delay-updates --safe-links --timeout=120 rsync://rsync.mirrors.ustc.edu.cn/ubuntu/ /mirrors/ubuntu

现象：
tunasync每次重启会生成一个新的日志文件。当系统重启后，我发现本次同步的文件在上次的同步日志中已经出现了。目前发现的主要是dists、pool、indices目录下的文件。

**Comment by Zhang-Xianglong** [comment]
@taoky

**Comment by taoky** [comment]
https://github.com/tuna/tunasync/issues/119

看来这是预期的结果。

**Comment by Zhang-Xianglong** [comment]
@taoky rsync同步超时和源有关系吗？

**Comment by Zhang-Xianglong** [comment]
@taoky 谢谢您的回复。

麻烦您看下这条讨论。
https://github.com/tuna/tunasync/issues/119#issuecomment-637230453

**Comment by taoky** [comment]
> @taoky rsync同步超时和源有关系吗？

可能就是单纯因为镜像站负载很大，所以就超时了。

**Comment by Zhang-Xianglong** [comment]
@taoky 好的 谢谢
