### ISSUE TITLE
rsync服务DOWN了？

### ISSUE THREAD

**Issue by RainyBow** [ustclug/discussions#328]
rsync: failed to connect to rsync.mirrors.ustc.edu.cn (202.141.176.110): Connection refused (111)
rsync: failed to connect to rsync.mirrors.ustc.edu.cn (218.104.71.170): Connection refused (111)
![1111](https://user-images.githubusercontent.com/20679042/83988173-1235b980-a975-11ea-99e5-7a84de38152f.png)

**Comment by gaoyifan** [comment]
感谢报告。这是由于昨天误操作所致，目前已修复
