### ISSUE TITLE
rust源失效

### ISSUE THREAD

**Issue by cs686** [ustclug/discussions#329]
rust源失效，failed to download from `https://crates-io.proxy.ustclug.org/api/v1/crates/rand_chacha/0.2.2/download`
你好，这个源以后还继续维护吗

**Comment by taoky** [comment]
今日凌晨，我们发现反代服务器无法连接与管理，经与服务商确认，所在主机目前出现了硬件问题。我们正在等待修复。

**Comment by taoky** [comment]
服务已经恢复。
