### ISSUE TITLE
termux的源无法使用

### ISSUE THREAD

**Issue by ZeroOne0v0** [ustclug/discussions#331]
按照提示配置好源，安装软件后无法正常执行，报错找不到libandroid-aupport.so，所有安装后的软件都无法使用，手动下载源中的php7.3的deb包后，使用dpkg进行安装后，执行软件同样报出此错误
【CANNOT LINK EXECUTABLE 'find': library 'libandroid-support.so' not found.】
我好想用php7.3（不是7.4），感谢大家的奉献

**Comment by taoky** [comment]
发 issue 之前是否有在网络上搜索过？

从 https://github.com/termux/termux-app/issues/1061 来看，很可能是环境变量 `LD_LIBRARY_PATH` 配置的问题？

**Comment by taoky** [comment]
由于没有得到有效的回复，此 issue 关闭。
