### ISSUE TITLE
VLC仓库疑似过时、未更新

### ISSUE THREAD

**Issue by 1970633640** [ustclug/discussions#333]
镜像里的版本貌似落后官网版本了

**Comment by taoky** [comment]
似乎并没有。最新的 3.0.11 是同步了的：<https://mirrors.ustc.edu.cn/videolan-ftp/vlc/3.0.11/>。

**Comment by 1970633640** [comment]
是我看错了，因为排序算法的问题，*.*.11排在*.*.2前面，所以没看到😂

**Comment by phy25** [comment]
问题解决可以关闭议题的。
