### ISSUE TITLE
镜像站访问超时、不稳定

### ISSUE THREAD

**Issue by 1900011604** [ustclug/discussions#335]
以下是两个例子：（archlinuxcn有时候会炸，pycharm，以及deepin-wine-wechat和deepin-wine-tim等从八月以来就从来没成功过）

```
sudo pacman -Syyu
:: 正在同步软件包数据库...
 core                                                 171.4 KiB   585 KiB/s 00:00 [----------------------------------------------] 100%
 extra                                               2012.3 KiB  1186 KiB/s 00:02 [----------------------------------------------] 100%
 community                                              6.1 MiB  1191 KiB/s 00:05 [----------------------------------------------] 100%
 multilib                                             195.2 KiB  1394 KiB/s 00:00 [----------------------------------------------] 100%
错误：无法从 mirrors.ustc.edu.cn : Operation timed out after 10002 milliseconds with 0 out of 0 bytes received 获取文件 'archlinuxcn.db'
错误：无法升级 archlinuxcn (下载数据库出错)
错误：未能成功同步所有数据库

yay -S pycharm           
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) pycharm-professional-2020.2.0-1

下载大小：   372.79 MiB
全部安装大小：  1098.47 MiB

:: 进行安装吗？ [Y/n] y
:: 正在获取软件包......
错误：无法从 mirrors.ustc.edu.cn : Operation timed out after 10001 milliseconds with 0 out of 0 bytes received 获取文件 'pycharm-professional-2020.2.0-1-x86_64.pkg.tar.zst'
警告：无法获取某些文件
错误：无法提交处理 (下载数据库出错)
发生错误，没有软件包被更新。
安装软件库软件包时出错
```

这是下载deepin-wine-wechat的结果

```
==> 正在创建软件包：deepin-wine-wechat 2.9.5.56-1 (2020年08月13日 星期四 15时28分39秒)
==> 获取源代码...
  -> 正在下载 deepin.com.wechat_2.6.8.65deepin0_i386.deb...
正在初始化下载：https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb
File size: 42635782 bytes
找到状态文件，但未有下载数据。重新开始下载。
正在打开输出文件 deepin.com.wechat_2.6.8.65deepin0_i386.deb.part
正在开始下载

==> 错误： 无法下载 https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb
    正在放弃...
下载源文件时出错: deepin-wine-wechat
```

**Comment by taoky** [comment]
本周六会升级服务器（见 <https://servers.ustclug.org/2020/08/mirrors-maintenance-notification-6/>），预计升级完成之后服务性能可以有所改善。

**Comment by taoky** [comment]
目前还会出现这样的情况吗？

**Comment by 1900011604** [comment]
还会的

==> 正在创建软件包：deepin-wine-wechat 2.9.5.56-1 (2020年08月17日 星期一 00时31分04秒)
==> 获取源代码...
  -> 正在下载 deepin.com.wechat_2.6.8.65deepin0_i386.deb...
正在初始化下载：https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb
File size: 42635782 bytes
正在打开输出文件 deepin.com.wechat_2.6.8.65deepin0_i386.deb.part
正在开始下载

==> 错误： 无法下载 https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb
    正在放弃...
下载源文件时出错: deepin-wine-wechat

**Comment by taoky** [comment]
> 还会的

猜测可能是网络的问题。是否尝试过将域名修改为镜像站主页右侧的「域名选择」下的其他的域名？

**Comment by 1900011604** [comment]
改过，但是最后还是会重定向到```https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb```这里来，应该怎么改呢

**Comment by taoky** [comment]
> 改过，但是最后还是会重定向到`https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb`这里来，应该怎么改呢

我刚刚试了一下，都不会出现 301/302 重定向的情况。你的 `/etc/pacman.d/mirrorlist` 是怎么配置的？

**Comment by zhsj** [comment]
这个url是aur里写死的，见 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deepin-wine-wechat#n15

**Comment by taoky** [comment]
> 这个url是aur里写死的，见 https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deepin-wine-wechat#n15

啊没注意到 deepin-wine-wechat 是个 AUR 包……那么只能改 /etc/hosts 了。

**Comment by 1900011604** [comment]
那我应该怎么改呢，我之前是把 ```/etc/pacman.d/mirrorlist``` 改了，但是不行，我的 ```/etc/hosts/``` 这个文件是这样的：
```
# Host addresses
127.0.0.1  localhost
127.0.1.1  FIRESTAR
::1        localhost ip6-localhost ip6-loopback
ff02::1    ip6-allnodes
ff02::2    ip6-allrouters
151.101.76.133 raw.githubusercontent.com
```

**Comment by taoky** [comment]
> 那我应该怎么改呢，我之前是把 `/etc/pacman.d/mirrorlist` 改了，但是不行，我的 `/etc/hosts/` 这个文件是这样的：
> 

IP 地址可以通过 `dig` 得到，例如移动出口：

```
$ dig +short cmcc.mirrors.ustc.edu.cn
202.141.176.110
```

然后在 hosts （模仿上面几行）指定 mirrors.ustc.edu.cn 为这个 IP 即可。

**Comment by SamLukeYes** [comment]
[archlinuxcn] 不是 Manjaro 的软件源

**Comment by 1900011604** [comment]
都试过了，不行，直接在https://github.com/countstarlight/deepin-wine-wechat-arch/releases?after=v2.8.0.121-1上面下载搞定了

**Comment by taoky** [comment]
我在本地、校园网环境和自己的 VPS 上（使用 `wget`）下载 <https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb> 都没有出现问题，速度也都很快（我目前没有 Arch 或 Manjaro 的环境，所以不清楚安装包时的具体情况）。所以从已有的信息来看，目前只能认为有两种可能：

- deepin-wine-wechat 这个软件包的打包有问题。（如果用其他下载工具可以正常下载这个链接的话）
- 您所在地区的网络有问题。（但是目前的信息不足，没有人能判断出到底出了什么问题）

除非有更多的反馈，否则这个 issue 会保持关闭状态。
