### ISSUE TITLE
k8s容器镜像ceph rbd插件镜像是否提供同步

### ISSUE THREAD

**Issue by zjcnew** [ustclug/discussions#336]
关于ceph rbd的几个插件镜像是否能提供镜像服务
quay.io/k8scsi/csi-provisioner:v1.6.0
quay.io/k8scsi/csi-snapshotter:v2.1.0
quay.io/k8scsi/csi-attacher:v2.1.1
quay.io/k8scsi/csi-resizer:v0.5.0
quay.io/cephcsi/cephcsi:canary

**Comment by zhsj** [comment]
不需要邮件列表和github上重复问一遍。。。

https://groups.google.com/g/ustc_lug/c/ieEzwbZj8ys/m/HRWnN3UUBQAJ

**Comment by zhsj** [comment]
quay 镜像提供了 https://github.com/ustclug/mirrorrequest/issues/135

但 quay 镜像可能有问题，见 https://github.com/ustclug/discussions/issues/259

Duplicate of #259

**Comment by zhsj** [comment]
Duplicate of #259
