### ISSUE TITLE
homebrew-bottles 包地址被重定向

### ISSUE THREAD

**Issue by cha0ran** [ustclug/discussions#337]
不知道为什么，所有的链接都被重定向了，我这里超级超级慢啊。就像这样
```bash
==> Upgrading libpq 12.3 -> 12.4 
==> Downloading https://cmcc.mirrors.ustc.edu.cn/homebrew-bottles/bottles/libpq-12.4.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/dae00b7442212f928e157405e8899c7fa912bb445bfeed07f52c1de94b04b2a2?response-content
```
要怎么让它不被重定向呀，使用第三方源原本就是为了提速，结果现在不管换什么源都会被重定向到巨慢的CDN，DNS污染么？

**Comment by taoky** [comment]
初步推断是 homebrew-bottles 同步的问题。

相关 issues:
- https://github.com/tuna/issues/issues/930
- https://github.com/gaoyifan/homebrew-bottle-mirror/issues/6

**Comment by taoky** [comment]
在 https://github.com/ustclug/ustcmirror-images/commit/9b24016a60b990512c0896a1aed3df8b7818337f 中尝试修复了这个问题，现在正在跑同步中。

**Comment by taoky** [comment]
同步完成。Fixed.
