### ISSUE TITLE
mingwin64 文件名解释一下

### ISSUE THREAD

**Issue by anlexN** [ustclug/discussions#340]
不明白的你文件名的意思
![image](https://user-images.githubusercontent.com/8686739/92851342-0a782c00-f420-11ea-9c53-12ebbba669d0.png)

**Comment by hosiet** [comment]
镜像站对 msys2 上游文件只是提供镜像，并不会进行修改。这样的文件名命名方式是由 MSYS2 上游确定的。请联系 MSYS2 社区或者上游开发人员来了解命名规范的来源和文件使用方式。

**Comment by anlexN** [comment]
联系方式发给我
