### ISSUE TITLE
rust crates 还会提供服务吗?

### ISSUE THREAD

**Issue by fundon** [ustclug/discussions#342]

**Comment by ksqsf** [comment]
Hi，我测试了一下，Rust crates 现在可以正常使用。请问你遇到了什么问题呢？

**Comment by fundon** [comment]
30分钟前，一直报代理错误，然后到 https://mirrors.ustc.edu.cn/ 也搜不出来了，我以为下线了

**Comment by ksqsf** [comment]
👌，没问题的话我就先 close 了。
