### ISSUE TITLE
rust-static 不能使用

### ISSUE THREAD

**Issue by CrazyPandas** [ustclug/discussions#343]
环境变量
`RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup`
`RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static`

执行命令 `rustup update`

得到结果：

```
🔥10/09/20|Friday|09:16:28 ❯ rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
error: could not download file from 'https://mirrors.ustc.edu.cn/rust-static/dist/channel-rust-stable.toml.sha256' to 'C:\Users\Administrator\.rustup\tmp\3fjzs2ny2p74eu4a_file'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc update failed - rustc 1.46.0 (04488afe3 2020-08-24)

info: cleaning up downloads & tmp directories
```
是rust-static的代理方式变了吗，请问现在应该怎么操作？

**Comment by wicast** [comment]
这个很可能与lets encrypt的 OCSP Server 被整有关，curl wget 对OCSP 校验似乎比较严格？
想办法找一个 ocsp.int-x3.letsencrypt.org 这个域名能用的ip改hosts试试看

**Comment by taoky** [comment]
> 这个很可能与lets encrypt的 OCSP Server 被整有关，curl wget 对OCSP 校验似乎比较严格？
> 想办法找一个 ocsp.int-x3.letsencrypt.org 这个域名能用的ip改hosts试试看

https://mirrors.ustc.edu.cn 很早之前就启用了 OCSP stapling。可以使用 `openssl s_client --connect mirrors.ustc.edu.cn:443 --status` 来测试。

这个问题可能还是因为 mirrors 到 rust-static 站点的反代有一些连通性的问题，因为我这里测试结果有时候正常，有时候超时，可能还需要一些时间来处理。

**Comment by iBug** [comment]
我们调整了一下镜像站的网络配置，看起来 `static.rust-lang.org` 的连通性问题暂时解决了。如果还有后续问题，可以直接在这里继续回复。
