### ISSUE TITLE
freebsd-ports 源缺少 texlive-20150523-texmf.tar.xz这个包

### ISSUE THREAD

**Issue by ykla** [ustclug/discussions#345]
上游地址
http://distcache.freebsd.org/ports-distfiles/Tex/texlive-20150523-texmf.tar.xz
ustc镜像没有这个包，可能是因为太大了没有镜像下来？有1804M这么大，安装kde 桌面会用到。
![IMG_20201101_171004](https://user-images.githubusercontent.com/10327999/97798889-e4853180-1bef-11eb-94f4-773861bf3445.jpg)

**Comment by taoky** [comment]
我看了一下镜像站的同步日志，发现有大量包下载时出现了 404，也有一部分包下载成功。暂时不确定是否为同步容器镜像的问题 (<https://github.com/ustclug/ustcmirror-images/tree/master/freebsd-ports>).

**Comment by gaoyifan** [comment]
synced http://mirrors.ustc.edu.cn/freebsd-ports/distfiles/TeX/texlive-20150523-texmf.tar.xz
