### ISSUE TITLE
kubernetes 源数据不同步

### ISSUE THREAD

**Issue by JoveYu** [ustclug/discussions#348]
目前使用的kubernetes种缺少yum源，当前apt源的数据也严重滞后，我看上游是google，是否可以考虑修改上游，比如清华源

**Comment by taoky** [comment]
> 目前使用的kubernetes种缺少yum源，当前apt源的数据也严重滞后

今晚会检查 k8s.apt 同步的配置，可能是因为配置没有及时更新。

> 我看上游是google，是否可以考虑修改上游，比如清华源

目前不作考虑。

**Comment by taoky** [comment]
同步完成。
