### ISSUE TITLE
主页获取发行版映像功能支持Kali Linux

### ISSUE THREAD

**Issue by m2kar** [ustclug/discussions#349]
Kali Linux是一个广泛使用的安全测试用Linux发行版，可否在主页上支持此Linux的安装镜像获取呢？

![image](https://user-images.githubusercontent.com/16930652/102962924-d0401f80-4522-11eb-9745-97a983026eb7.png)

当前kali安装镜像位置： 

https://mirrors.ustc.edu.cn/kali-images/

**Comment by taoky** [comment]
我晚上来改一下 https://git.lug.ustc.edu.cn/mirrors/mirrors-index/-/blob/master/genisolist.ini 吧。

**Comment by taoky** [comment]
首页已经更新。因为 Kali Linux 是滚动更新的发行版，首页 ISO 下载只列出最新的版本（`current` 目录对应的版本，目前是 2020.4）。
