### ISSUE TITLE
换个监控前端

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#35]
感觉可以把现在的 ganglia-web 换掉，不如换个好看点的 grafana。
底层监控如果不方便改的话，可以继续用 ganglia gmond。

gmetad 可以把收集的日志记录到 graphite，然后 grafana 可以显示 graphite 的日志。
不过如果可以自己写一个 grafana 的 plugin，直接读取 gemtad 的数据就更好了。。。

**Comment by zhsj** [comment]
说到监控底层的话，gmond比较适合集群（同一个组播域），collectd比较适合单个机器，各位倾向哪种？

**Comment by StephenPCG** [comment]
我对collectd的理解，它是一个 **collect**-**daemon**，也就是说，它的主要作用是**collect**。而数据存储，则可以很随意，即可以存在本地的rrd中（通过rrd这个插件实现，collectd.conf中如果关闭了rrd插件，那么本地就不会有任何保存）。collect可以将采集到的数据送到其他地方，比如给graphite（准确的说是carbon cache），比如给influxdb，也可以给gmetad。我现在公司里用的是collectd->graphite的方案，本地也保存一份，这样当网络出现故障时也可以查看本地保存的数据。

曾经尝试过用sensu来采集数据，但是sensu是ruby实现的，大量的采集数据的插件（比如采集CPU、内存信息）也是ruby实现的，因此性能极差，阿里云上1核的机器，部署上sensu，sensu本身就能耗掉20%的CPU，因此后来放弃sensu了。

**Comment by zhsj** [comment]
gmond也是只collect，但与collectd的区别是，同一个组播域的机器会把数据发送到组播地址，然后配置了接受组播信息的gmond会把整个集群的数据收集过来存在内存里，然后等gmetad来收集。

**Comment by StephenPCG** [comment]
对于ganglia，我觉得已经逐渐不再适合现在的业务情形了。ganglia就采集数据方面跟collectd没有多大的差别，基础数据的采集性能都很好，也可以通过python方便的实现插件。而ganglia-web的功能，我觉得逐渐有些落伍了。在早年，大家监控所关注的主要还是基础数据层面，而现在更多关注应用层面的数据监控，ganglia-web自己默认带了许多很有用的预定义好的绘图规则，但是对于用户定义的数据绘图时，功能就比较受限了。而graphite/grafana上，则灵活很多，用户可以从后端取出一个或者多个series的数据，进行各种聚合、运算，绘图的种类也可以自己随便定（比如同样是内存，ganglia只有一种绘图方式，就是stack，而grafana中，可以只挑感兴趣的某个指标如used画曲线；可以将两台机器的内存聚合起来画一张图，也可以将两台机器的数据画在一张图上方便比较）。

**Comment by zhsj** [comment]
ganglia-web我也觉得实在太丑了，也没人去改善。。。不过ganglia-web自定义绘图还可以啊，比如现在mirrors status页面上那几幅图就是自定义的。

**Comment by StephenPCG** [comment]
我觉得，对于**collect**来说，gmond和collectd区别不大，都可以用。我印象中，gmond的数据也未必需要发给gmetad，也可以配置发送给其他的数据存储媒介。“组播”这个feature，我觉得实用性是有限的，并不会简化部署配置。

**Comment by zhsj** [comment]
gmond 的数据不会主动发送给存储后端，需要主动去抓取的。比如 gmetad 去主动抓取，然后 gmetad 抓了之后，可以选择存到本地 rrd 数据库，还是存到其他地方如 graphite。

gmond 的优点确实感觉有用的就是组播。。。但一般上了规模才会用到这个 feature。。。。
比如freeshell 7台机器是一个组播域，这样在存储后端那里只需写一个抓取地址而不用写7个。

**Comment by StephenPCG** [comment]
我已经很久没有用ganglia了，上一次用还是3年前。我记得那个时候，我们没有用组播，同一个机房所有的gmond都发送给该机房的某一个gmond，然后这个gmond再跨机房向总的gmetad那里灌（因为有多个机房）。我印象中并不是gmetad去抓取，而是gmond灌的，不过也可能是我记错了。但我们没有用组播，这是确定的。

**Comment by shankerwangmiao** [comment]
直接用 telegraf + influxdb + grafana 吧

**Comment by zhsj** [comment]
@shankerwangmiao 收集+存储这个区别不大。。就是前端看来大家一致好评grafana啊

**Comment by shankerwangmiao** [comment]
嗯嗯嗯，不过感觉 grafana 和 influxdb  是绝配啊

**Comment by gaoyifan** [comment]
monitor.ustclug.org

Grafana + InfluxDB + Telegraf

目前仅添加了mirrors

**Comment by bojieli** [comment]
@gaoyifan 赞！Memory 图里面，为什么 mirrors 超过 200G 的内存是 used，而 cached 只有 30G？是不是 ZFS cache 使用的内存被计入 used 而非 cached 了？

**Comment by gaoyifan** [comment]
增加[Neat DNS监控](https://monitor.ustclug.org/dashboard/db/neatdns)，欢迎吐槽

**Comment by gaoyifan** [comment]
目前 monitor.ustclug.org 监控范围已超过 status.ustclug.org 。
