### ISSUE TITLE
homebrew-bottles从1月9日后一直没有更新

### ISSUE THREAD

**Issue by meteormatt** [ustclug/discussions#350]
是不是同步失败了？
![图片](https://user-images.githubusercontent.com/424475/104727893-1038a200-5771-11eb-8ea4-35bf23f7d743.png)

**Comment by taoky** [comment]
> 是不是同步失败了？

是的，同步程序执行失败了。

关联 issue: https://github.com/gaoyifan/homebrew-bottle-mirror/issues/9

**Comment by taoky** [comment]
同步程序问题已由 <https://github.com/gaoyifan/homebrew-bottle-mirror/pull/10> 与 <https://github.com/gaoyifan/homebrew-bottle-mirror/pull/11> 修复，并且重新同步已完成。
