### ISSUE TITLE
请求修改上游源（不定期更新，发现就反馈）

### ISSUE THREAD

**Issue by teszNU** [ustclug/discussions#351]
2021年2月2日
part1：dotdeb上游源地址建议更改为“rsync://packages.dotdeb.org”；本人已查明上游源已经做了变更；
part2：nodesource上游源建议更改为“https://github.com/nodesource/distributions.git”；

**Comment by taoky** [comment]
> part1：dotdeb上游源地址建议更改为“rsync://packages.dotdeb.org”；本人已查明上游源已经做了变更；

Dotdeb 上游已经停止维护了，见 <https://www.dotdeb.org/>：

> Mirrors won’t be monitored or supported anymore. The rsync server will be decommissioned.

> part2：nodesource上游源建议更改为“https://github.com/nodesource/distributions.git”

如果真的去看过 <https://github.com/nodesource/distributions> 的内容的话，就会发现这个仓库中**并没有软件包**。目前我们的同步程序逻辑在 <https://github.com/ustclug/ustcmirror-images/blob/master/nodesource/sync-nodesource.sh> 中，如果发现问题（例如版本过时等）欢迎指出。
