### ISSUE TITLE
PXE 安装 Debian Bullseye 失败

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#352]
EFI 模式，校内安装 Debian Bullseye，提示 "no kernel modules found"

![image](https://user-images.githubusercontent.com/5450996/106878254-b0506e00-6714-11eb-8c9e-c2641130fe97.png)

**Comment by zhsj** [comment]
这个应该是Debian的问题，在bullseye没有release前，总会有时间段，installer里的内核和源里的内核不匹配。安装testing的正规方法是先安装stable，然后升级到testing。

**Comment by zhsj** [comment]
也就是说，现在用testing的network installer也会出一样的问题，而不是pxe的问题。

**Comment by gaoyifan** [comment]
[debian-testing-amd64-netinst.iso](https://mirrors.ustc.edu.cn/debian-cdimage/weekly-builds/amd64/iso-cd/debian-testing-amd64-netinst.iso) 安装过程一切正常
我查了下 PXE 的启动参数，配置的内核的确指向 Bullseye，应该不是我们的问题。这个 issue 先关闭了
