### ISSUE TITLE
建议更新KDE plasma镜像源

### ISSUE THREAD

**Issue by congruiIT** [ustclug/discussions#353]
源地址：http://download.kde.org/stable/plasma/5.21.1
5.21.1已出，镜像版本仍停留在5.20.2。

**Comment by myl7** [comment]
在 https://mirrors.ustc.edu.cn/status/ 界面上可以查到，USTC Mirror KDE 的上游是 rsync://mirror.cc.columbia.edu/kde/ ，而目前此上游尚未更新到 5.21.1。
请稍等一段时间，如上游一直不更新到最新版本，我们会考虑相应的解决方案。

**Comment by myl7** [comment]
目前 KDE 上游已切换到官方源，在同步完成后应该就能有最新版本的镜像，具体状态可以在 https://mirrors.ustc.edu.cn/status/ 查看。
