### ISSUE TITLE
更新pve 缺失文件

### ISSUE THREAD

**Issue by qzwl** [ustclug/discussions#354]
http://mirrors.ustc.edu.cn/proxmox/debian/pve/dists/buster/pve-no-subscription/binary-amd64/libzpool4linux_2.0.3-pve2_amd64.deb 没有这个文件。是我这边的原因吗

**Comment by iBug** [comment]
你好，proxmox 仓库的同步频率是每天凌晨一次，可能是由于该文件太新而没有被同步到。我刚才已经重新同步了一次，这个文件现在存在了。

**Comment by qzwl** [comment]
> 你好，proxmox 仓库的同步频率是每天凌晨一次，可能是由于该文件太新而没有被同步到。我刚才已经重新同步了一次，这个文件现在存在了。

非常感谢，这么晚还能及时回复。
