### ISSUE TITLE
homebrew-bottles mirrors sync errors

### ISSUE THREAD

**Issue by cxwx** [ustclug/discussions#355]
···
==> Upgrading 3 outdated packages:
ensmallen 2.16.2 -> 2.16.2_1
armadillo 10.3.0 -> 10.4.0
mlpack 3.4.2 -> 3.4.2_1
==> Upgrading ensmallen 2.16.2 -> 2.16.2_1
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/armadil
#=#=#                                                                       ###############################################################           88######################################################################## 100.0%
Error: SHA256 mismatch
Expected: fbda88ac109efeb559f7a3acc1e16a65d4019b0e08e2c9fc8d417db6e9c817ac
  Actual: 149e40e4ba150a3cbee0e5f8ae1a4fa833db11b817cb9b15f2b68e18bfce291e
    File: /Users/chenxu/Library/Caches/Homebrew/downloads/01843d82ed8ba0eb974aca70a55a44d4ec389ba2125d706c35ba0c325f1095df--armadillo-10.4.0.big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
···

from origin source is OK！

armadillo bottle 损坏了。重新同步一下应该就可以了

**Comment by gaoyifan** [comment]
这似乎是一个来自上游的错误，出现了同名但 hash 不同的文件
```
./rsync-huai.log:.by-hash/149e40e4ba150a3cbee0e5f8ae1a4fa833db11b817cb9b15f2b68e18bfce291e
./rsync-huai.log:bottles/armadillo-10.4.0.big_sur.bottle.tar.gz => .by-hash/149e40e4ba150a3cbee0e5f8ae1a4fa833db11b817cb9b15f2b68e18bfce291e
```

目前上游元数据已经更新，正在重新同步

**Comment by gaoyifan** [comment]
同步完成
