### ISSUE TITLE
homebrew的core和cask自4.30后就没有更新？

### ISSUE THREAD

**Issue by crazyi** [ustclug/discussions#357]
[core](http://mirrors.ustc.edu.cn/homebrew-core.git/)和[cask](http://mirrors.ustc.edu.cn/homebrew-cask.git/)一直没有更新，请问是什么原因？而[bottles](http://mirrors.ustc.edu.cn/homebrew-bottles/)是正常的

**Comment by Wongboo** [comment]
同问，我也才发现，换了官方原试了试才确认

**Comment by crazyi** [comment]
> 同问，我也才发现，换了官方原试了试才确认

清华的core和cask是正常的，但是bottles有问题，我现在是两个混着用

**Comment by taoky** [comment]
目前已更新。

未更新的原因可能为从 4/30 开始，同步程序一直在等待 GitHub 的数据包，但是直到今日中午仍未完成接收。在重启同步之后完成了更新。
