### ISSUE TITLE
Proxmox 源缺失文件

### ISSUE THREAD

**Issue by nightcoffee** [ustclug/discussions#359]
访问以下地址显示404
https://mirrors.ustc.edu.cn/proxmox/debian/pve/dists/buster/pve-no-subscription/binary-amd64/libquorum5_3.1.2-pve1_amd64.deb
但官方源是正常的
http://download.proxmox.com/debian/pve/dists/buster/pve-no-subscription/binary-amd64/libquorum5_3.1.2-pve1_amd64.deb

**Comment by phy25** [comment]
现在再试的话看起来已经正常了，如果这是新发布的版本，同步不及时是正常的。
