### ISSUE TITLE
mysql-repo 数据不同步

### ISSUE THREAD

**Issue by ivmm** [ustclug/discussions#360]
http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-8.0-community/el/8/x86_64/repodata/repomd.xml

这个文件更新了，但是文件里面的数据文件全部没有同步，导致yum更新失败

**Comment by taoky** [comment]
Duplicate with https://github.com/ustclug/discussions/issues/282

这个是老问题了，本来打算在寒假的时候搞定，结果一直拖到现在。希望能在学校的事情都处理完之后搞定吧……
