### ISSUE TITLE
homebrew bottles镜像方式修改

### ISSUE THREAD

**Issue by tacticalmixtu** [ustclug/discussions#364]
[Remove HOMEBREW_BOTTLE_DOMAIN](https://github.com/Homebrew/brew/pull/11781)

HOMEBREW_BOTTLE_DOMAIN似乎不再被使用了, 转而改用HOMEBREW_ARTIFACT_DOMAIN的方式下载bottles

**Comment by gaoyifan** [comment]
HOMEBREW_ARTIFACT_DOMAIN 的路径规则发生了较大的变化，可能需要修改同步程序以应对这个问题

```
==> Downloading https://ghcr.io/v2/homebrew/core/jq/manifests/1.6-1
==> Downloading from https://mirrors.ustc.edu.cn/homebrew-bottles/ghcr.io/v2/homebrew/core/jq/manifests/1.6-1
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "jq_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/jq/manifests/1.6-1
Warning: Bottle fetch failed, fetching the source instead.
==> Downloading https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz
==> Downloading from https://mirrors.ustc.edu.cn/homebrew-bottles/github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "jq"
Download failed: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz
```

**Comment by gaoyifan** [comment]
`https://mirrors.ustc.edu.cn/homebrew-bottles/ghcr.io/v2/homebrew/core/jq/manifests/1.6-1`

这种路径规则不包含 系统版本信息，这样一来，会出现不同系统版本的botlles file 路径完全相同的情况。导致不可能被正确镜像

P.S. 对比之前的路径格式：`https://mirrors.ustc.edu.cn/homebrew-bottles/jq-1.6.arm64_big_sur.bottle.1.tar.gz`

**Comment by taoky** [comment]
Related: https://github.com/Homebrew/brew/issues/11209

**Comment by gaoyifan** [comment]
Relates: https://github.com/Homebrew/discussions/discussions/1906

**Comment by haoranliu666** [comment]
用了ustc的镜像后改不回去了
每次都要用 unset HOMEBREW_BREW_GIT_REMOTE HOMEBREW_CORE_GIT_REMOTE

**Comment by taoky** [comment]
> 用了ustc的镜像后改不回去了 每次都要用 unset HOMEBREW_BREW_GIT_REMOTE HOMEBREW_CORE_GIT_REMOTE

@haoranliu666  请阅读 <https://mirrors.ustc.edu.cn/help/brew.git.html> 与 <https://mirrors.ustc.edu.cn/help/homebrew-core.git.html>。

如果仍有问题，请新开 issue 并附上详细的问题说明。

**Comment by haoranliu666** [comment]
> > 用了ustc的镜像后改不回去了 每次都要用 unset HOMEBREW_BREW_GIT_REMOTE HOMEBREW_CORE_GIT_REMOTE
> 
> @haoranliu666 请阅读 https://mirrors.ustc.edu.cn/help/brew.git.html 与 https://mirrors.ustc.edu.cn/help/homebrew-core.git.html。
> 
> 如果仍有问题，请新开 issue 并附上详细的问题说明。

谢谢，搞定了。
用文件编辑器打开 ~/.zshrc ，删除以下内容：
echo 'export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"' >> ~/.zshrc

**Comment by ErnestDong** [comment]
所以请问镜像方式修改了吗？还是每次都走ghcr

**Comment by taoky** [comment]
> 所以请问镜像方式修改了吗？还是每次都走ghcr

@ErnestDong 请开新 issue，并附上详细信息以便调试。
