### ISSUE TITLE
是否该恢复conda源了

### ISSUE THREAD

**Issue by suruoxi** [ustclug/discussions#365]
目前国内似乎还没有好的conda源，清华的对于稍大一点的包，经常会断。 ustc的源时候可以把conda加回来？

**Comment by skyzh** [comment]
> 目前国内似乎还没有好的conda源

https://mirrorz.org/list/anaconda

**Comment by taoky** [comment]
1. 在今年二三月份，根据校内的测速结果，目前我们的 pypi 和 conda 源修改为了 302 至 BFSU。
2. Pypi 和 conda 源预计未来会以反代的方式恢复。
