### ISSUE TITLE
git.lug.ustc.edu.cn  连接不上去

### ISSUE THREAD

**Issue by sdli1995** [ustclug/discussions#366]
gitlab 用不了了

**Comment by skyzh** [comment]
Hi, 我这边（北京联通）测试是 ok 的。

**Comment by iBug** [comment]
gitlab 虚拟机之前又莫名其妙关机了，我刚开起来了

**Comment by sdli1995** [comment]
> Hi, 我这边（北京联通）测试是 ok 的。

> gitlab 虚拟机之前又莫名其妙关机了，我刚开起来了

估计网络抽风吧 
10点左右上海这边aliyun服务器和联通 都连不上  这会又可以了

**Comment by taoky** [comment]
从目前得到的日志看问题可能与 https://kb.vmware.com/s/article/2089321?lang=zh_CN 有关，可能调高 NFS 服务器的 grace time 来缓解这个问题。虽然 ESXi 和 NFS 的机器在同一个子网里，照理来说不应该出现严重的网络问题。

**Comment by gaoyifan** [comment]
最近图书馆内网二层似乎不太稳定，表现为链路中断，发送出去的广播/单播报文均收不到
这个现象从 2021/08/06 01:44:44 初次出现
可能与 NFS 的网络问题相关

**Comment by iBug** [comment]
@gaoyifan esxi-6 和 NFS 之间只有一个我们自己的 VLAN 交换机，似乎还没有到“图书馆内网”的层面

**Comment by taoky** [comment]
最近两天又出现了这个问题，所以 reopen 此 issue。

**Comment by taoky** [comment]
> 最近两天又出现了这个问题，所以 reopen 此 issue。

下午东图的虚拟机又全被关掉了。这次我把 Datastore 从 NFS 4.1 改到了 NFS 3。不知道能不能解决问题。

**Comment by taoky** [comment]
> > 最近两天又出现了这个问题，所以 reopen 此 issue。
> 
> 下午东图的虚拟机又全被关掉了。这次我把 Datastore 从 NFS 4.1 改到了 NFS 3。不知道能不能解决问题。

到目前已经稳定跑了半个月，这个 issue 应该能 close 了。
