### ISSUE TITLE
网站图标在Firefox上无法显示

### ISSUE THREAD

**Issue by 1900011604** [ustclug/discussions#367]
以前edge和firefox上都没有图标，现在edge有了但是firefox没有：
![图片](https://user-images.githubusercontent.com/65082432/128896544-df1e6d3e-ae5e-4101-b06f-873de3dd75b8.png)

**Comment by taoky** [comment]
Fixed in https://git.lug.ustc.edu.cn/mirrors/mirrors-index/-/commit/aab1421278ca2b2724cf2854b1cad49d97055db5

**Comment by 1900011604** [comment]
Thanks!
