### ISSUE TITLE
http://deb.debian.org/debian  404

### ISSUE THREAD

**Issue by archdesigner** [ustclug/discussions#368]
官方在国内无法访问了，访问咱们的源也是这样404了，据说dns好像被污染了，求check

Get: 2 http://deb.debian.org/debian stable-updates InRelease [36.8 kB]
Err http://deb.debian.org/debian-security stable/updates Release                                                            
  404  Not Found [IP: 151.101.74.132 80]

**Comment by taoky** [comment]
请问您的 Debian 版本是？Debian 11 "Bullseye" 的安全更新仓库名有更改，请参考 https://mirrors.ustc.edu.cn/help/debian-security.html 修改。

**Comment by iBug** [comment]
Debian Bullseye 的更新，不再使用 `<dist>/updates` 的形式了，镜像站和 deb.debian.org 没有问题

<https://wiki.debian.org/NewInBullseye#Changes>

**Comment by archdesigner** [comment]
原来如此，感谢两位

**Comment by archdesigner** [comment]
打扰，目前版本是debian 10这个如何去做？刚搜索半天没找到，求资料 @iBug @taoky

**Comment by taoky** [comment]
> 打扰，目前版本是debian 10这个如何去做？刚搜索半天没找到，求资料 @iBug @taoky

Debian 10 现在是 `oldstable`。如果需要保持在这个版本，需要把配置中的 `stable` 改成 `buster`。

**Comment by archdesigner** [comment]
apt-get update
Get:1 http://mirrors.ustc.edu.cn/debian stable InRelease [113 kB]
Err:1 http://mirrors.ustc.edu.cn/debian stable InRelease
  At least one invalid signature was encountered.
Get:2 https://packages.sury.org/php buster InRelease [6837 B]
Err:2 https://packages.sury.org/php buster InRelease
  At least one invalid signature was encountered.
Get:3 http://mirrors.ustc.edu.cn/debian-security bullseye-security InRelease [44.1 kB]
Err:3 http://mirrors.ustc.edu.cn/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Get:4 http://mirrors.ustc.edu.cn/debian stable-updates InRelease [36.8 kB]
Err:4 http://mirrors.ustc.edu.cn/debian stable-updates InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://mirrors.ustc.edu.cn/debian stable InRelease: At least one invalid signature was encountered.
E: The repository 'http://mirrors.ustc.edu.cn/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packages.sury.org/php buster InRelease: At least one invalid signature was encountered.
E: The repository 'https://packages.sury.org/php buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirrors.ustc.edu.cn/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://mirrors.ustc.edu.cn/debian-security bullseye-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirrors.ustc.edu.cn/debian stable-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://mirrors.ustc.edu.cn/debian stable-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by archdesigner** [comment]
> buster

非常感谢！
