### ISSUE TITLE
freebsd-pkg 源 FreeBSD-12-latest 升级失败，报错 packagesite.pkg: Not Found

### ISSUE THREAD

**Issue by viruscamp** [ustclug/discussions#369]
freebsd-pkg 源 FreeBSD-12-latest 升级失败，报错packagesite.pkg: Not Found

根据这里 https://forums.freebsd.org/threads/pkg-update-packagesite-pkg-not-found.81771/ 说
> It's the other way around, the *.pkg extension is new. It was added with 1.17.0.

对比官方源 latest 少3个文件  meta.conf meta.pkg packagesite.pkg . 目前官方源的 quarterly 还没有 *.pkg .

https://pkg.freebsd.org/FreeBSD:12:amd64/latest/
```
All/
Latest/
meta.conf
meta.pkg
meta.txz
packagesite.pkg
packagesite.txz
```

https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD%3A12%3Aamd64/latest/
```
All/
Latest/
meta.txz
packagesite.txz
```

**Comment by gaoyifan** [comment]
感谢反馈！

已更新同步脚本，增加下列可选文件：
* meta.conf
* meta.pkg
* packagesite.pkg
