### ISSUE TITLE
mirrors 考虑使用 rsync-huai

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#37]
如题。TUNA 为了解决 rsync 服务端的固有问题 fork 了一份 rsync：

https://github.com/tuna/rsync

据说效果明显。

**Comment by zhsj** [comment]
我们目前已经用了 bcache 来缓存，这个功能和 bcache 有点重。。

但 bcache 这货太不稳定了，不如撤了换这一个。。。

**Comment by gaoyifan** [comment]
我觉得可以考虑在不更换bcache的情况下换rsync-huai，这二者功能并不完全重叠。

**Comment by zhsj** [comment]
@gaoyifan rsync-hui 是把目录树单独抽象出来放在一个加速设备上，目的就是缓存meta信息。bcache理论上就直接在block层次上把meta信息缓存了(虽然感觉效果不好。。。）

**Comment by gaoyifan** [comment]
@zhsj bcache缓存的不仅仅是meta信息，还有热数据。目前mirrors上SSD的流量比磁盘整列的流量都要大。如果放弃bcache，那么磁盘整列的流量至少提高一倍。

**Comment by zhsj** [comment]
@gaoyifan 我的意思就是bcache把rsync-hui要做的事情都干了。。。。

**Comment by gaoyifan** [comment]
rsync-huai的缓存是存储在内存中的吧，速度应该有进一步的提升。

如果换成rsync-huai，meta数据的访问量就会大幅下降，bcache会将这些块逐渐替换出去。其实也不冲突。

**Comment by zhsj** [comment]
@gaoyifan rsync-hui的使用这样的：

对于要缓存的目录树 /root，遍历所有文件，对每个文件，假设为 a/b/c，新创建一个相同相对路径的文件 /cache/a/b/c，这个 /cache/a/b/c 和 /root/a/b/c 除了 size 之外所有meta信息一样，原文件的size信息写进 /cache/a/b/c 中。

所以，确实你可以直接把这些 /cache 下的文件放在一个 ramfs 上。。。不过这样内存就有点浪费，从而使操作系统本身的 cache 不能有效发挥。。。。

**Comment by Alkaid-Benetnash** [comment]
现在mirrors内存吃紧，这个估计得搁置了

**Comment by zhsj** [comment]
@Alkaid-Benetnash 不一定用内存，ssd 也可以。另外 rsync-huai 可以从 http://mirrors.ustc.edu.cn/ustclug/ 下载（现在貌似打开困难。。。），包名是 rsync-huai，可以和原来的 rsync 共存。

**Comment by gaoyifan** [comment]
目前的情况来看，zfs对文件目录的缓存并不好，rsync daemon会花费很多时间在扫描文件上，同时也给zfs带来较大的负担。
可以考虑关闭zfs的L2ARC（即SSD缓存），将SSD用于rsync-huai，以优化rsync的列目录速度。

**Comment by gaoyifan** [comment]
经过充分预热，zfs对rsync列目录速度有较大提升（debian同步基本秒出），不再考虑增加rsync-huai

**Comment by gaoyifan** [comment]
近期负载波动较大，打算重启rsync-huai计划

**Comment by gaoyifan** [comment]
done
感谢 @knight42 的贡献https://github.com/knight42/Yuki/commit/2d2f32321a1fe4ebb705bcafe8d13fa0b223ed00
