### ISSUE TITLE
LUG GitLab 不支持 web terminal

### ISSUE THREAD

**Issue by zhaofeng-shu33** [ustclug/discussions#376]
我在自己实验室 deploy 的 gitlab instance 测试了 web terminal （<https://docs.gitlab.com/ee/ci/interactive_web_terminal/>） 的功能是 work的，但在 xxx 上挂自己的 gitlab runner 就不行。
怀疑原因可能是 ustc lug deploy 的 instance 用了 reverse proxy. 按照 https://docs.gitlab.com/ee/administration/integration/terminal.html#enabling-and-disabling-terminal-support
的说法，需要在服务端启用  web terminals。希望管理员有时间可以帮忙 check 一下。

**Comment by taoky** [comment]
已添加 websocket 相关的两个 header (`Upgrade` 和 `Connection`) 的转发。
