### ISSUE TITLE
Hackage snapshot.json 01-index.tar.gz 文件 length 不匹配

### ISSUE THREAD

**Issue by YungeG** [ustclug/discussions#377]
文件大小不匹配导致执行 stack update 失败

**Comment by skyzh** [comment]
`snapshot.json` 里面似乎没有文件的 length 信息。能否提供详细的报错信息？

**Comment by YungeG** [comment]
$ stack update
Selected mirror https://mirrors.ustc.edu.cn/hackage/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
file returned by server too large: <repo>/01-index.tar.gz (expected exactly 88730495 bytes)

**Comment by YungeG** [comment]
我也不太懂，这个是 snapshot.json，加粗的部分应该是不匹配的字段？
{"signatures":[{"keyid":"2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201","method":"ed25519","sig":"+pXjRBebS0tIgyfSxOCXNUvPR6dfizKZ9n7lMqFNbQBDYHAgqwvC4yp+b/0oEXM81s+YMlhRQYvGlmp19ZqFDw=="}],"signed":{"_type":"Snapshot","expires":"2020-05-02T13:09:44Z","meta":{"<repo>/01-index.tar":{"hashes":{"md5":"7acedc312244799e28fd1bcff25a4bde","sha256":"20a316375ab8a2a7135a561cfcf92001de3acc4df54b4f352b49b4ffa19c9a80"},"length":664143872},"<repo>**/01-index.tar.gz":{"hashes":{"md5":"00fde7e29b5311ed3e4eb72e94018d3f","sha256":"dc3d25136da3de32b2b8ce4c5dcc10f3c997c3276559f071d387c19f948327c2"},"length":88730495}**,"<repo>/mirrors.json":{"hashes":{"md5":"e5960ab00f691b004bc71df3a7f9afdd","sha256":"2134e02188ba9168830d6c1c1912d1ad91f373f6ee2411bde33f8c6794dcbb57"},"length":407},"<repo>/root.json":{"hashes":{"md5":"9395ec78baaea3bd2faa225accb55b26","sha256":"0db265fdc8ed4cfba119f6daaa913b48986a0bf7e8239ad7874611c1b0cd2ddb"},"length":4077}},"version":60842}}

**Comment by skyzh** [comment]
看起来确实不匹配（

**Comment by taoky** [comment]
在 https://github.com/ustclug/ustcmirror-images/commit/5414bbe651d23a49195129d7ab561e1c41d8f94d 中修复。本地测试 `stack update` 正常了。
