### ISSUE TITLE
about the mirrors synchronize

### ISSUE THREAD

**Issue by dongzhe1208** [ustclug/discussions#378]
Good morning!Our company is a IDC Service provider in Beijing.We want to synchronize some mirrors with high user frequency to my station. Can you provide a list of the top ten mirrors in the higher frequency of your station?

**Comment by WhenMelancholy** [comment]
Hello! We have analyzed the logs for the last seven days, here is the result (sorted by the indicators listed in the first row from largest to smallest):

| number of visits |  number of ips   | amount of accessed data |
| :--------------: | :--------------: | :---------------------: |
|      ubuntu      |      centos      |         ubuntu          |
|      centos      |       epel       |           gnu           |
|   ubuntu-ports   |      ubuntu      |         centos          |
|      debian      |       gnu        |        qtproject        |
|       kali       |     armbian      |       kernel.org        |
|       epel       |      debian      |    homebrew-core.git    |
|     armbian      |    docker-ce     |          kali           |
|       CTAN       |     manjaro      |          CTAN           |
|    archlinux     | homebrew-bottles |        archlinux        |
|     opensuse     |       xbmc       |          epel           |

I hope this will help.
