### ISSUE TITLE
申请创建 opensuse 下未同步的的跳转链接

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [ustclug/discussions#379]
经过实测，上交大的
opensuse/ports
-----
![证明](https://i.bmp.ovh/imgs/2021/11/4bf07f0049cce63a.png)
-----
正常工作，请求创建以上链接到上交大镜像，并且修改 opensuse 的 mirror help 页面，补全镜像。

**Comment by skyzh** [comment]
Hi, SJTUG 的这几个目录都是空的，实际上没有同步。

**Comment by Mr-Ao-Dragon** [comment]
> Hi, SJTUG 的这几个目录都是空的，实际上没有同步。
sorry ，我眼花了，已修改请求，请看看
