### ISSUE TITLE
安装PHP@7.2时会自动安装python@3.9的版本

### ISSUE THREAD

**Issue by hide-in-code** [ustclug/discussions#380]
USTC的老师你好，我在使用brew安装php7.2的时候，brew会提示并安装python3.9，据我所知php本身并不依赖python的任何东西，且我本地已经安装了python3.7.3的版本，本次的使用安装会导致我原先的环境受到影响而无法正常工作(python3.9比较新，很多其他开源依赖包未支持3.9版本，其次之前工作中的所编写的代码都是基于python3.7，项目迁移会有影响)，暂不清楚这是bug还是有意为之，但对使用的人始终不太友好，希望能提供一种相对便捷合理解决方案。
![image](https://user-images.githubusercontent.com/19517597/142978410-fd3eb000-4aa6-4c6d-8958-a97dcd72ab69.png)

**Comment by skyzh** [comment]
这是 brew 的问题吧，你用官方上游试试？

**Comment by hide-in-code** [comment]
@skyzh 咱们这边是只负责镜像，不负责解决brew的问题吗？

**Comment by skyzh** [comment]
超出了镜像站可以解决的问题范围.jpg

**Comment by taoky** [comment]
1. 相关软件包的依赖问题请咨询 brew 上游，镜像站「依原样提供」软件包，不会进行额外的修改。
2. `python@3.9` 不会覆盖 `python@3.7`。
3. 我个人推荐使用 `pyenv` 解决 Python 版本相关问题。

**Comment by hide-in-code** [comment]
本来是要提到brew官方的，然后看了官方issue提交说明说有问题可以来这里问，才来这里提的。
@taoky pyenv或者Anaconda 都可以解决，我其实是比较好奇为啥装php会依赖python这件事情，这两个软件之间应该是没有依赖关系的，不知道这个算不算brew的bug

**Comment by hide-in-code** [comment]
USTC和TUNA 都只会相互推诿，CN开源氛围也就是这样而已

**Comment by skyzh** [comment]
> USTC和TUNA 都只会相互推诿，CN开源氛围也就是这样而已

事实是你没有找对提问的地方，镜像站不参与 brew 本身的维护。

**Comment by taoky** [comment]
@hide-in-code `brew deps --tree php@7.2` 可以解答你的迷惑。

**Comment by taoky** [comment]
> USTC和TUNA 都只会相互推诿，CN开源氛围也就是这样而已

我用国内版 Bing 搜索「brew get all dependencies」，第一条就是 <https://stackoverflow.com/questions/41029842/easy-way-to-have-homebrew-list-all-package-dependencies>。

我的**个人**观点（不代表 USTCLUG/TUNA）是：在您发出如此言论之前，请先学会使用搜索引擎，对于程序员来说这是非常重要的技能。

**Comment by hide-in-code** [comment]
sry, 我话说的有点过了，情绪没控制住，抱歉

**Comment by hide-in-code** [comment]
加油

**Comment by billchenchina** [comment]
https://stackoverflow.com/questions/65583607/why-brew-needs-python-while-installing-php7

**Comment by hide-in-code** [comment]
【填坑】昨天回家后用docker做了实验(从源码编译安装php和使用linux homebrew安装php)，使用brew安装php就会附带安装python，源码编译安装则不会，在discussions上发了问题，他们也没有正面回答问题，也有建议我使用python的版本管理工具，估计是没办法解决，帖子链接[#discussion-3700600](https://github.com/Homebrew/discussions/discussions/2514#discussion-3700600)，不知道后面会不会有更新

**Comment by hide-in-code** [comment]
【填坑】从官方discussions问到了我认为合理的解释：
[#2514 (reply in thread)](https://github.com/Homebrew/discussions/discussions/2514#discussioncomment-1692308)
https://justinmayer.com/posts/homebrew-python-is-not-for-you/
homebrew python 并不适合开发
@taoky @billchenchina 感谢两位大佬的帮助

**Comment by hide-in-code** [comment]
官方已经移除了php7.2对于python3.9的依赖
https://github.com/Homebrew/discussions/discussions/2514#discussioncomment-1693794

**Comment by hide-in-code** [comment]
对于前两天说错话，在这里给USTCLUG和TUNA再次道歉，事情本身不大，也是一时间没控制住情绪，现在联系官方做了处理，也算是完美解决了，CN开源加油
