### ISSUE TITLE
elpa 镜像变更

### ISSUE THREAD

**Issue by ksqsf** [ustclug/discussions#381]
for the record,

1. https://github.com/tuna/issues/issues/1373
2. https://emacs-china.org/t/elpa/19155/11

由于 emacs-china 上游停止了 rsync 服务，至今 lug 和 tuna 镜像停留在 10 月 19 号。

**Comment by taoky** [comment]
之前因为知晓 emacs-china 的带宽不够，所以同步是直接从 tuna/bfsu 拉下来的。如果直接从上游用 rsync 同步会需要设置多个同步项，有一些麻烦。

如果可以提供 emacs-china 同步连接的所有上游和目录的对应关系的话应该可以更新，现在在不知道参数的情况下直接改可能会出问题，所以保险起见保持不动。

**Comment by ksqsf** [comment]
working rn no changes needed
