### ISSUE TITLE
Manjaro Linux cd镜像不同步？

### ISSUE THREAD

**Issue by humanfans** [ustclug/discussions#383]
貌似最近国内都不同步manjarolinux 镜像了

**Comment by taoky** [comment]
Related:

- https://github.com/tuna/issues/issues/1178
- https://github.com/BITNP/issues/issues/32

同样，目前不会考虑同步 Manjaro CD 的每日构建。如果有能够同步稳定版本的渠道会进行切换。

**Comment by zhullyb** [comment]
https://github.com/hitlug/issues/issues/39

**Comment by taoky** [comment]
由于没有能够同步 manjaro-cd 的方式，该镜像已移除。
