### ISSUE TITLE
docker-ce仓库的repodata没同步过来

### ISSUE THREAD

**Issue by lightnear** [ustclug/discussions#385]
## docker-ce仓库的repodata没同步过来

路径：https://mirrors.ustc.edu.cn/docker-ce/linux/centos/8/x86_64/stable/repodata/

如下为报错内容：

```shell
$ dnf makecache
CentOS Stream 8 - AppStream                                                                                    27 MB/s |  20 MB     00:00
CentOS Stream 8 - BaseOS                                                                                       31 MB/s |  19 MB     00:00
CentOS Stream 8 - Extras                                                                                       81 kB/s |  18 kB     00:00
Docker CE Stable - x86_64                                                                                     863  B/s | 150  B     00:00
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://mirrors.ustc.edu.cn/docker-ce/linux/centos/8/x86_64/stable/repodata/repomd.xml (IP: 202.141.160.110)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

- 浏览器查看 ustc 源 repodata 中确实没有文件
https://mirrors.ustc.edu.cn/docker-ce/linux/centos/8/x86_64/stable/repodata/
<img width="838" alt="image" src="https://user-images.githubusercontent.com/1888302/156735117-4743636d-bec9-474b-a753-1bb1a156c617.png">

- 查看其它源（TUNA），此目录下是有文件的
https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/8/x86_64/stable/repodata/
<img width="938" alt="image" src="https://user-images.githubusercontent.com/1888302/156735369-85a1450e-b11a-4ff3-ae53-08655cb21c84.png">

**Comment by taoky** [comment]
更新了同步脚本 <https://github.com/ustclug/ustcmirror-images/commit/881468c67656fbf5a95c4cd5beadb6f2f127dcfe> 并且重新进行了一次同步，应该可以了，如果之后还出现类似情况会继续调试。
