### ISSUE TITLE
proxmox源 文件缺失

### ISSUE THREAD

**Issue by zctmdc** [ustclug/discussions#387]
今天安装proxmox的时候，提示几个文件找不到，麻烦同步一下。

![image](https://user-images.githubusercontent.com/24244480/158050184-6819ff39-1bf4-4637-ba2c-4c86af6a2948.png)

![image](https://user-images.githubusercontent.com/24244480/158050193-e9a21b8a-43ae-44af-b583-c290770c8704.png)

```
After this operation, 2,311 MB of additional disk space will be used.
Err:1 https://mirrors.ustc.edu.cn/proxmox/debian/pve bullseye/pve-no-subscription amd64 swtpm amd64 0.7.1~bpo11+1
  404  Not Found [IP: 2001:da8:d800:95::110 443]
Err:2 https://mirrors.ustc.edu.cn/proxmox/debian/pve bullseye/pve-no-subscription amd64 vncterm amd64 1.7-1
  404  Not Found [IP: 2001:da8:d800:95::110 443]
Err:3 https://mirrors.ustc.edu.cn/proxmox/debian/pve bullseye/pve-no-subscription amd64 zfs-zed amd64 2.1.2-pve1
  404  Not Found [IP: 2001:da8:d800:95::110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/proxmox/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/swtpm_0.7.1%7ebpo11%2b1_amd64.deb  404  Not Found [IP: 2001:da8:d800:95::110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/proxmox/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/vncterm_1.7-1_amd64.deb  404  Not Found [IP: 2001:da8:d800:95::110 443]
E: Failed to fetch https://mirrors.ustc.edu.cn/proxmox/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/zfs-zed_2.1.2-pve1_amd64.deb  404  Not Found [IP: 2001:da8:d800:95::110 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by zctmdc** [comment]
昨晚上是好的，应该是今天早上同步的问题

**Comment by taoky** [comment]
这个问题发现每过几个月就有反馈，而且都是再同步一下就好了。之前怀疑可能是 CDN 的问题，但是固定 hosts 之后还是会出现。我对同步管理器做了一些修改 (<https://github.com/ustclug/Yuki/commit/6e70ec505134aeb9576179d58e58d54fd30623f7>)，在定时同步 proxmox 的时候加上更详细的日志，以期在下次出问题的时候能够了解到更详细的情况。

**Comment by taoky** [comment]
https://github.com/ustclug/discussions/issues/423#issuecomment-1560454342

刚刚检查日志发现这个问题又出现了，得让 `rclone sync` 遇到 503 的时候别把本地文件删了……

**Comment by taoky** [comment]
https://github.com/rclone/rclone/issues/5390, and also https://github.com/rclone/rclone/issues/6582

**Comment by taoky** [comment]
和 @iBug 讨论后向 proxmox 官方发送了咨询是否能开启 rsync 同步的邮件，得到了否定的回复。

Proxmox 官方推荐使用 [Proxmox Offline Mirror](https://pom.proxmox.com/) 进行同步，但是该程序**不会同步 LXC 镜像等内容**，并且同步得到的目录树也不符合使用需求，因此不会考虑。

**Comment by taoky** [comment]
[更换为了自制的同步工具](https://github.com/ustclug/ustcmirror-images/pull/99)，同步速度应该快得多了（扫一遍文件从近 10 个小时变成只要几分钟），并且即使遇到 503 也不会再删文件了。但是同步的时候发现 proxmox CDN 的 nginx 列出的目录树似乎是过时的，其中的一部分文件可能已经不存在了，会出现类似这样的情况：

```
2023-07-23T15:13:00.725987Z ERROR ThreadId(84) tsumugu: Failed to GET http://download.proxmox.com/debian/devel/dists/bookworm/main/binary-amd64/librust-proxmox-sys%2Bsortable-macro-dev_0.4.2-1.changelog: HTTP status client error (404 Not Found) for url (http://download.proxmox.com/debian/devel/dists/bookworm/main/binary-amd64/librust-proxmox-sys%2Bsortable-macro-dev_0.4.2-1.changelog)
2023-07-23T15:13:02.724620Z ERROR ThreadId(84) tsumugu: Failed to GET http://download.proxmox.com/debian/devel/dists/bullseye/main/binary-amd64/librust-futures-task%2Bonce-cell-dev_0.3.8-1%2Bpve1.changelog: HTTP status client error (404 Not Found) for url (http://download.proxmox.com/debian/devel/dists/bullseye/main/binary-amd64/librust-futures-task%2Bonce-cell-dev_0.3.8-1%2Bpve1.changelog)
```

有可能还要考虑对 APT/YUM 的 metadata 做特殊判断处理，如果之后发现有必要的话可以作为后续的工作。

**Comment by gaoyifan** [comment]
可以试试设置请求头 `Cache-Control: no-cache`，能强制一些 CDN 回源验证缓存有效性（但不是所有 CDN 都遵守

**Comment by iBug** [comment]
> 但不是所有 CDN 都遵守

我判断这个“CDN”是 Proxmox 用一堆 vps 自建的，用的是 nginx，估计不会遵守客户端发上来的 header

**Comment by taoky** [comment]
我发现目前 CDN listing 里面所有存在但是缺失的文件都是非必须的 changelog，可以在同步的时候 exclude 掉。
