### ISSUE TITLE
qt新的目录同步

### ISSUE THREAD

**Issue by CharlesLiaoO** [ustclug/discussions#391]
qt官方下载站已经将部分版本的目录从archive移动到new_archive目录，但镜像站并没有new_archive，qt官方下载站速度慢甚至速度为0。请问是否可以同步new_archive目录，便于国内下载

**Comment by taoky** [comment]
参考 <https://github.com/tuna/issues/issues/757#issuecomment-604243686>，已经停止支持的版本不会被 rsync 同步。
