### ISSUE TITLE
ip被禁

### ISSUE THREAD

**Issue by cuijianzhe** [ustclug/discussions#392]
你好，我们的出口ip访问清华源地址https://pypi.mirrors.ustc.edu.cn/simple 不被允许，请问是把我们的IP封禁了吗？如何申诉，附ip：117.161.12.146。

**Comment by taoky** [comment]
1. 我们是**中科大**开源镜像站，不是清华源。目前 pypi 镜像重定向至由北京外国语大学开源镜像站提供的 pypi: https://mirrors.bfsu.edu.cn/pypi
2. 经检查，117.161.12.146 不在我们的黑名单中。

目前的信息不足以判断产生问题的原因。如果需要我们帮助判断连接问题，请提供以下信息：

1. 你是否能够访问 <https://mirrors.ustc.edu.cn> 与 <https://mirrors.bfsu.edu.cn>？如果不能，提示的错误信息是什么？
2. 你的网络环境是否有特殊配置（如代理）？
3. 使用 traceroute 或 mtr 检查连接上述两个域名每一跳的信息，并且展示命令的输出。

你也可以尝试将 pypi 配置替换为由 bfsu 提供的镜像，并且检查是否能够正常访问，如果仍然不能，可以考虑回到 <https://github.com/tuna/issues/issues/> 向 TUNA 咨询。

**Comment by cuijianzhe** [comment]
您好，感谢回复，现象是到清华源和中科大的源都不能正常请求，直接访问超时。我们的出口ip有多个，换一个其他的比如117.161.12.148就可以了，但是这个117.161.12.146就不行。
![image](https://user-images.githubusercontent.com/48144475/173972762-0302ca49-ad27-475d-b192-a8a02fd405f8.png)

**Comment by taoky** [comment]
你所给出的信息只说明你的 IP 到 BFSU 的网络连接存在问题。如果你能正常访问[科大镜像站的主页](https://mirrors.ustc.edu.cn)，那么你到我们的连接是没有问题的。前面提到，**目前 pypi 镜像重定向至由北京外国语大学（BFSU）开源镜像站提供的**服务，因此如果你无法正常连接到 BFSU，那么即使你设置了 <https://pypi.mirrors.ustc.edu.cn/simple>，也无法使用 pypi 镜像。

由于我们目前不提供 pypi 镜像，你可以参考 <https://mirrorz.org/list/pypi> 选择合适的镜像。

**Comment by taoky** [comment]
从目前的信息来看，@cuijianzhe 到科大镜像站的网络连接没有问题，并且也已提供了 pypi 镜像的替代方案，故此 issue 关闭。
