### ISSUE TITLE
turnkeylinux源每次执行pveam update后失效

### ISSUE THREAD

**Issue by ZKeeer** [ustclug/discussions#393]
https://mirrors.ustc.edu.cn/turnkeylinux/metadata/pve/aplinfo.dat
此文件中镜像的location仍然为master镜像源，即便是修改为中科大源之后，仍然指向的master源
例如

> Package: turnkey-ansible
Version: 16.1-1
Type: lxc
OS: debian-10
Section: turnkeylinux
Architecture: amd64
Location: http://mirror.turnkeylinux.org/turnkeylinux/images/proxmox/debian-10-turnkey-ansible_16.1-1_amd64.tar.gz
Infopage: http://www.turnkeylinux.org/ansible
ManageUrl: http://__IPADDRESS__/
sha512sum: e2e1303ce0dcbe707202318c85404c5471c647827a5e3ea4ce430f3188ccdaafcabd22338d4e82d096bb6a8dc7ab6f19dffdfc07cd894ce22f756adfd58368b0
Description: TurnKey Ansible
 TurnKey Ansible - Radically simple IT automation platform

手动替换/var/lib/pve-manager/apl-info文件夹下内容后可以生效，但是pve每天会定时执行pveam update，更新完后仍然是master源

希望能在同步完turnkeylinux后，更新相关文件的配置

**Comment by taoky** [comment]
Duplicate of https://github.com/ustclug/discussions/issues/327

**Comment by taoky** [comment]
从之前的分析来看，`aplinfo.dat` 有签名检验，因此只能做本地修改。可以尝试本地 edit pve-daily-update.service 用 `sed` 做路径修改。
