### ISSUE TITLE
AOSP镜像限制个人用户访问！！！！

### ISSUE THREAD

**Issue by jgb002002** [ustclug/discussions#397]
AOSP 镜像可以少点限制个人用户同步吗？AOSP速度快的国内镜像站本来就少，加上Google官方的镜像国内无法访问，个人想同步AOSP源码非常困难，你们站的速度很快但是同步4-5G左右的数据后IP就会被封锁，需要重连宽带换得新IP后才能继续

**Comment by taoky** [comment]
> 你们站的速度很快但是同步4-5G左右的数据后IP就会被封锁，需要重连宽带换得新IP后才能继续

我们没有配置过这样的限制。

**Comment by taoky** [comment]
另请提供 IP，以便我们分析日志进行故障排查。

**Comment by jgb002002** [comment]
> 另请提供 IP，以便我们分析日志进行故障排查。

39.171.207.42

**Comment by taoky** [comment]
@jgb002002 请问你的 AOSP 仓库中 `.repo/manifests.git/config` 的配置是怎样的？

**Comment by jgb002002** [comment]
> @jgb002002 请问你的 AOSP 仓库中 `.repo/manifests.git/config` 的配置是怎样的？
[core]
	repositoryformatversion = 0
	filemode = false
[filter "lfs"]
	smudge = git-lfs smudge --skip -- %f
	process = git-lfs filter-process --skip
[remote "origin"]
	url = https://github.com/jgb002002/platform_manifest_twrp_aosp.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[manifest]
	platform = auto
[branch "default"]
	remote = origin
	merge = refs/heads/twrp-11
最后把default.xml   
 <remote name="aosp"
            fetch="git://mirrors.ustc.edu.cn/aosp"   #改成Git:// 正常了 http://（封IP）和rsync://rsync（Git不支持）
            review="https://android-review.googlesource.com/"/>
    <default revision="refs/tags/android-11.0.0_r29"
             remote="aosp"
             sync-j="4"/>

**Comment by taoky** [comment]
检查日志后发现为 AOSP 中文件数过多，会在初次同步时触发请求数限制器。目前修改如下：

1. https://mirrors.ustc.edu.cn/help/aosp.html 帮助中明确推荐使用 aosp-monthly 压缩包进行初次同步；
2. 请求数限制器暂时忽略 AOSP 相关请求。

**Comment by jgb002002** [comment]
> 



> 检查日志后发现为 AOSP 中文件数过多，会在初次同步时触发请求数限制器。目前修改如下：
> 
>     1. https://mirrors.ustc.edu.cn/help/aosp.html 帮助中明确推荐使用 aosp-monthly 压缩包进行初次同步；
> 
>     2. 请求数限制器暂时忽略 AOSP 相关请求。

谢谢同步好了，我只要部分组件就好了，不用全部AOSP源码，全部源码100G，我只要大概26G就可以了，但是https://mirrors.ustc.edu.cn/aosp封IP的问题是确实存在的!!
