### ISSUE TITLE
Request to add mirror for VNote

### ISSUE THREAD

**Issue by tamlok** [ustclug/discussions#399]
Hi,

I am the author of [VNote](https://github.com/vnotex/vnote), an active open source notebook taking application. Could you please help to add VNote binaries to the mirror, so users from mainland could download it conveniently? Now I use Baidu NetDisk and Tianyi NetDisk for this, both not being the best solutions.

VNote will honor and appreciate the help!

Thanks!

**Comment by taoky** [comment]
Please refer to https://github.com/ustclug/mirrorrequest for mirror request.
