### ISSUE TITLE
Arm64 iso下载支持

### ISSUE THREAD

**Issue by jiangcuo** [ustclug/discussions#402]
在https://mirrors.ustc.edu.cn/ **获取发行版映像** 栏目中。ubuntu\debian\ 均是amd64，没有指向ARM64的链接.
恳请支持，方便下载。
现在是手动替换镜像站下载。
https://iso.mirrors.ustc.edu.cn/debian-cd/

**Comment by taoky** [comment]
https://git.lug.ustc.edu.cn/mirrors/mirrors-index/-/merge_requests/12

**Comment by taoky** [comment]
列表中添加了 Ubuntu 和 Debian 的 arm64 iso。
