### ISSUE TITLE
lug.ustc.edu.cn/blog迁移至USTC blog

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#41]
目前[LUG新闻站](https://lug.ustc.edu.cn/blog)与wiki放在同一个域名下。

我想将WordPress与dokuwiki分离开，以降低系统耦合度。dokuwiki使用docker管理，WordPress则迁移至USTCblog。

同时启用新域名news.ustclug.org，lug.ustc.edu.cn/blog则301跳转到news.ustclug.org。

大家觉得如何？

**Comment by gaoyifan** [comment]
新注册的https://lugnews.blog.ustc.edu.cn主页空白，原因未知。

P.S. 后台可登陆

**Comment by zhsj** [comment]
和 server.u.o 一样再开个 container 呗（

**Comment by gaoyifan** [comment]
已迁移：
dokuwiki -> docker2 (container: lugwiki)
wordpress -> USTC Blog (lugnews.blog.ustc.edu.cn)

添加了301  lug.ustc.edu.cn/blog  -> news.ustclug.org

**Comment by zhsj** [comment]
顺手开了下lugwiki，首页样式全乱了。

```
https://lug.ustc.edu.cn/wiki/lib/exe/js.php?t=bootstrap3&tseed=331cede6cbd469687a8e5e2ed6710302 Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
https://lug.ustc.edu.cn/wiki/lib/exe/css.php?t=bootstrap3&tseed=331cede6cbd469687a8e5e2ed6710302 Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery(…)
lug.ustc.edu.cn/:39 Uncaught ReferenceError: jQuery is not defined(…)
```

**Comment by gaoyifan** [comment]
你用的什么浏览器？ 为什么会出现ERR_SPDY_PROTOCOL_ERROR....

Safari用户表示一切正常....

**Comment by zhsj** [comment]
@gaoyifan Chrome 54。nginx配置出问题了吧

**Comment by gaoyifan** [comment]
@zhsj   nginx配置是照抄的：https://github.com/ustclug/lugwiki/blob/master/rootfs/etc/nginx/default.d/lug.ustc.edu.cn
