### ISSUE TITLE
mysql-repo源未更新同步完整

### ISSUE THREAD

**Issue by DevHaoZi** [ustclug/discussions#410]
镜像站：[http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-connectors-community/el/](http://mirrors.ustc.edu.cn/mysql-repo/yum/mysql-connectors-community/el/)
上游：[http://repo.mysql.com/yum/mysql-connectors-community/el/](http://repo.mysql.com/yum/mysql-connectors-community/el/)

对比可以发现9版本不存在，导致在CentOS Stream 9等9系系统安装mysql失败。

**Comment by taoky** [comment]
还是 mysql CDN 的问题。头疼……镜像站上的 repo.mysql.com hosts 我刚刚从 23.36.253.13 改成了 23.219.68.218，现在正在重新同步，跑完应该暂时就行了。

之前在 #282 里提到要把同步拆出来，但是之后忘了这件事情，我还是最近找时间看看能不能把 mysql-repo 的 apt & yum 同步拆出来吧。

Duplicate with #282.
