### ISSUE TITLE
lfs 10.0的lfs-bootscripts-20200818.tar.xz 校验错误

### ISSUE THREAD

**Issue by apzc2529** [ustclug/discussions#411]
地址 https://mirrors.ustc.edu.cn/lfs/lfs-packages/10.0/lfs-bootscripts-20200818.tar.xz
下载后校验md5的结果为：
d689e8d2b5ca258f95099b74c53ddee1  lfs-bootscripts-20200818.tar.xz
LFS官方页码给出的校验码如下（https://www.linuxfromscratch.org/lfs/downloads/10.0/LFS-BOOK-10.0-NOCHUNKS.html）
ef4abcaeddc1496f7a94b72af99e243a  lfs-bootscripts-20200818.tar.xz

麻烦校对一下，谢谢！
祝新年快乐！

**Comment by taoky** [comment]
我们的上游 osuosl 对应的文件的 MD5 值亦为 d689e8d2b5ca258f95099b74c53ddee1:

```
$ sudo -u mirror rsync rsync://ftp.osuosl.org/lfs/lfs-packages/10.0/lfs-bootscripts-20200818.tar.xz /tmp/

---------------------------------------------------------------------------
                      R S Y N C . O S U O S L . O R G
                          Oregon State University
                              Open Source Lab

       Unauthorized use is prohibited - violators will be prosecuted
---------------------------------------------------------------------------

                For more information about the OSL visit:
                    http://osuosl.org/services/hosting

          This host is the home to the primary archives of several
           projects.  We would prefer that only primary/secondary
                    mirrors use this service.  Thanks!

---------------------------------------------------------------------------


$ md5sum /tmp/lfs-bootscripts-20200818.tar.xz 
d689e8d2b5ca258f95099b74c53ddee1  /tmp/lfs-bootscripts-20200818.tar.xz
```

我本地测试了一下，两个文件解压得到的包内容应该是一样的：

```
> diff -r lfs-bootscripts-20200818 lfs-bootscripts-20200818-1/
>
```

等有空的时候会尝试向上游反馈。

**Comment by apzc2529** [comment]
> 我们的上游 osuosl 对应的文件的 MD5 值亦为 d689e8d2b5ca258f95099b74c53ddee1:
> 
> ```
> $ sudo -u mirror rsync rsync://ftp.osuosl.org/lfs/lfs-packages/10.0/lfs-bootscripts-20200818.tar.xz /tmp/
> 
> ---------------------------------------------------------------------------
>                       R S Y N C . O S U O S L . O R G
>                           Oregon State University
>                               Open Source Lab
> 
>        Unauthorized use is prohibited - violators will be prosecuted
> ---------------------------------------------------------------------------
> 
>                 For more information about the OSL visit:
>                     http://osuosl.org/services/hosting
> 
>           This host is the home to the primary archives of several
>            projects.  We would prefer that only primary/secondary
>                     mirrors use this service.  Thanks!
> 
> ---------------------------------------------------------------------------
> 
> 
> $ md5sum /tmp/lfs-bootscripts-20200818.tar.xz 
> d689e8d2b5ca258f95099b74c53ddee1  /tmp/lfs-bootscripts-20200818.tar.xz
> ```
> 
> 我本地测试了一下，两个文件解压得到的包内容应该是一样的：
> 
> ```
> > diff -r lfs-bootscripts-20200818 lfs-bootscripts-20200818-1/
> >
> ```
> 
> 等有空的时候会尝试向上游反馈。

辛苦了！我是用ALFS自动编译提示校验码错误，然后发现咱们镜像下载的该文件与lfs官网给出的校验码不一致的。

感谢回复！祝新年快乐！

**Comment by taoky** [comment]
上游已修复该问题。
