### ISSUE TITLE
AOSP tar包checksum不一致

### ISSUE THREAD

**Issue by Yuna95** [ustclug/discussions#416]
一、问题：
使用curl命令下载的AOSP tar包，本地计算出来的md5和网站上提供的aosp-latest.tar.md5文件中的值不一致。

二、操作步骤：
2.1. 使用如下命令下载AOSP  tar包和md5 checksum文件：
     curl -OC - https://mirrors.ustc.edu.cn/aosp-monthly/aosp-latest.tar
     curl -OC - https://mirrors.ustc.edu.cn/aosp-monthly/aosp-latest.tar.md5

2.2. 下载完成之后，在本地使用如下命令计算AOSP tar包的md5：
     md5sum aosp-latest.tar

2.3. 结果
     第2步中计算出来的md5值和aosp-latest.tar.md5文件中提供的md5值不一致。

三、备注：
3.1. aosp-latest.tar文件下载过多次，都是这个现象；
3.2. 执行repo sync 2>&1 | tee sync_remote.log命令的log如附件[sync_remote.log](https://github.com/ustclug/discussions/files/10890846/sync_remote.log)所示；
3.3. 执行repo sync -l 2>&1 | tee sync_local.log命令的log如附件[sync_local.log](https://github.com/ustclug/discussions/files/10890853/sync_local.log)所示；

**Comment by taoky** [comment]
在服务器上 md5sum 得到的结果是一致的：

```
taoky@mirrors4:/srv/repo/aosp-monthly$ cat aosp-latest.tar.md5 
236e9e55ab13bc9ce40c625098962972  aosp-20230301.tar
taoky@mirrors4:/srv/repo/aosp-monthly$ md5sum aosp-latest.tar
236e9e55ab13bc9ce40c625098962972  aosp-latest.tar
```

**Comment by Yuna95** [comment]
那请问下：除了curl，和浏览器下载，还有什么其它下载方案吗？

**Comment by taoky** [comment]
可以试一下去掉 `-C -` 下载，以及下载完成后确认一下文件字节数是否和 https://mirrors.ustc.edu.cn/aosp-monthly/ 显示的一致。

**Comment by Yuna95** [comment]
好的，我试下，谢谢。
之前确认过，字节数和网站上显示的不一样。

**Comment by Yuna95** [comment]
试了一下，用curl -O https://mirrors.ustc.edu.cn/aosp-monthly/aosp-latest.tar下载，字节数可以对上，但是md5sum值依然对不上。我这边下载的文件的md5值：d7080c6ba104cab85cfa0209226ed212  aosp-latest.tar。

之前下载的aosp-latest.tar字节数也对得上，但是md5值不一样：05cfcc702a3d203e2cc1b871e7752b76  aosp-latest.tar.bak

**Comment by taoky** [comment]
我使用 `curl -O` 在校外本地下载也无法复现这个问题，因此目前看起来问题不在镜像站一端。可以考虑从其他镜像站下载 aosp-monthly: https://mirrorz.org/list/aosp-monthly

如果从其他镜像站下载得到的文件也有 MD5 不一致的问题，那么有大概率是你的机器的硬件故障。另外如果是在部分公司等的场合，使用了自签名的 TLS 证书截获 HTTPS 通信，那么中间设备也有可能导致下载得到的文件出现问题。

**Comment by Yuna95** [comment]
下面这个地址我可以直接用吗？我安装的是桌面版的Ubuntu。
rsync://mirrors.bfsu.edu.cn/aosp-monthly/

**Comment by taoky** [comment]
> 下面这个地址我可以直接用吗？我安装的是桌面版的Ubuntu。 rsync://mirrors.bfsu.edu.cn/aosp-monthly/

rsync 协议需要安装使用 rsync 从远程获取文件。

**Comment by Yuna95** [comment]
Ubuntu默认有rsync，只是不知道怎么用，网上查到的示例不是下载这种连接的：rsync://mirrors.bfsu.edu.cn/aosp-monthly/

我的电脑上rsync的版本：
xxx:~$ rsync --version
rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

**Comment by taoky** [comment]
> Ubuntu默认有rsync，只是不知道怎么用，网上查到的示例不是下载这种连接的：rsync://mirrors.bfsu.edu.cn/aosp-monthly/，而且看网上的示例，这个命令貌似需要账号密码。
> 
> 我的电脑上rsync的版本： xxx:~$ rsync --version rsync version 3.1.2 protocol version 31 Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others. Web site: http://rsync.samba.org/ Capabilities: 64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints, socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace, append, ACLs, xattrs, iconv, symtimes, prealloc
> 
> rsync comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions. See the GNU General Public Licence for details.

`rsync` 后直接跟 URL 可以显示对应文件或者文件夹的信息：

```
> rsync rsync://mirrors.bfsu.edu.cn/aosp-monthly/                                                                
+==================================================+
|               Tsinghua University                |
|          -= Open Source Mirror Site =-           |
+--------------------------------------------------+
|   Welcome to Tsinghua Open Source Mirror Site.   |
|                                                  |
|   This mirror is also available on HTTP.         |
|   HTTP  [https://mirrors.tuna.tsinghua.edu.cn]   |
|   RSYNC [rsync://mirrors.tuna.tsinghua.edu.cn]   |
|                                                  |
|   If you have any issues, please contact us      |
|   via GitHub @ https://github.com/tuna/issues    |
|   or IRC at #tuna on freenode                    |
|   or Fishroom at https://fishroom.tuna.moe/      |
|                                                  |
|   Supported by                                   |
|      Tsinghua Information Technology Center      |
|   Maintained by                                  |
|      Tsinghua University TUNA Association        |
|   Service Provided by                            |
|      neomirrors                                  |
|   This storage server is sponsored by            |
|      Huawei Inc.                                 |
|                                                  |
|   TUNA acknowledges the contribution from        |
|   Huawei and Megvii to open source software and  |
|   communities.                                   |
|                                                  |
+==================================================+

drwxr-xr-x             10 2023/03/01 00:46:41 .
-rw-r--r-- 74,921,072,640 2023/01/01 00:46:28 aosp-20230101.tar
-rw-r--r--             52 2023/01/01 00:53:32 aosp-20230101.tar.md5
-rw-r--r-- 64,426,127,360 2023/02/03 21:44:51 aosp-20230203.tar
-rw-r--r--             52 2023/02/03 21:48:49 aosp-20230203.tar.md5
-rw-r--r-- 65,439,375,360 2023/03/01 00:42:34 aosp-20230301.tar
-rw-r--r--             52 2023/03/01 00:46:41 aosp-20230301.tar.md5
lrwxrwxrwx             17 2023/03/01 00:46:41 aosp-latest.tar
lrwxrwxrwx             21 2023/03/01 00:46:41 aosp-latest.tar.md5
```

添加其他的参数可以使用下载文件或文件夹，例如：

```
> rsync -avP rsync://mirrors.bfsu.edu.cn/ubuntu/ls-lR.gz .
```

**Comment by Yuna95** [comment]
1. 测试了下，下载的镜像包的md5还是和网站上的不一致。
2. 现在发现，Windows10上下载的md5是一致的，Ubuntu 20.04.5 LTS上下载的md5不一致。
3. 把在Windows10上下载的tar包（文件系统是NTFS）使用cp命令复制到Ubuntu的盘（ext4文件系统）上，后者的md5也变了。
4. 电脑是Windows10和Ubuntu 20.04.5 LTS双系统的，双固态硬盘、两个系统分别在两个硬盘上，但是Ubuntu的/boot和/boot/efi是在Windows10的系统盘上。

试了很多方法，还是没有解决问题，目前没有解决思路了。请问一下有什么办法没？

**Comment by taoky** [comment]
> 1. 测试了下，下载的镜像包的md5还是和网站上的不一致。
> 
>     2. 现在发现，Windows10上下载的md5是一致的，Ubuntu 20.04.5 LTS上下载的md5不一致。
> 
>     3. 把在Windows10上下载的tar包（文件系统是NTFS）使用cp命令复制到Ubuntu的盘（ext4文件系统）上，后者的md5也变了。
> 
>     4. 电脑是Windows10和Ubuntu 20.04.5 LTS双系统的，双固态硬盘、两个系统分别在两个硬盘上，但是Ubuntu的/boot和/boot/efi是在Windows10的系统盘上。
> 
> 
> 试了很多方法，还是没有解决问题，目前没有解决思路了。请问一下有什么办法没？

可以考虑跑一下 memtest86，如果显示内存问题可以试试换根内存条。另外可以看看两块盘的 SMART 信息有没有问题。

**Comment by libreliu** [comment]
其实也可以考虑再拷贝回去，看看是否改变？
也可以看看 binary diff 类型的工具的输出，观察出现问题的模式等等。

**Comment by fourdim** [comment]
Ubuntu 的 linux kernel 更新到最新了么，看起来和 https://dirtypipe.cm4all.com/ 的 dirty pipe 好像

**Comment by Yuna95** [comment]
> > 1. 测试了下，下载的镜像包的md5还是和网站上的不一致。
> >    
> >    2. 现在发现，Windows10上下载的md5是一致的，Ubuntu 20.04.5 LTS上下载的md5不一致。
> >    3. 把在Windows10上下载的tar包（文件系统是NTFS）使用cp命令复制到Ubuntu的盘（ext4文件系统）上，后者的md5也变了。
> >    4. 电脑是Windows10和Ubuntu 20.04.5 LTS双系统的，双固态硬盘、两个系统分别在两个硬盘上，但是Ubuntu的/boot和/boot/efi是在Windows10的系统盘上。
> > 
> > 试了很多方法，还是没有解决问题，目前没有解决思路了。请问一下有什么办法没？
> 
> 可以考虑跑一下 memtest86，如果显示内存问题可以试试换根内存条。另外可以看看两块盘的 SMART 信息有没有问题。

SSD固态硬盘，在BIOS里面没有看到SMART信息，不过从厂家的工具中看，还是很健康的，memtest86有点点复杂，很多类似的工具，都不知道哪一个是官网了，哪一个好用点了。

**Comment by Yuna95** [comment]
> 其实也可以考虑再拷贝回去，看看是否改变？ 也可以看看 binary diff 类型的工具的输出，观察出现问题的模式等等。

环境说明：
1）Ubuntu桌面版操作系统。
2）2块SSD，A盘和B盘。源文件在A盘，是aosp-latest.tar文件，60GB。
3）A盘是NTFS文件系统，B盘是ext4文件系统。

从A盘拷贝到B盘，再从B盘拷贝回去，md5值确实变了，和A盘、B盘中的md5都不一样。但是如果从B盘拷贝到B盘，文件md5不变，不区分文件体积大小；从A盘拷贝到A盘、从A盘拷贝到B盘、从B盘拷贝到A盘，小文件（<200MB，测试用的文件166MB）文件的md5不变，大文件（>1GB，测试文件为1GB和3.6GB）会变。

我把A盘中的aosp-latest.tar文件用split命令分割成1GB的61份，然后用cp命令复制到B盘，发现1/3左右的文件md5校验失败了，又将校验失败的文件重传，才成功，但是用cat命令合并分割文件后，校验合并的文件的md5,仍然失败。

**Comment by Yuna95** [comment]
> Ubuntu 的 linux kernel 更新到最新了么，看起来和 https://dirtypipe.cm4all.com/ 的 dirty pipe 好像

5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

这两个版本的Ubuntu都用过，但是都无法正确复制文件。后者的内核比Dirty Pipe中的内核要新，每次安装后都用apt/apt-get upgrade更新过。

**Comment by taoky** [comment]
> memtest86有点点复杂，很多类似的工具，都不知道哪一个是官网了，哪一个好用点了。

可以直接从官方源安装 memtest86+，然后重启在 grub 里面选就行。
