### ISSUE TITLE
EPEL 9 同步失败

### ISSUE THREAD

**Issue by irort** [ustclug/discussions#419]
在更改完epel源后，运行 sudo dnf makecache , 报错404 
<a href="https://images4.imagebam.com/87/d4/08/MEK11XF_o.png" target="_blank"><img  src="https://images4.imagebam.com/87/d4/08/MEK11XF_o.png" alt="Screenshot_20230408_204628.png"/></a>

应该是https://mirrors.ustc.edu.cn/epel/9/Everything/x86_64/repodata/repomd.xml 和 https://mirrors.ustc.edu.cn/epel/9/Everything/x86_64/repodata/ 里的更新不同步 ，导致checksum不一致
<a href="https://images4.imagebam.com/48/0a/9c/MEK11XH_o.png" target="_blank"><img src="https://images4.imagebam.com/48/0a/9c/MEK11XH_o.png" alt="Screenshot_20230408_204824.png"/></a>
<a href="https://images4.imagebam.com/4a/f0/2c/MEK11XK_o.png" target="_blank"><img src="https://images4.imagebam.com/4a/f0/2c/MEK11XK_o.png" alt="Screenshot_20230408_205058.png"/></a>

**Comment by taoky** [comment]
epel 重新进行了同步，现在应该是正常的。推测原因是在上一次同步时上游的内容不一致所导致的。
