### ISSUE TITLE
Can you share your Status page source?

### ISSUE THREAD

**Issue by karibuTW** [ustclug/discussions#42]
Hi,

I'm running a mirror in Vietnam and I'd be thrilled to build the same status page as you have
http://mirrors.ustc.edu.cn/status/

How did you make it? Can you share the code may be?

Thank you

**Comment by zhsj** [comment]
@karibuTW The source is available at https://git.ustclug.org/mirrors/genstatus
These scripts have no documents currently. But it's written in Python and I think it is easy to understand.

**Comment by karibuTW** [comment]
Thanks for such fast response zhsj !

I will try out.

**Comment by gaoyifan** [comment]
The issue tracker is only limited to Features and Bugs. If you need further help, please mail us (lug@ustc.edu.cn) .
