### ISSUE TITLE
将Gentoo的镜像收录官方

### ISSUE THREAD

**Issue by jack9603301** [ustclug/discussions#420]
中国科学技术大学已经存在相关gentoo很久了，但从未被收录至https://www.gentoo.org/downloads/mirrors/

能否申请收录呢？

**Comment by taoky** [comment]
根据 <https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Source>，需要在 Gentoo Bugzilla 上注册账号并且提交请求。我刚刚注册了一个，由于注册后 24 小时内不能贴 URL，相关请求会在明晚之后提交。

**Comment by taoky** [comment]
我重新搜索了一下，在 2021 年 3 月份相关 Bug report 早已有提交：

https://bugs.gentoo.org/775998

但是上游没有做任何回应。

**Comment by jack9603301** [comment]
> 我重新搜索了一下，在 2021 年 3 月份相关 Bug report 早已有提交：
> 
> https://bugs.gentoo.org/775998
> 
> 但是上游没有做任何回应。

重新提交看看

**Comment by jack9603301** [comment]
@taoky 情况怎么样了？

**Comment by taoky** [comment]
> @taoky 情况怎么样了？

我回复了之前一位 Gentoo Developer 在去年抄送给我们的相关邮件，但是截至目前没有收到任何 mirror-admin 组成员的有关回复。

另外在这个 issue 下面催人是**没有任何意义的**。因为不是我（或者这里的其他人）不想/懒得进 mirrors 的列表。

**Comment by jack9603301** [comment]
> > @taoky 情况怎么样了？
> 
> 我回复了之前一位 Gentoo Developer 在去年抄送给我们的相关邮件，但是截至目前没有收到任何 mirror-admin 组成员的有关回复。
> 
> 另外在这个 issue 下面催人是**没有任何意义的**。因为不是我（或者这里的其他人）不想/懒得进 mirrors 的列表。

好的，我只是想看看你那边提交的怎么样了哈哈

**Comment by taoky** [comment]
上游已添加：

https://gitweb.gentoo.org/data/api.git/commit/?id=b20c533a58727876020f80bc4b229fcbd23ce9df

https://www.gentoo.org/downloads/mirrors/ 没有及时更新（包括 data/api.git 之前新增的镜像也没有及时更新在上面），可能单纯是这个页面没有很好地维护导致的。
