### ISSUE TITLE
Qt在线安装器添加此镜像源后提示如下图

### ISSUE THREAD

**Issue by AkarinLiu** [ustclug/discussions#421]
![image](https://user-images.githubusercontent.com/58081491/232951608-574453ba-5848-4ce4-8b07-dee1c0e152bc.png)

**Comment by taoky** [comment]
从错误信息看，这不是镜像站的问题。如果需要进一步调试，请提供：

- 系统中是否已经安装了 Qt 的组件？如果之前已经安装了，是如何安装的？
- 在线安装器是如何下载的？以及其版本信息。
- 你是如何「添加镜像源」的？

**Comment by AkarinLiu** [comment]
@taoky 

1.是通过在线安装进行安装
2.在线安装器从Qt官网下载，版本是v4.5.2
3.我是从“用户定义的资料档案库”来添加镜像源的

**Comment by taoky** [comment]
我测试用安装器 4.5.2 安装 Qt 6.4.3 (MinGW build) 没有遇到这个问题。

在测试的时候发现出现了哈希校验的问题，该问题已经修复。另外关于镜像站使用 rsync 无法从 Qt 上游获得正确的安装器软链接的问题也已经邮件反馈。

**Comment by taoky** [comment]
另外相比于手动添加档案库，用命令行更方便：

```
.\qt-unified-windows-x64-4.5.2-online.exe --mirror https://mirrors.ustc.edu.cn/qtproject
```

参见 https://mirrors.ustc.edu.cn/help/qtproject.html

**Comment by taoky** [comment]
图中的问题我搜索了一下，似乎可以参考 https://stackoverflow.com/questions/50001183/how-to-update-qt-maintenance-tool 解决。
