### ISSUE TITLE
请求新增Jellyfin镜像！

### ISSUE THREAD

**Issue by AkarinLiu** [ustclug/discussions#422]
镜像地址：https://repo.jellyfin.org
简介：Jellyfin是志愿者构建的媒体解决方案，可让您控制媒体。从您自己的服务器流式传输到任何设备，没有任何附加条件。您的媒体，您的服务器，您的方式。
镜像方案：http
支持的操作系统：Windows macOS Linux Docker

**Comment by taoky** [comment]
Duplicate of https://github.com/ustclug/mirrorrequest/issues/351
