### ISSUE TITLE
HomeBrew Bottles 镜像未收录 glibc-bootstrap 仓库

### ISSUE THREAD

**Issue by stevapple** [ustclug/discussions#424]
### 问题描述 / Bug description

https://github.com/Homebrew/glibc-bootstrap 仓库收录了本地构建 Glibc 所需的一些源码包，在指定 `HOMEBREW_BOTTLE_DOMAIN` 后会自动通过镜像站拉取，造成安装失败。

```
Failure while executing; `/usr/bin/env /opt/brew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/4.0.20\ \(Linux\;\ x86_64\ Ubuntu\ 20.04.4\ LTS\)\ curl/7.68.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://mirrors.ustc.edu.cn/homebrew-bottles/glibc-bootstrap/1.0.0/bootstrap-binutils-2.38.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/1.1 200 Connection established
```

以上述报错信息为例，URL `https://mirrors.ustc.edu.cn/homebrew-bottles/glibc-bootstrap/1.0.0/bootstrap-binutils-2.38.tar.gz` 应当镜像 `https://github.com/Homebrew/glibc-bootstrap/releases/download/1.0.0/bootstrap-binutils-2.38.tar.gz` 的内容。

**Comment by taoky** [comment]
已经在 github-release 中添加，并且设置了软链接。
