### ISSUE TITLE
freebsd-ports 源无法使用 gitup

### ISSUE THREAD

**Issue by ykla** [ustclug/discussions#426]
### 问题描述 / Bug description

gitup 是 FreeBSD 官方用来替代 portsnap 的。

```
[root@ykla /home/ykla]# gitup -v2 ports
# Host: mirrors.ustc.edu.cn
# Port: 443
# Repository Path: /freebsd-ports/ports.git
# Target Directory: /usr/ports
gitup: mirrors.ustc.edu.cn does not support the version 2 wire protocol: Protocol not supported
```

**Comment by taoky** [comment]
```console
> git -c protocol.version=2 clone https://mirrors.ustc.edu.cn/freebsd-ports/ports.git
Cloning into 'ports'...
remote: Enumerating objects: 5852263, done.
^C
```

至于为什么 gitup 认为不支持 version 2 wire protocol，可能得看代码才能知道。

**Comment by ykla** [comment]
gitup 的源码为 <https://github.com/johnmehr/gitup>。

**Comment by taoky** [comment]
检查了一下发现：

1. git-http-backend 确实没有使用 protocol 2，上面 git 只是 silently ignore 了版本不一致的问题
2. 检查了其环境变量之后发现 header 里面的 `Git-Protocol` 没有出现在 http-backend 的环境变量里面，修改配置后我用 `curl` 测试能够正确识别协议版本了。

gitup 我没有构建成功，但是从代码来看应该不会遇到这个问题了。如果还有问题可以 reopen。
