### ISSUE TITLE
Mirrors Status绘文字缺乏辨识度

### ISSUE THREAD

**Issue by liyishuai** [ustclug/discussions#427]
例：在黄色圆饼找出沮丧脸（界面经F12移除行底色及括号数字标记）
<img width="1248" alt="image" src="https://github.com/ustclug/discussions/assets/7020805/ead58182-93cf-4c6e-a32a-fd12e01cdce5">
提案：改用✅❌等颜色、轮廓均一眼可辨的图标。

**Comment by taoky** [comment]
GitHub 网页端似乎会转换代码块外面的 emoji 字符。看了一下和正确/错误有关的 emoji 大概有这些：

```
Check mark emojis:

☑️ (Check Box With Check) ✅ (Check Mark Button) ✔️ (Check Mark)

Cross mark emojis:

❎ (Cross Mark Button) ❌ (Cross Mark)

Others:

⭕ (Hollow Red Circle)
```

如果要从轮廓和颜色上区分，`✅`（绿底白色对勾）和 `❌`（透明背景红色叉号）应该是不错的选择。

**Comment by taoky** [comment]
Fixed by https://git.lug.ustc.edu.cn/mirrors/mirrors-index/-/commit/c2299e0fe03bd61d4aa5144b0f02b67d267a5fe6.
