### ISSUE TITLE
在线安装Qt时出现NotFound错误

### ISSUE THREAD

**Issue by c-my** [ustclug/discussions#429]
### 问题描述 / Bug description

在线安装时报错，提示找不到文件：

> 无法下载存档 https://mirrors.ustc.edu.cn/qtproject/online/qtsdkrepository/windows_x86/desktop/qt6_652_src_doc_examples/qt.qt6.652.doc/6.5.2-0-202307080351qt5-documentation.zip：Error transferring https://mirrors.ustc.edu.cn/qtproject/online/qtsdkrepository/windows_x86/desktop/qt6_652_src_doc_examples/qt.qt6.652.doc/6.5.2-0-202307080351qt5-documentation.zip.sha1 - server replied: Not Found

但该文件存在于Qt官方下载路径<https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_652_src_doc_examples/qt.qt6.652.doc/6.5.2-0-202307080351qt5-documentation.zip.sha1>

**Comment by taoky** [comment]
原因应该是从 rsync://master.qt-project.org/qt-all/ 同步太慢了，测试了各个能用的网络出口，甚至我用我自己的 VPS 跑 rsync 测试，最快也只有大约 100KB/s，导致同步很难追平进度。

**Comment by taoky** [comment]
根据 @shankerwangmiao 的建议，暂时切换到了伯克利大学的镜像作为上游同步（<rsync://mirrors.ocf.berkeley.edu/qt/>），从时间戳看上次更新在半天前，较为及时。

彻底的解决可能需要待 Qt 一方修复网络问题。

**Comment by taoky** [comment]
发现上面的上游也没有 @c-my 在 issue 里面说少的文件，在 https://download.qt.io/static/mirrorlist/ 里面找了一下，换成了 rsync://ftp.acc.umu.se/mirror/qt.io/qtproject/ 重新同步中。

**Comment by taoky** [comment]
上游切回了 master.qt-project.org.
