### ISSUE TITLE
HomeBrew API 缺失 `cask_tap_migrations.jws.json` 文件

### ISSUE THREAD

**Issue by stevapple** [ustclug/discussions#430]
### 问题描述 / Bug description

RT

```
Error: Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!
```

**Comment by taoky** [comment]
https://github.com/Homebrew/brew/blob/41ca77c6ac571d58eda505d38cce3685d2b3d818/Library/Homebrew/tap.rb#L1014

https://github.com/Homebrew/brew/blob/41ca77c6ac571d58eda505d38cce3685d2b3d818/Library/Homebrew/tap.rb#L1152

**Comment by taoky** [comment]
Fixed in https://github.com/ustclug/ustcmirror-images/commit/1354b614d92085ddce5c6024904a1a651c7ffcb0
