### ISSUE TITLE
HomeBrew 镜像增加 `cask-source` 支持

### ISSUE THREAD

**Issue by stevapple** [ustclug/discussions#431]
### 功能描述 / Feature description

RT，源站为 `raw.githubusercontent.com`（部分 ISP 访问困难），`formulae.brew.sh/api/cask-source` 下有一份镜像。

代码参考在此
https://github.com/Homebrew/brew/blob/41ca77c6ac571d58eda505d38cce3685d2b3d818/Library/Homebrew/api/cask.rb#L32-L36

**Comment by taoky** [comment]
Implemented in https://github.com/ustclug/ustcmirror-images/commit/e9f01774fc445efd21872a7e877104a626e9e17d.
