### ISSUE TITLE
更新 k8s 镜像同步上游至 pkgs.k8s.io

### ISSUE THREAD

**Issue by taoky** [ustclug/discussions#433]
Ref:
- https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/
- https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

**Comment by taoky** [comment]
旧的托管在 packages.cloud.google.com 上的 k8s deb/rpm 仓库会在 9/13 冻结。

新版本的配置格式：

```
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
```

```
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
```

如何获取版本号（URL 中间的 `v1.28`）列表？不知道，pkgs.k8s.io 也不允许列目录。

**Comment by knight42** [comment]
如果改动很大的话，我觉得可以先结合目前的使用量来看看是否要继续维护。

> 如何获取版本号（URL 中间的 v1.28）列表？

目前我能想到几种方法
1. 列出 k8s 仓库最近更新的几个分支 https://github.com/kubernetes/kubernetes/branches ，格式是 `release-{version}`
2. 调 https://endoflife.date/api/kubernetes.json 这个 API 获取（不确定是否会一直维护）
3. 比较邪道的办法，k8s 的 [release 周期](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md)比较固定，大概是一年三次，可以根据目前的时间算一个出来

**Comment by ajl520** [comment]
所以这个issue有什么更新么？

**Comment by taoky** [comment]
> 所以这个issue有什么更新么？

需要有一个人来写同步脚本，处理 k8s 的版本问题。

- TUNA 的同步脚本在 https://github.com/tuna/tunasync-scripts/blob/master/kubernetes.sh
- 我们的在 <https://github.com/ustclug/ustcmirror-images>，鉴于目前的情况，可能需要新建一个同步的容器 image

**Comment by taoky** [comment]
https://github.com/CQUPTMirror/Report/issues/47#issuecomment-2089676501

**Comment by taoky** [comment]
从 OpenSUSE OBS 使用 rsync 同步的新 k8s 镜像已经上线。

**Comment by yewq** [comment]
似乎仓库在 7 月以后就不更新了，[OBS browsable](https://download.opensuse.org/repositories/isv:/kubernetes:/core:/stable:/) 已经更新到 v1.31

**Comment by taoky** [comment]
> 似乎仓库在 7 月以后就不更新了，[OBS browsable](https://download.opensuse.org/repositories/isv:/kubernetes:/core:/stable:/) 已经更新到 v1.31

检查之后发现 rsync://stage.opensuse.org 有 1.31，但是 rsync://rsync.opensuse.org 没有。按照 https://en.opensuse.org/openSUSE:Mirror_infrastructure#rsync_modules 的说法，后者从前者同步，并且时间差应该会很短。但是 v1.31 已经过去两个月了，可能是 OpenSUSE 方面的问题。我先把上游修改为了 rsync://stage.opensuse.org，现在正在同步。
