### ISSUE TITLE
Missing files in debian-cdimage repository

### ISSUE THREAD

**Issue by PhotonQuantum** [ustclug/discussions#437]
### 问题描述 / Bug description

Ref: https://github.com/sjtug/mirror-requests/issues/327

Upstream: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
Actual: http://mirrors.ustc.edu.cn/debian-cdimage/cloud/bookworm/latest/debian-12-generic-amd64.qcow2

Trace generated by our gateway:
```
wrong path or broken symlink

link trace:
"" / "cloud": followed directory
"cloud" / "bookworm": followed directory
"cloud/bookworm" / "latest": following symlink -> "20231013-1532/.latest"
"cloud/bookworm" / "20231013-1532": followed directory
"cloud/bookworm/20231013-1532" / ".latest": not found, abort
```

The reason for this could be that all dot files have been excluded.

**Comment by zzzyf01** [comment]
更新了同步规则，保留了.latest文件的同步，问题已解决。
