### ISSUE TITLE
nix-channels下的nixpkgs-unstable目录同步似乎挂了

### ISSUE THREAD

**Issue by holymonson** [ustclug/discussions#440]
### 问题描述 / Bug description

请检查此目录的同步 https://mirrors.ustc.edu.cn/nix-channels/nixpkgs-unstable/
对比隔壁 https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable/

**Comment by taoky** [comment]
Ref:
- https://github.com/tuna/issues/issues/1855
- https://github.com/tuna/tunasync-scripts/pull/169
- https://github.com/NixOS/nixos-org-configurations/issues/309
- https://github.com/NixOS/nixpkgs/pull/270232

在上游已经有 PR 尝试修复的情况下，我不认为采取像 https://github.com/tuna/tunasync-scripts/pull/169/commits/2fda08453341bd85a669acb02296a27a6f731bdf 一样很丑的 workaround 是一个好主意。作为非 nix 开发者来讲，目前能做的应该是给 https://github.com/NixOS/nixpkgs/pull/270232 点 👍 reaction。

**Comment by holymonson** [comment]
粗看了一下，同步文件列表是取自`store-paths.xz`，而里面列的文件有缺失，所以同步失败了。
个人建议，对缺失的文件，直接报warning跳过即可，没必要报error吧？因为这仅仅是cache mirror，文件缺失了的话nix会往下一级找，找不着还会自己build。因此停了同步一个多月，还不知啥时会修好，实属不值。

**Comment by holymonson** [comment]
我的意思是，对 __任意缺失的文件__，而非目前缺失的特定几个做workaround。

**Comment by taoky** [comment]
> 个人建议，对缺失的文件，直接报warning跳过即可，没必要报error吧？

非 0 的返回值是 `nix path-info` 返回的，没有选项抑制这种行为。

> 我的意思是，对 任意缺失的文件，而非目前缺失的特定几个做workaround。

https://github.com/ustclug/ustcmirror-images/commit/46006f0141a41806e1f2fee8ea76758310ce17fa 已经添加了一个 workaround，在 nix 返回错误的时候选择跳过 batch 继续 channel 中下一个 batch 的处理。

一个 batch 有 8192 个包，因此最坏情况下 n 次错误会导致 8191 * n 个包的缓存不会被下载。这是上游不修复 + 脚本不大改的情况下能接受的最佳方案了。

去掉 batch 恐怕不能接受，因为本来列包的部分就已经很慢很慢了，再把 batch 去掉，那就真的不知道要等到猴年马月才能同步好了。Nix binary cache 本身的设计也对非对象存储的架构非常不友好，之后可能会放弃现在做全量 cache 的方案。

**Comment by holymonson** [comment]
> 一个 batch 有 8192 个包，因此最坏情况下 n 次错误会导致 8191 * n 个包的缓存不会被下载。这是上游不修复 + 脚本不大改的情况下能接受的最佳方案了。

查询部分写成函数`func(batch)`，当出错时，递归执行`func(batch[0:len(batch)//2])` `func(batch[len(batch)//2:len(batch)])`，直到`len(batch)==1`定位出缺失的包。这样的思路可以？

**Comment by taoky** [comment]
> > 一个 batch 有 8192 个包，因此最坏情况下 n 次错误会导致 8191 * n 个包的缓存不会被下载。这是上游不修复 + 脚本不大改的情况下能接受的最佳方案了。
> 
> 查询部分写成函数`func(batch)`，当出错时，递归执行`func(batch[0:len(batch)//2])` `func(batch[len(batch)//2:len(batch)])`，直到`len(batch)==1`定位出缺失的包。这样的思路可以？

你没有办法保证一批里**只**会有**一个**这个类型的错误（正如某个笑话所说，图书管理员用二分法从某个离开图书馆的人拿着的一摞书里找出了没有消磁的一本书，但结果导致了 n-1 本书没有登记就被从图书馆里拿走了一样），而加上边缘情况的处理会带来大量额外的 I/O 开销，以及显著增加了同步脚本的复杂性。

所以与其催我去「修」同步脚本，**催上游快点把这个问题修掉**是更简单，也对各方都有利的方案。

**Comment by dramforever** [comment]
作为传说中的“上游”，我也同意没有必要专门对加相关的处理。如果真的加上的话结果就是代码里永远有一段只在 2023 年底的时候的几个月运行了的错误处理，其它时候放在那里，没有实际运行，也不知道和别的错误（比如临时的网络问题）有没有影响的代码。

预计等 https://github.com/NixOS/nixpkgs/pull/270232 合并后，过一段时间等没有 channel 会被这个影响后，我会把基于名字匹配的这个 workaround revert 掉。
