### ISSUE TITLE
Gentoo 相关源同步频率是否可以优化一下

### ISSUE THREAD

**Issue by Nuralii1i** [ustclug/discussions#443]
### 功能描述 / Feature description

首先，作为常年白嫖的老菜鸡由衷的感谢各位的付出，非常感谢！
其次：
`gentoo.git` 和 `gentoo-portage` 两个源同步的其实都是 `Ebuild` 脚本，在Gentoo用户群体中，除非刚开始安装时会用 `rsync` 同步（也就是使用 `gentoo-portage` 源，因为默认就是 `rsync`）之外，大多数用户都会选择用 `Git` 同步（即使用 `gentoo.git` 源，别的镜像站也有叫 `gentoo-portage.git` 的）
同步 `Ebuild` 仓库的同时，还得同步源码（即 `Gentoo` 源）
然鹅，深得我心的中科大镜像站这三者同步频率貌似都不一致（三者是指 `Gentoo`，`Gentoo-portage` 和 `Gentoo.git` 源）
我在想是否可以优化一下

**Comment by taoky** [comment]
gentoo: `54 2,6,10,14,18,22 * * *`
gentoo-portage: `18 1-23/6 * * *`
gentoo.git: `7 6 * * *`

`gentoo.git` 的同步频率确实可能低了。

然后我不太确定 gentoo 和 gentoo-portage 是否是强关联的（如果有一个没有及时同步就会 break 掉另一个），如果不是的话保持现在这样，或者 gentoo-portage 也调成每 4h 同步一次。一个主要考虑是最好不同时开启很多同步任务，否则可能会给网络/磁盘带来额外的压力。

**Comment by Nuralii1i** [comment]
> gentoo: `54 2,6,10,14,18,22 * * *` gentoo-portage: `18 1-23/6 * * *` gentoo.git: `7 6 * * *`
> 
> `gentoo.git` 的同步频率确实可能低了。
> 
> 然后我不太确定 gentoo 和 gentoo-portage 是否是强关联的（如果有一个没有及时同步就会 break 掉另一个），如果不是的话保持现在这样，或者 gentoo-portage 也调成每 4h 同步一次。一个主要考虑是最好不同时开启很多同步任务，否则可能会给网络/磁盘带来额外的压力。

emmm,是这样的, `gentoo-portage` 和 `gentoo.git` 同步的Ebuild脚本会包含指向源码上游的连接，一般是 `SRC_URI` 变量
同时Ebuild大概率还会有个关键字会携带 `mirror` ，意味着并不需要真的去上游下载源码，而是优先去设定的 Distfiles镜像站（即 `gentoo` 源）下载，找不到该版本的源码包，再去设定的上游连接进行fetch。
按理来说没有什么强关联，但是GFW的存在导致了必须依赖镜像站
感觉可以提高 `gentoo.git` 源的同步频率，降低 `gentoo-portage` 源的频率（若有必要的话），同时 `gentoo` 源的更新不要跟 `gentoo.git` 源的差太久就好了

**Comment by taoky** [comment]
目前 gentoo.git 调到了 `7 0-23/6 * * *`，另外 gentoo 是四小时更新一次，所以应该不会出现差太久的情况。

**Comment by Nuralii1i** [comment]
> 目前 gentoo.git 调到了 `7 0-23/6 * * *`，另外 gentoo 是四小时更新一次，所以应该不会出现差太久的情况。

非常感谢，我上面提到的"gentoo-portage源用户少"言论貌似有些欠考虑了，我在我们的QQ群里发起了投票，发现还是有30%-40％用户都会选择Rsync
那么，这issue就关闭了吧
