### ISSUE TITLE
salt 源不更新

### ISSUE THREAD

**Issue by 111wang222** [ustclug/discussions#444]
问题：
Salt软件包源与官方Salt仓库中的软件包不一致。ustc源中的软件包似乎没有更新到官方仓库中最新版本的软件包
该源中的软件包与官方仓库相比已经过时。这导致无法将Salt更新到最新版本，可能导致已经在新版本中修复的安全漏洞或错误。

[ustc源](https://mirrors.ustc.edu.cn/salt/py3/redhat/)
[salt官方源](https://repo.saltproject.io/salt/py3/redhat/)

请求同步更新，以确保用户可以访问Salt及其依赖的最新版本，有助于保持不同环境之间的一致性和安全性。
十分感谢！

**Comment by taoky** [comment]
需要 salt 上游修复此问题：https://github.com/saltstack/salt/issues/64140

**Comment by taoky** [comment]
另外其他文件的更新应该都是正常的，看起来你说的目录在 https://mirrors.ustc.edu.cn/salt/salt/py3/redhat/

**Comment by taoky** [comment]
将 index.html 加入了同步排除列表，以帮助减少误解。
