### ISSUE TITLE
OpenWrt 的 SNAPSHOT 404了

### ISSUE THREAD

**Issue by Karmylr** [ustclug/discussions#445]
OpenWrt 的 SNAPSHOT 镜像404了
https://mirrors.ustc.edu.cn/openwrt/releases/

**Comment by taoky** [comment]
https://mirrors.ustc.edu.cn/openwrt/snapshots/ -> https://openwrt.proxy.ustclug.org/snapshots/targets/

清空了反代的缓存，问题似乎解决了。看起来是 https://downloads.openwrt.org/ 在某个时间段内内容变成了 <https://firmware-selector.openwrt.org/>，然后结果被缓存了下来。
