### ISSUE TITLE
移动/电信的运营商线路能否增加IPv6地址

### ISSUE THREAD

**Issue by cctv4-cgtn** [ustclug/discussions#449]
### 功能描述 / Feature description

ustc镜像站的IPv4地址应该用的是自己的IP+移动/电信的AS代播免去跨网访问这点很好（未查阅任何资料仅个人推测如果不对请指正）
IPv6能否也拿出部分IP交给运营商代播？

**Comment by iBug** [comment]
这个超出了我们的能力范围，等学校打算接入运营商的 IPv6 才能安排（据我所知没有计划）。

**Comment by cctv4-cgtn** [comment]
感谢回复
