### ISSUE TITLE
neatdns增加对edns-client-subnet的支持

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#45]

**Comment by zhsj** [comment]
各位有没有动力自己写一个 Forward DNS？
其实感觉只是Forward的话，还不算复杂。关于 ECS 的话，请求者带了  ECS option 的话，就把这个参数直接转发给上游；没有的话，把请求者的 ip 作为 ECS subnet 参数传给上游。
感觉难度应该就两个，一是缓存记录；二是现在用了 dnsmasq-china-list，有一个大表要查询，设计个像字典树一样的数据结构应该会比较快。

**Comment by gaoyifan** [comment]
这种成熟的轮子为什么要自己造咧？练练手？

**Comment by StephenPCG** [comment]
@zhsj forward dns带ECS似乎没什么用，public dns（例如8.8.8.8、114.114.114.114）似乎并不采纳下游携带的ECS信息（它们在递归时，并不尊重下游的ECS信息，而是把它们看到的下游的地址作为ECS传递给上游权威解析服务器）。

dnsmasq从某个版本开始支持``--add-subnet``参数，我曾经尝试过，发现并没有用。当时好像读到过一篇文章，讲为什么这些dns不尊重下游的ECS信息，我一时找不到当时看过的文章了。

**Comment by gaoyifan** [comment]
@StephenPCG  Google Public DNS是支持下游提交edns请求的。需要申请加入白名单：https://groups.google.com/d/topic/public-dns-announce/67oxFjSLeUM/discussion

**Comment by StephenPCG** [comment]
@gaoyifan 你贴的这个链接似乎不对，这个链接讲的应该是8.8.8.8会自动探测权威服务器是否支持EDNS，如果权威服务器支持，那么发送给权威服务器的请求就会带上ECS信息。

**Comment by gaoyifan** [comment]
@StephenPCG 是我理解错了....

**Comment by zhsj** [comment]
@StephenPCG 确实，测了下 8.8.8.8 不支持。不过有意思的是，223.5.5.5 竟然支持。

zsj@debian ~ $ dig dl.google.com @223.5.5.5 +subnet=202.38.64.1 +short
dl.l.google.com.
203.208.48.66
203.208.48.72
203.208.48.73
203.208.48.65
203.208.48.64
203.208.48.70
203.208.48.68
203.208.48.67
203.208.48.69
203.208.48.71
203.208.48.78
zsj@debian ~ $ dig dl.google.com @223.5.5.5 +subnet=128.199.125.193 +short
dl.l.google.com.
216.58.196.238

**Comment by zhsj** [comment]
这样说的话，如果 8.8.8.8 不支持 Forward 过去的 ECS 选项的话，那应该没什么成熟的轮子来让 neatdns 支持 ECS？

不过，要自己实现的话，其实也是有办法的，就是 Google Public DNS 的 HTTP API。neatdns 收到请求后，利用 HTTPDNS 来转发。国内的话，就用 Ali DNS。

**Comment by zhsj** [comment]
国内的 HTTPDNS，提供公共服务的就两个，114和 DNSPod。114 只支持 A 记录，DNSPod 支持 A/AAAA 记录。
HTTPDNS 的

**Comment by zhsj** [comment]
不好意思，点错了。。。

**Comment by zhsj** [comment]
@gaoyifan 我错了。。。测试的时候没挂 vpn，8.8.8.8 被劫持了。。。

**Comment by StephenPCG** [comment]
@gaoyifan 我刚才测试了一下，8.8.8.8确实支持。

**Comment by gaoyifan** [comment]
我将neatdns的bind更新到了9.11.0-P1( https://github.com/ustclug/neatdns/commit/f7e61a2340df29e4bc19067bb922f69da702a5b0 )，但edns并没有生效。[手册](https://ftp.isc.org/isc/bind9/cur/9.11/doc/arm/Bv9ARM.ch06.html)中也没有提到相关选项。
大家有什么想法吗？

**Comment by zhsj** [comment]
@gaoyifan 有什么证据可以证明 bind 9.11.0-P1 作为 Recursive DNS 时支持 ECS 的吗？
我查到的资料都是说作为 Authoritative DNS 支持 ECS？

**Comment by gaoyifan** [comment]
@zhsj 没有证据哎，所以才困惑.....

**Comment by zhsj** [comment]
我们来自己写吧，我先开个坑 https://github.com/zhsj/fdns :see_no_evil:

**Comment by gaoyifan** [comment]
看了一下9.11的release note,  ECS的相关内容中的确没有提到forwarder:

> The EDNS Client Subnet (ECS) option is now supported for authoritative servers; if a query contains an ECS option then ACLs containing geoip or ecs elements can match against the address encoded in the option. This can be used to select a view for a query, so that different answers can be provided depending on the client network.
> The EDNS EXPIRE option has been implemented on the client side, allowing a slave server to set the expiration timer correctly when transferring zone data from another slave server.

**Comment by gaoyifan** [comment]
5353端口增加ECS特性。先试验一段时间。

**Comment by deepzz0** [comment]
bind 支持转发 EDNS 查询请求吗？

如，我发起一个 EDNS 查询请求到 bind9，bind9 会从根服务器遍历查找，当查到 NS 的时候，它会把这个 EDNS 请求发到 NS 服务器上吗？

**Comment by gaoyifan** [comment]
@deepzz0  
第一个问题：不支持
第二个问题：一般而言，不仅会将ECS扩展转发给最终的NS，递归路径上的NS服务器也会收到ECS扩展。

**Comment by deepzz0** [comment]
@gaoyifan 
EDNS 现在 Bind 是支持的（9.10 之后），但在我查询的时候出现这个说明：
```
13-Nov-2017 08:05:34.970 edns-disabled: info: success resolving 'www.gds.alibaba.com/A' (in 'gds.alibaba.com'?) after disabling EDNS
```
完全没明白什么意思？难道 Bind 还有开启 EDNS 的开关。而且我抓包显示，bind9出去的并没有 EDNS 扩展。网上有说是 UDP 包大小的关系，但 TCP 测试同样但效果。

**Comment by gaoyifan** [comment]
@deepzz0  只有bind的权威服务器支持ECS，递归不支持。

**Comment by deepzz0** [comment]
@gaoyifan 这和ECS没有关系吧。我的目的是想让bind帮我把 EDNS 的请求发出去，并不是说让 bind 帮我解析 ECS。

**Comment by gaoyifan** [comment]
@deepzz0  我没表述清楚么.....   Bind的转发服务器不支持你说的功能.....

**Comment by gaoyifan** [comment]
https://servers.ustclug.org/2017/11/neatdns-support-ecs-and-dns-over-tls/
