### ISSUE TITLE
无法访问科大镜像源

### ISSUE THREAD

**Issue by xiaole992** [ustclug/discussions#451]
你好，请问下是否有封禁这个段的地址，无法访问科大镜像源。183.237.208.128-183.237.208.254

**Comment by taoky** [comment]
目前没有封禁 183.237.208.128/25。提供更详细的错误信息会有助于解决问题。

另：请不要在 https://github.com/ustclug/mirrorhelp/ 反馈故障报告。该 issue 已经迁移到了正确的地方。

**Comment by xiaole992** [comment]
访问ipv4.mirrors.ustc.edu.cn，科大没有返回数据包回来

**Comment by taoky** [comment]
> 访问ipv4.mirrors.ustc.edu.cn，科大没有返回数据包回来

请给一下 curl, ping 和 mtr（或 traceroute）的输出。

参考命令：

```console
curl -v ipv4.mirrors.ustc.edu.cn
ping ipv4.mirrors.ustc.edu.cn
mtr ipv4.mirrors.ustc.edu.cn
traceroute ipv4.mirrors.ustc.edu.cn
```

**Comment by xiaole992** [comment]
curl -v ipv4.mirrors.ustc.edu.cn
* About to connect() to ipv4.mirrors.ustc.edu.cn port 80 (#0)
*   Trying 202.141.160.110...

**Comment by iBug** [comment]
我从两处不同的校外网络环境测试，均可以正常通过 202.141.160.110 和 80 端口访问，因此更可能是你的网络环境存在故障。请提供 traceroute 或 mtr 信息我们才能进一步排查。

或者你也可以使用其他线路访问：

- [cernet.mirrors.ustc.edu.cn](https://cernet.mirrors.ustc.edu.cn/) 教育网线路（推荐）
- [chinanet.mirrors.ustc.edu.cn](https://chinanet.mirrors.ustc.edu.cn/) 电信线路
- [unicom.mirrors.ustc.edu.cn](https://unicom.mirrors.ustc.edu.cn/) 联通线路
- [cmcc.mirrors.ustc.edu.cn](https://cmcc.mirrors.ustc.edu.cn/) 移动线路
- [ipv6.mirrors.ustc.edu.cn](https://ipv6.mirrors.ustc.edu.cn/) IPv6 线路（推荐）

**Comment by xiaole992** [comment]
Host                                                                        Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 10.147.2.254                                                              0.0%     8    3.5   3.5   2.6   8.2   1.9
 2. 10.1.67.43                                                                0.0%     8    1.4   1.5   0.8   2.1   0.0
 3. 10.1.67.50                                                                0.0%     8    4.4   4.6   3.5   8.3   1.5
 4. 10.145.0.49                                                               0.0%     8    3.4   3.8   2.2   6.0   1.3
 5. 10.145.0.17                                                               0.0%     8    3.4   3.6   2.6   4.8   0.4
 6. 59.36.14.49                                                               0.0%     8    4.4   4.7   3.4   6.1   0.7
 7. 192.168.10.6                                                              0.0%     8    5.4   5.0   3.5   7.0   1.1
 8. 221.179.29.9                                                              0.0%     8   10.5   7.9   5.3  11.1   2.5
 9. ???

**Comment by taoky** [comment]
>     6. 59.36.14.49                                                               0.0%     8    4.4   4.7   3.4   6.1   0.7
>     7. 192.168.10.6                                                              0.0%     8    5.4   5.0   3.5   7.0   1.1
>     8. 221.179.29.9                                                              0.0%     8   10.5   7.9   5.3  11.1   2.5
>     9. ???

从 traceroute 看，数据包最后似乎到达了移动网络，然后被丢弃：

```console
> nali 221.179.29.9
221.179.29.9 [海南省海口市 移动]
```

建议联系运营商反馈故障，镜像站一端无法解决此问题。

**Comment by iBug** [comment]
从你提供的 mtr 输出查询 IP 归属情况如下：

1. 10.147.2.254 [局域网 IP]
2. 10.1.67.43 [局域网 IP]
3. 10.1.67.50 [局域网 IP]
4. 10.145.0.49 [局域网 IP]
5. 10.145.0.17 [局域网 IP]
6. 59.36.14.49 [广东省东莞市 电信]
7. 192.168.10.6 [局域网 对方和您在同一内部网]
8. 221.179.29.9 [海南省海口市 移动]
9. ???

路由是在移动骨干网上中断的，与科大镜像站无关，请联系你的网络运营商寻求进一步帮助。
