### ISSUE TITLE
rust-static 源无法正常工作 打开显示为xml而不是一个目录

### ISSUE THREAD

**Issue by bbbyyl** [ustclug/discussions#453]
### 问题描述 / Bug description

https://mirrors.ustc.edu.cn/rust-static/
打开显示为xml而不是一个目录  如下：
[Uploading 下载.xml.txt…]()

正常应该类似这样 呈现一个目录
https://mirrors.tuna.tsinghua.edu.cn/rustup/

**Comment by taoky** [comment]
这是预期的行为。
