### ISSUE TITLE
freebsd-pkg 源损坏

### ISSUE THREAD

**Issue by Alex6357** [ustclug/discussions#458]
### 问题描述 / Bug description

[https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD:14:amd64/quarterly/Latest/](https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD%3A14%3Aamd64/quarterly/Latest/) 目录下应该有 pkg 文件，现在消失了，文件夹时间也不对

**Comment by taoky** [comment]
同步的问题在 https://github.com/ustclug/ustcmirror-images/commit/d34eb24fd86d13aadbe819be8e34e5e6c540810f 作了修正，但是似乎进度掉得有点多，加上到上游的带宽只有一两百 KB/s，同步了两天也没有结束，要完全追上进度应该还需要一些时间。
