### ISSUE TITLE
Mac Safari 17.5 环境下，获取 ISO 返回 421 Misdirected Request

### ISSUE THREAD

**Issue by Arnie97** [ustclug/discussions#459]
### 问题描述 / Bug description

此问题与浏览器有强关联，相同网络环境下的其他浏览器不复现（Chrome 内核浏览器会在 `This page requires JavaScript. Please wait 2 seconds.` 停留后正常进入下载）。除 Safari 正常模式外，用 Safari 隐身模式仍可复现，用 Safari WebKit 开发者工具关闭浏览器缓存仍可复现。怀疑是 Safari 在 302 重定向后，对第二次请求 header 的处理行为与其他浏览器不同，不排除是 Safari 代码缺陷。比较怪异的是，用开发者工具复制出的 Safari curl 请求不复现（请求如下：）
```sh
curl 'https://iso.mirrors.ustc.edu.cn/ubuntu-cdimage/ubuntukylin/releases/noble/release/ubuntukylin-24.04-desktop-amd64.iso' \
-X 'GET' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Pragma: no-cache' \
-H 'Sec-Fetch-Site: none' \
-H 'Cache-Control: no-cache' \
-H 'Sec-Fetch-Dest: document' \
-H 'Sec-Fetch-Mode: navigate' \
-H 'Host: iso.mirrors.ustc.edu.cn' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Connection: keep-alive'
```
![Safari Screenshot](https://github.com/ustclug/discussions/assets/10341686/99a11e40-2f19-483c-a8cf-79b223856339)

**Comment by taoky** [comment]
emmm 我本地用 GNOME Web 46.1 和 iOS Safari 都复现不出来，一会找个 Mac 看看……

**Comment by tiankaima** [comment]
@taoky 我来?

**Comment by ustcljh** [comment]
我这里行为是正常的
![IMG_4705](https://github.com/ustclug/discussions/assets/147305241/bf32f706-f8a9-4428-9e13-b603a739c999)

**Comment by tiankaima** [comment]
还是无法复现这一问题, 能提供更完整的时序图吗

<img width="794" alt="图片" src="https://github.com/ustclug/discussions/assets/91816094/d89f90d2-8718-48b9-bf94-8e75557121dc">

<img width="396" alt="图片" src="https://github.com/ustclug/discussions/assets/91816094/1e2622ee-c37b-4a81-8107-60bf88879014">

对了一下 UA 应该是这个版本, 对吧

**Comment by tiankaima** [comment]
@tiankaima

**Comment by taoky** [comment]
可能相关：https://trac.nginx.org/nginx/ticket/1252

**Comment by taoky** [comment]
检查 nginx 配置时发现 iso.mirrors 对应的 server block 未开启 http2。目前已经作了修改，全部启用了 http2，可以试一下问题是否还能够复现。

（虽然从 https://github.com/envoyproxy/envoy/issues/6767#issuecomment-1010733256 和 https://bugs.webkit.org/show_bug.cgi?id=192926 来看，这个 bug 应该 macOS 早就修了，但是可能在访问的域名没有 http2 支持的时候还是会出错？不太确定）

**Comment by Arnie97** [comment]
经测试，nginx 开启 HTTP2 后，问题已不能复现。
UA 和楼上有轻微差异：`Version 17.5 (18618.2.12.111.5, 18618)`

<img width="396" alt="image" src="https://github.com/ustclug/discussions/assets/10341686/a1a680ce-50d5-4d9d-8713-5cc00e3ea651">

**Comment by Arnie97** [comment]
对比我俩贴的时序图，发现以下区别：
1. 问题发生时，我理解重定向前是 HTTPS 1.1 请求（截图中 `GET /path` 开头），重定向后是 HTTP 2 请求（`:method GET` 开头）。
2. tiankaima 的对照组中，重定向前后均是 HTTPS 1.1 请求。
3. 目前修改 nginx 配置后，我的浏览器仍然保持着重定向前是 HTTPS 1.1 请求，重定向后是 HTTP 2 请求的行为。但是重定向后的 HTTP 2 请求不返回 421 了，成功返回了 200。

**Comment by tiankaima** [comment]
更改 nginx 配置之前, Safari 将 302 目标升级到 HTTP/2 应该是非预期行为, 并不是跟服务器协商的结果, 就算是 421 也应该交由 Safari 处理.

Google 一下 `safari http2 421` 能出来不少东西. ~~I blame Apple.~~ Anyways 解决了就好.
