### ISSUE TITLE
请求更换本站slackware目前的上游镜像站

### ISSUE THREAD

**Issue by linuxjinjin** [ustclug/discussions#460]
将目前的rsync://slackware.cs.utah.edu/slackware/更换成rsync://ftp.slackware.com/slackware/
原因是slackware.cs.utah.edu/slackware/已于2024年5月26日停止更新。

**Comment by taoky** [comment]
更换为了 rsync://rsync.osuosl.org/slackware/，正在重新同步。

**Comment by taoky** [comment]
同步到了最新版本。
