### ISSUE TITLE
ROS unexpected file size

### ISSUE THREAD

**Issue by sdaheng** [ustclug/discussions#462]
### 问题描述 / Bug description

sudo apt update

Hit:1 http://mirrors.ustc.edu.cn/ubuntu jammy InRelease
Hit:2 http://mirrors.ustc.edu.cn/ubuntu jammy-updates InRelease
Hit:4 http://mirrors.ustc.edu.cn/ubuntu jammy-backports InRelease
Hit:5 http://mirrors.ustc.edu.cn/ubuntu jammy-security InRelease
Get:6 https://mirrors.ustc.edu.cn/ros/ubuntu focal InRelease [4,679 B]
Hit:7 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:3 https://packages.microsoft.com/repos/code stable InRelease
Get:8 https://mirrors.ustc.edu.cn/ros/ubuntu focal/main i386 Packages [59.5 kB]
Err:8 https://mirrors.ustc.edu.cn/ros/ubuntu focal/main i386 Packages
  File has unexpected size (59457 != 59487). Mirror sync in progress? [IP: 2001:da8:d800:95::110 443]
  Hashes of expected file:
   - Filesize:59487 [weak]
   - SHA256:7424f845b313b4439fba18708c1723eea97fb22f8bccfe9f5a155b63ca52701b
   - SHA1:e738c9e15089260cac955cc73d16bd6de23d37ae [weak]
   - MD5Sum:a3ec2d0321be449266d17bf4b09c6c85 [weak]
  Release file created at: Tue, 25 Jun 2024 14:39:42 +0000
Get:9 https://mirrors.ustc.edu.cn/ros/ubuntu focal/main amd64 Packages [815 kB]
Ign:10 https://releases.warp.dev/linux/deb stable InRelease
Hit:11 https://releases.warp.dev/linux/deb stable Release
Hit:13 http://packages.ros.org/ros2/ubuntu focal InRelease
Reading package lists... Done
E: Failed to fetch https://mirrors.ustc.edu.cn/ros/ubuntu/dists/focal/main/binary-i386/Packages.gz  File has unexpected size (59457 != 59487). Mirror sync in progress? [IP: 2001:da8:d800:95::110 443]
   Hashes of expected file:
    - Filesize:59487 [weak]
    - SHA256:7424f845b313b4439fba18708c1723eea97fb22f8bccfe9f5a155b63ca52701b
    - SHA1:e738c9e15089260cac955cc73d16bd6de23d37ae [weak]
    - MD5Sum:a3ec2d0321be449266d17bf4b09c6c85 [weak]
   Release file created at: Tue, 25 Jun 2024 14:39:42 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by tiankaima** [comment]
```
> wget -q https://mirrors.ustc.edu.cn/ros/ubuntu/dists/focal/main/binary-i386/Packages.gz

> sha256sum ./Packages.gz
066698e22af902d2769443b9573654fe92c0931f44ed879345c12d6bca19f6cf  ./Packages.gz

> ls -al ./Packages.gz
-rw-r--r--@ 1 tiankaima  staff  59457 May  9 06:11 ./Packages.gz
```

**Comment by taoky** [comment]
~~官方上游亦如此：~~

```
root@c8c18dbef0fe:/# apt update
Hit:1 http://mirrors.ustc.edu.cn/ubuntu focal InRelease
Hit:2 http://mirrors.ustc.edu.cn/ubuntu focal-updates InRelease
Hit:3 http://mirrors.ustc.edu.cn/ubuntu focal-backports InRelease
Hit:4 http://mirrors.ustc.edu.cn/ubuntu focal-security InRelease
Ign:5 https://packages.ros.org/ros/ubuntu focal InRelease
Err:6 https://packages.ros.org/ros/ubuntu focal Release
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 64.50.236.52 443]
Reading package lists... Done
E: The repository 'https://packages.ros.org/ros/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

~~镜像站一端目前无法解决此问题，考虑使用 `dpkg --remove-architecture i386` 移除对应架构，或者切换至 ROS2。~~

**Comment by taoky** [comment]
抱歉看错了消息，上游 (http) 应该是正常的：

```
root@c8c18dbef0fe:/# apt update
Hit:1 http://mirrors.ustc.edu.cn/ubuntu focal InRelease
Hit:2 http://mirrors.ustc.edu.cn/ubuntu focal-updates InRelease
Hit:3 http://mirrors.ustc.edu.cn/ubuntu focal-backports InRelease
Hit:4 http://mirrors.ustc.edu.cn/ubuntu focal-security InRelease
Get:5 http://packages.ros.org/ros/ubuntu focal InRelease [4679 B]
Get:6 http://packages.ros.org/ros/ubuntu focal/main i386 Packages [59.5 kB]
Get:7 http://packages.ros.org/ros/ubuntu focal/main amd64 Packages [815 kB]
Fetched 879 kB in 7s (131 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
35 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

我看一下重新同步是否能解决问题。

**Comment by taoky** [comment]
经检查原因为同步配置于 5/25 删除了 i386 架构的同步。现在该架构已经重新添加，并且正在同步。

**Comment by taoky** [comment]
同步已完成。

**Comment by sdaheng** [comment]
👍感谢
