### ISSUE TITLE
freebsd-pkg sync error from status page.

### ISSUE THREAD

**Issue by yjqg6666** [ustclug/discussions#463]
### 问题描述 / Bug description

The syncing container timed out and was thus terminated.

**Comment by taoky** [comment]
https://github.com/ustclug/discussions/issues/458#issuecomment-2143381539

> 到上游的带宽只有一两百 KB/s

默认超时是 48 小时。考虑到带宽有限，等待重新同步完成即可。

**Comment by yjqg6666** [comment]
The other mirror sites can be used.
`dig +short _http._tcp.pkg.all.freebsd.org srv`

> 50 10 80 pkg0.syd.freebsd.org.
> 50 10 80 pkg0.sjb.freebsd.org.
> 50 10 80 pkg0.bbt.freebsd.org.
> 50 10 80 pkg0.nyi.freebsd.org.
> 50 10 80 pkg0.tuk.freebsd.org.
> 50 10 80 pkg0.jinx.freebsd.org.
> 50 10 80 pkg0.bme.freebsd.org.
> 50 10 80 pkg0.kul.freebsd.org.
> 50 10 80 pkg0.twn.freebsd.org.
> 50 10 80 pkg0.kwc.freebsd.org.
> 50 10 80 pkg0.fra.freebsd.org.
> 50 10 80 pkg0.bra.freebsd.org.
> 50 10 80 pkg0.fmt.freebsd.org.

reference: https://forums.freebsd.org/threads/how-to-change-mirror-in-pkg.79991/

**Comment by yjqg6666** [comment]
@taoky pkg0.jinx.freebsd.org 的速度国内还不错（1MB～5MB)，可以考虑换到这个上面来。

**Comment by yjqg6666** [comment]
2024Q3分支才出来，很多包有新版本构建更新，需要同步的量会比较多。

**Comment by taoky** [comment]
> @taoky pkg0.jinx.freebsd.org 的速度国内还不错（1MB～5MB)，可以考虑换到这个上面来。

我测试了其中一些，带宽都达不到 1M/s。由于 <https://servers.ustclug.org/2024/07/mirrors-maint/> 工作量较大，在迁移全部完成之后再考虑处理。

**Comment by taoky** [comment]
> The other mirror sites can be used. `dig +short _http._tcp.pkg.all.freebsd.org srv`
> 
> > 50 10 80 pkg0.syd.freebsd.org.
> > 50 10 80 pkg0.sjb.freebsd.org.
> > 50 10 80 pkg0.bbt.freebsd.org.
> > 50 10 80 pkg0.nyi.freebsd.org.
> > 50 10 80 pkg0.tuk.freebsd.org.
> > 50 10 80 pkg0.jinx.freebsd.org.
> > 50 10 80 pkg0.bme.freebsd.org.
> > 50 10 80 pkg0.kul.freebsd.org.
> > 50 10 80 pkg0.twn.freebsd.org.
> > 50 10 80 pkg0.kwc.freebsd.org.
> > 50 10 80 pkg0.fra.freebsd.org.
> > 50 10 80 pkg0.bra.freebsd.org.
> > 50 10 80 pkg0.fmt.freebsd.org.
> 
> reference: https://forums.freebsd.org/threads/how-to-change-mirror-in-pkg.79991/

> @taoky pkg0.jinx.freebsd.org 的速度国内还不错（1MB～5MB)，可以考虑换到这个上面来。

我今天对以上所有做了一次测速：https://gist.github.com/taoky/728fa5c2d6d0cef76d1f4449a990f30a

从结果上看，最快的也只有 1.2M/s 左右。

**Comment by yjqg6666** [comment]
试试其它域名呢？ 现在用的同步站点速度能到多少？ 看最近同步一直有问题。

**Comment by taoky** [comment]
> 试试其它域名呢？ 现在用的同步站点速度能到多少？ 看最近同步一直有问题。

测试结果是对所有 srv 查询结果提供的域名，使用电信、移动、联通、教育网线路分别测速，最快也就只有这么多。
