### ISSUE TITLE
ros kinetic源用不了

### ISSUE THREAD

**Issue by FlyHan** [ustclug/discussions#467]
### 问题描述 / Bug description

E: Failed to fetch https://mirrors.ustc.edu.cn/ros/ubuntu/pool/main/r/ros-kinetic-rviz/ros-kinetic-rviz_1.12.17-0xenial-20210503-142936-0800_amd64.deb  404  Not Found

实际打开网页显示，确实没有这个文件：

> Index of /ros/ubuntu/pool/main/r/ros-kinetic-rviz/
> ../
> ros-kinetic-rviz_1.12.17-0xenial.debian.tar.xz     30-May-2019 17:44               11944
> ros-kinetic-rviz_1.12.17-0xenial.dsc               30-May-2019 17:44                1674
> ros-kinetic-rviz_1.12.17.orig.tar.gz               30-May-2019 17:44             5082795

**Comment by taoky** [comment]
请提供 `/etc/apt/sources.list.d/ros-latest.list` 的内容以供排查问题。

**Comment by FlyHan** [comment]
源内容如下：

> deb https://mirrors.ustc.edu.cn/ros/ubuntu xenial main

另外使用清华源是可以的，网页查看里面内容也存在
https://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu/pool/main/r/ros-kinetic-rviz/

> Index of /ros/ubuntu/pool/main/r/ros-kinetic-rviz/
> Last Update: 2024-08-15 09:42
> File Name  ↓ 	File Size  ↓ 	Date  ↓ 
> Parent directory/	-	-
> ros-kinetic-rviz_1.12.17-0xenial-20210503-142936-0800_amd64.deb	2.1 MiB	2021-05-04 07:00
> ros-kinetic-rviz_1.12.17-0xenial-20210503-144133-0800_i386.deb	2.1 MiB	2021-05-04 07:06
> ros-kinetic-rviz_1.12.17-0xenial-20210507-051609-0800_arm64.deb	2.0 MiB	2021-05-08 01:04
> ros-kinetic-rviz_1.12.17-0xenial-20210507-174408-0800_armhf.deb	1.9 MiB	2021-05-08 13:43

**Comment by iBug** [comment]
由于 ros 上游没有提供 Rsync 等可靠的同步方式，因此我们使用 apt-sync 同步了**仍在受支持的** Ubuntu LTS 版本和 Debian 版本。Xenial（16.04）过于老旧，因此我们已不再同步该版本的软件包。

**Comment by iBug** [comment]
好像是有 `rsync://packages.ros.org/ros-main/` 这个服务的，托管在 OSUOSL，我来改一下同步方式吧

**Comment by iBug** [comment]
官方上游[有个符号链接的问题](https://discourse.ros.org/t/can-we-fix-rsync-for-packages-ros-org/2767)用不了，我们换到和 tuna 一样的上游 `rsync://mirror.umd.edu/packages.ros.org/ros/`，已补充同步完成。
