### ISSUE TITLE
需要移除镜像网站说明中的“最全”、“最大”字样

### ISSUE THREAD

**Issue by armnotstrong** [ustclug/discussions#468]
### 问题描述 / Bug description

![image](https://github.com/user-attachments/assets/1d5c2638-ec8d-44e4-88a7-38424b7254a6)
根据《[中华人民共和国广告法](https://www.gov.cn/guoqing/2020-12/24/content_5572939.htm)》第二章，第九条第三款之规定

> 广告不得有下列情形：
（三）使用“国家级”、“最高级”、“最佳”等用语；

并且，[mirrors.tuna](https://mirrors.tuna.tsinghua.edu.cn/status/#server-status)之收录数量与访问流量显然已经超过了mirrors.ustc。继续使用此描述已显不妥。

建议将描述改为

> 目前是中国大陆高校访问量较大，收录较全的开源软件镜像。

或将此描述直接删除。

**Comment by iBug** [comment]
> 第二条　在中华人民共和国境内，商品经营者或者服务提供者通过一定媒介和形式直接或者间接地介绍自己所推销的商品或者服务的商业广告活动，适用本法。

我们不「推销商品或者服务」，因此不适用广告法。

不过您的 issue 非常有趣，因此我们可将标签重新更正为 feature 😊

**Comment by taoky** [comment]
此外，我们提供的是非营利性的服务，而非商业服务，因此也当然没有发布过任何**商业**广告，不适用于《广告法》第二条的适用条件。

**Comment by Harry-Chen** [comment]
感谢您对 TUNA 镜像站的支持。TUNA 不认为此措辞存在不妥当之处。

**Comment by armnotstrong** [comment]
> 感谢您对 TUNA 镜像站的支持。TUNA 不认为此措辞存在不妥当之处。

这个问题不在于您觉得是否妥当，而在于是否实事求是。这句话当初写上是基于事实，现在应该去掉也是基于事实。

**Comment by taoky** [comment]
尽管我个人支持在后面添加「之一」，但是这里目前的状态已经不适合严肃讨论这个问题了。

如果文案有变化的话，会在这里更新。

**Comment by yaoge123** [comment]
感谢您对实际上可能[最全开源镜像站](https://mirror.nju.edu.cn)的隐式支持，但是NJU不认为USTC存在不妥之处。

**Comment by tiankaima** [comment]
Nevertheless, resolved with <https://git.lug.ustc.edu.cn/mirrors/mirrors-index/-/commit/3e74854ac02a627a015d496374237245037bffad>.

A PM might be preferred in such cases tho.
