### ISSUE TITLE
mirrors 硬件升级？

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#47]
专门开一个 issue 跟踪近期到中期的硬件升级问题。

之前我和 Aron Xu 谈过 Canonical 赞助 mirrors 服务器部分硬件（特指内存，起源是 Aron 安利 ZFS，但是 ZFS 是内存消耗大户），这件事情正在 C 社内部跟进，暂时没回音。

mirrors 年头也不小了，有必要更新其它硬件吗？如有，应该如何下手呢？不知道现在经费有多少。

**Comment by gaoyifan** [comment]
mirrors主要部件：

* CPU（E5620）
* RAM（4G×4）
* 磁盘阵列（a0,a1）
* 网卡（集成网卡）

CPU不是瓶颈，没必要升级。
内存C社管了。
磁盘阵列，价格不菲，经费估计不够用。
网卡，可以考虑加一块千兆卡。

**Comment by zhsj** [comment]
新买的话，用不着磁盘整列的。普通带多个硬盘槽的服务器就行了，然后上 ZFS。现在这种磁盘整列，过一层 raid 再上 ZFS 的话，都感觉不清真。

**Comment by gaoyifan** [comment]
@zhsj  同意新增一台存储服务器。 但不知道经费是否够用。

**Comment by Alkaid-Benetnash** [comment]
我也觉得买磁盘阵列不如买硬盘槽多的服务器
现在相当于有三条路

-  Canonical赞助内存（等着回邮件
- 找james谈谈升级硬件的事，看看网络中心能帮多少忙？（我下周找一趟james
- 在博客上发通知筹款买硬件（我先联系CFO把经费结余统计出来，如果网络中心帮不上多大忙，要以LUG名义发通知筹款

@bojieli 提供信息，买dell塔式服务器占地方但槽真的挺多，普通的12槽机器不算硬盘1w以内就下的来
@redsky0802 推荐京东4T红盘常年999，槽少但盘容量大性能好也不错。

**Comment by RiessarSadyx** [comment]
我就是2016届(本届)的CFO。
如果需要购买新硬件，我可以invoke一个赞助商，其愿意为我们提供2k~5k的赞助金额，而且该赞助商貌似表示很有意愿和我们LUG深入交流。

**Comment by zhsj** [comment]
我觉得买新硬件不是很急吧？而且 James 那边一般能支持的吧？

**Comment by Alkaid-Benetnash** [comment]
![image](https://cloud.githubusercontent.com/assets/9082286/20612462/15120caa-b2f5-11e6-99dd-a41b6e7bbd53.png)
新机器配置留档(from james)
服务器背后还有4个盘位，用两个做系统，剩下的放ssd #64

**Comment by gaoyifan** [comment]
@bg6cq 服务器可以增加一块SSD吗？

**Comment by gaoyifan** [comment]
update: TUNA赞助，mirrors内存增加至48GB。同时新服务器已到货。
