### ISSUE TITLE
Centos-Vault 无法通过Rsync 同步

### ISSUE THREAD

**Issue by sang8052** [ustclug/discussions#471]
### 问题描述 / Bug description

由于Centos7.x 终止了生命周期,但是我们公司的历史项目大规模使用了Centos7.x 。考虑到后续使用，需要同步Centos-Vault 到本地存储。但是执行 rsync rsync://rsync.mirrors.ustc.edu.cn 发现并没有 centos-vault 的同步项目。故此提出PR，恳请开放 rsync://rsync.mirrors.ustc.edu.cn/centos-vault 或者提供 rsync://rsync.mirrors.ustc.edu.cn/centos-vault/7.9.2009

**Comment by iBug** [comment]
我们在切换到 [rsync-proxy](https://github.com/ustclug/rsync-proxy) 的时候漏掉了 `centos-vault` module 的配置，现在已经补上了，请尝试

```shell
rsync rsync://rsync.mirrors.ustc.edu.cn/centos-vault/
```

**Comment by sang8052** [comment]
![image](https://github.com/user-attachments/assets/847ac0c4-08c4-44bb-9c9f-49d3af2cc60f)
已可正常同步，感谢您的帮助
