### ISSUE TITLE
镜像站完全不能访问

### ISSUE THREAD

**Issue by cokkiy** [ustclug/discussions#472]
### 问题描述 / Bug description

镜像站完全不能访问，网页和镜像均不能访问

**Comment by taoky** [comment]
请提供以下信息：

- 是否能正常访问 cernet.mirrors.ustc.edu.cn/chinanet.mirrors.ustc.edu.cn/unicom.mirrors.ustc.edu.cn/cmcc.mirrors.ustc.edu.cn/ipv6.mirrors.ustc.edu.cn
- nslookup mirrors.ustc.edu.cn 的输出
- ping mirrors.ustc.edu.cn 的输出

**Comment by taoky** [comment]
由于没有收到回复，此 issue 关闭。如果仍然有问题，欢迎回复相关的调试信息并 reopen。
