### ISSUE TITLE
广西地区电信网络无法访问

### ISSUE THREAD

**Issue by Rongxuan2022** [ustclug/discussions#473]
### 问题描述 / Bug description

![Screenshot_20240914_201556_org mozilla firefox](https://github.com/user-attachments/assets/5869e0ed-7929-4e54-8eae-f87a4543918f)
![Screenshot_20240914_194441_org mozilla firefox](https://github.com/user-attachments/assets/07dfe7b0-8ccf-45f5-9f0f-636f340359fe)
如图，分别为晚上8:15与7:44时访问

**Comment by iBug** [comment]
自 9 月 12 日以来我们收到大量恶意请求，占满了镜像站的电信出口带宽，请求来源遍布整个广西电信，因此 USTC 镜像站暂时不对广西电信用户服务。我们会持续观察镜像站情况，待恶意流量停止后再考虑恢复服务。

注：图中 9 月 14 日 0:30 左右流量下降原因是我们封禁了广西电信。

![image](https://github.com/user-attachments/assets/f766949e-f973-408b-9119-4ef84ca0004a)

![image](https://github.com/user-attachments/assets/a23a0248-148e-4d8e-a1bd-82bb42df9b54)

**Comment by iBug** [comment]
今天恶意流量基本消停了，解除了对广西电信的封禁，但保留了针对恶意流量的特征的封禁措施。
