### ISSUE TITLE
freebsd-pkg 源故障

### ISSUE THREAD

**Issue by ykla** [ustclug/discussions#476]
### 问题描述 / Bug description

目前安装任何软件，均提示 `missing or size mismatch, fetching from remote`，使用了相同脚本的南京大学开源镜像站亦如此。

查看镜像站文件似乎不太对，没有十月份的文件。

`https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD%3A15%3Aamd64/latest/All/` 与 `https://pkg.freebsd.org/FreeBSD%3A15%3Aamd64/latest/`

`https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD%3A14%3Aamd64/latest/All/`

上游 <http://kwc.freebsd.org/> 我也打不开。

**Comment by taoky** [comment]
```
============ SYNC STARTED AT 2024-10-07 01:23:05 ============
*********** 8< ***********
[INFO] getting version list...
curl: (28) Failed to connect to pkg0.kwc.freebsd.org port 80 after 135970 ms: Could not connect to server
[INFO] clean hash files
============ SYNC FINISHED AT 2024-10-07 01:25:38 ============
```

**Comment by ykla** [comment]
```
root@generic:~ # dig +short _http._tcp.pkg.freebsd.org srv
50 10 80 pkg0.nyi.freebsd.org.
50 10 80 pkg0.tuk.freebsd.org.
10 10 80 pkgmir.geo.freebsd.org.
50 10 80 pkg0.fra.freebsd.org.
50 10 80 pkg0.fmt.freebsd.org.
50 10 80 pkg0.sjb.freebsd.org.
```

上面是正常的。

**Comment by taoky** [comment]
Syncing from http://pkg0.nyi.freebsd.org now.

**Comment by ykla** [comment]
似乎 <https://mirrors.ustc.edu.cn/status/> 01:23:05	 报错就没有后续了

**Comment by taoky** [comment]
> 似乎 https://mirrors.ustc.edu.cn/status/ 01:23:05 报错就没有后续了

![image](https://github.com/user-attachments/assets/0b94569c-dc2f-48b0-852f-8216dddd1be1)

仍在同步（瓶颈是到达上游的网络带宽，见 <https://github.com/ustclug/discussions/issues/463#issuecomment-2227642229>）。

Patience is all you need.

**Comment by taoky** [comment]
截至目前 FreeBSD 15 的两个架构应该已经同步完成了，现在正在同步 FreeBSD 14 相关架构的包。

**Comment by ykla** [comment]
似乎还需要同步下 <http://pkg0.nyi.freebsd.org/FreeBSD:15:amd64/latest/> 这个路径下的 `data.pkg`、`data.txz`。

同 13、14

直接使用的话，会报错 `has no meta file, using default settings`。

**Comment by taoky** [comment]
> 似乎还需要同步下 http://pkg0.nyi.freebsd.org/FreeBSD:15:amd64/latest/ 这个路径下的 `data.pkg`、`data.txz`。
> 
> 同 13、14
> 
> 直接使用的话，会报错 `has no meta file, using default settings`。

同步脚本已更新，并重新开始同步。

**Comment by ykla** [comment]
FreeBSD 15.0 amd64 恢复正常。

**Comment by taoky** [comment]
![image](https://github.com/user-attachments/assets/bafca388-6dd4-4ae3-ba79-732ae64ffa4b)

**Comment by ykla** [comment]
请求将以下内容一并同步。以方便使用包管理器直接更新系统。大概每个路径各有 2GB。由于 15-CURRENT 是开发分支，变动频繁，可提高同步次数，其余版本根据 [wiki ](https://wiki.freebsd.org/PkgBase) 所述几乎是不变的，仅在大版本变动时才会更新。

| **分支** | **更新频率** | **URL 地址** |
| :---: | :---: | :--- |
| main（15.0-CURRENT） | 每天两次：08:00、20:00 | <https://pkg.freebsd.org/${ABI}/base_latest> |
| main（15.0-CURRENT） | 每周一次：星期日 20:00 | <https://pkg.freebsd.org/${ABI}/base_weekly> |
| stable/14 | 每天两次：08:00、20:00  | <https://pkg.freebsd.org/${ABI}/base_latest> |
| stable/14 | 每周一次：星期日 20:00 | <https://pkg.freebsd.org/${ABI}/base_weekly> |
| releng/14.0（RELEASE） | 每天两次：08:00、20:00 | <https://pkg.freebsd.org/${ABI}/base_release_0> |
| releng/14.1（RELEASE） | 每天两次：08:00、20:00 | <https://pkg.freebsd.org/${ABI}/base_release_1> |

**以上表格的时间为北京时间，即东八区时间。**

**Comment by taoky** [comment]
> 请求将以下内容一并同步。

由于最近有其他事项需要处理，可能最早也要到十一月中旬的时候才能处理这个。如果有兴趣的话，可以给 https://github.com/ustclug/ustcmirror-images 交 PR。
