### ISSUE TITLE
linux版 docker-ce 仓库缺少 GPG 公钥

### ISSUE THREAD

**Issue by jingjingxyk** [ustclug/discussions#477]
### 问题描述 / Bug description

发现报错：
![image](https://github.com/user-attachments/assets/26f4dfd7-2f02-4442-b54d-22d4d5b5ca22)

验证脚本
```shell

# https://github.com/docker/docker-install.git
# test -f get-docker.sh || curl -fsSL https://get.docker.com -o get-docker.sh

test -f get-docker.sh || curl -fsSLo get-docker.sh https://github.com/docker/docker-install/blob/master/install.sh?raw=true
# 或者
test -f get-docker.sh || curl -fsSLo get-docker.sh https://gitee.com/jingjingxyk/docker-install/raw/master/install.sh



sed -i.backup "s@https://mirrors.aliyun.com/docker-ce@https://mirrors.ustc.edu.cn/docker-ce@g; s@Aliyun)@ustc)@g " get-docker.sh

bash get-docker.sh --mirror ustc



```

检查结果：

| 镜像地址                                                            | 有无 GPG 公钥 |
|-----------------------------------------------------------------|-----------|
| https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian/gpg | 有         |
| https://mirrors.ustc.edu.cn/docker-ce/linux/debian/gpg          | 无         |
| https://mirrors.aliyun.com/docker-ce/linux/debian/gpg           | 有         |

**Comment by taoky** [comment]
相关问题已修复。

另：需要注意的是，从镜像站获取验证软件包完整性的公钥是存在安全性风险的（这也是我们所有的帮助文档中都只有从官方上游获取公钥的步骤的原因）。有关官方安装脚本的问题，详情参见上游 PR 的讨论 [<https://github.com/docker/docker-install/pull/444>](https://github.com/docker/docker-install/pull/444)。
