### ISSUE TITLE
Some package are missing on the hackage mirror

### ISSUE THREAD

**Issue by poscat0x04** [ustclug/discussions#478]
### 问题描述 / Bug description

For example the latest version of the `free` package, 5.2, is missing from the mirror:
https://mirrors.ustc.edu.cn/hackage/package/free-5.2/free-5.2.tar.gz returns 404 while
https://hackage.haskell.org/package/free-5.2/free-5.2.tar.gz returns 200

This is quite weird considering that version was released over a year ago.

Edit: found another one missing: fingertree-0.1.5.0 :/

**Comment by taoky** [comment]
But <https://mirrors.ustc.edu.cn/hackage/package/free-5.2.tar.gz> exists.

I'm not a haskell user so I'm not sure what's happening. Maybe there's an issue with <https://github.com/ustclug/ustcmirror-images/blob/master/hackage/sync.sh>?

**Comment by taoky** [comment]
Also, could you provide a MRE for this case? I tried with stack creating a project, adding `free` in `dependencies` locally and it does not seem to have any issue.

**Comment by poscat0x04** [comment]
Weird, I can no longer reproduce errors by running `cabal build` :/ Maybe it was caused by some inconsistent cache state?

I guess since this does not seem to affect the the usage of cabal I'll close it by now.
