### ISSUE TITLE
wget 返回 403

### ISSUE THREAD

**Issue by xclid** [ustclug/discussions#479]
### 问题描述 / Bug description

- 问题现象：
```
wget https://mirrors.ustc.edu.cn/ubuntu-cloud-images/noble/current/noble-server-cloudimg-amd64.img
--2024-11-25 16:28:21--  https://mirrors.ustc.edu.cn/ubuntu-cloud-images/noble/current/noble-server-cloudimg-amd64.img
Resolving mirrors.ustc.edu.cn (mirrors.ustc.edu.cn)... 202.141.160.110, 2001:da8:d800:95::110
Connecting to mirrors.ustc.edu.cn (mirrors.ustc.edu.cn)|202.141.160.110|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-11-25 16:28:21 ERROR 403: Forbidden.
```
- 环境：debian12.8
- IP:27.25.156.X

用 PC 浏览器尝试可以正常下载但之前加了一道验证
```
Verifying your browser

Additional verification is required for this file you requested.

This page requires JavaScript. Please wait for a few seconds.
```

IP在机房，家里最近也存在同样的403

**Comment by taoky** [comment]
由于恶意的占用流量的访问猖獗，我们部署了一些规则对存在大量访问的客户端进行封禁，其中包括了一部分 wget 版本的 UA。

作为替代，请在使用 `wget` 时使用 `--user-agent` 额外添加 user agent 配置，将 UA 替换为能反映您下载意图或所在组织机构的字符串，以便识别。

**Comment by enihsyou** [comment]
BusyBox 中的 wget 默认使用的 User-Agent 值是单纯的 `Wget`，在此环境中（比如 Alpine 容器）使用 wget 访问 mirrors.ustc.edu.cn 下资源会以 403 响应。

需使用 `wget -U wget.` 设置一个其它 User-Agent，既然如此简单能绕过，还有必要拦截吗

**Comment by iBug** [comment]
> 既然如此简单能绕过，还有必要拦截吗

有必要。

会绕过的人是少数，不拦截的话镜像站一天 24 小时都在伺候垃圾流量，拦截的话起码你动动手加个参数之后还有得用。希望您能理解镜像站每天服务约 **50% 的请求数**是顶着类似 UA 反复下载 ISO 等大文件时所采取的必要措施。
