### ISSUE TITLE
proxmox 镜像

### ISSUE THREAD

**Issue by wy414012** [ustclug/discussions#480]
### 问题描述 / Bug description

proxmox 镜像服务器统计的大小可能有错误，服务器状态显示
![image](https://github.com/user-attachments/assets/b12950cc-6d07-40e5-82c5-34202b9cc174)
，实际在我同步完成后有
![image](https://github.com/user-attachments/assets/bf8ff82c-1779-4e5d-ba7a-85f3019eb83e)

**Comment by wy414012** [comment]
补充：已使用du -sh 检查镜像存储目录
```bash
/home/mirrors/update/proxmox# du -sh
434G    
```
是否是因为我同步参数原因?
使用同步参数：
```bash
rsync -azv --delete rsync://rsync.mirrors.ustc.edu.cn/proxmox/ /home/mirrors/update/proxmox
```

**Comment by wy414012** [comment]
[proxmox.sync.log.tar.gz](https://github.com/user-attachments/files/18050798/proxmox.sync.log.tar.gz)
完整的同步日志

**Comment by wy414012** [comment]
调查完成 由于`.~tmp~`目录 被我的统计工具给统计进去了!在同步时候导致写入了输出日志，删除原始失败的目录下的`.~tmp~`后重新执行一次同步指令 已恢复正常。

**Comment by iBug** [comment]
另：推荐您同步 Proxmox 的时候使用 `rsync -H`（i.e. preserve hard links）。由于 Proxmox 仓库内文件重复率高，所以我们在同步完之后会进行用户态去重，将重复的文件替换成 hard link，这也是我们的 Proxmox 仓库容量较小的原因（可以参考[我在南京大学分享的 slides](https://ibug.io/blog/2024/08/nju-talk/#/jdupes-table)）。
