### ISSUE TITLE
Restrict storage-googleapis.proxy.ustclug.org

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#53]
Previously discussed.
Google Cloud Storage has UGC(User Generated Content).

**Comment by gaoyifan** [comment]
@zhsj  有什么好办法吗？ 要不直接放弃google storage的代理？

**Comment by zhsj** [comment]
@gaoyifan 用白名单限制第一级目录名就可以了

**Comment by gaoyifan** [comment]
@zhsj  到哪弄这么一个白名单呢？分析日志么

**Comment by zhsj** [comment]
当然是找当初要设这么一个反代的原因啊。。。
比如 https://lug.ustc.edu.cn/wiki/mirrors/help/aosp 这里记录了 git-repo-downloads

**Comment by zhsj** [comment]
已关闭

由于从来没有对外宣传过 storage-googleapis.proxy.ustclug.org 的服务，所以关闭也不再进行公告。
