### ISSUE TITLE
Mirrors Service Outage

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#54]
从 Ganglia 监控可以看到，昨天一天 Mirrors 流量都不正常。

首先，希望可以明确是不是 bcache 造成的 IO、负载异常。如果是，在我们没有解决 bcache 问题的情况下，希望可以立即拆除 bcache。
如果有人有能力解决 bcache 的问题，请给出解决的 deadline。

以下讨论如何拆除 bcache：

1. 是否格式化
    不格式话，请给出具体的方法
2. 格式话的话，数据如何迁移
     中转设备如果 james 那边没有的话，可以找 tuna 把上次的硬盘再寄过来
     另外是否有比通过 Mirrors 网口传输数据更可行的方法

**Comment by bojieli** [comment]
为什么需要格式化？

首先 ls -l /sys/fs/bcache/ 找出 UUID

echo $UUID> /sys/block/bcache0/bcache/detach

验证：
$ cat /sys/block/bcache0/bcache/state
no cache

这样可以吗？

2016-11-13 1:01 GMT+08:00 zhsj <notifications@github.com>:

**Comment by zhsj** [comment]
@bojieli 
这样我的理解是把bcache置于不缓存的工作模式，但访问依旧是经过bcache设备的。

**Comment by bojieli** [comment]
@zhsj

From https://www.kernel.org/doc/Documentation/bcache.txt:

D) Recovering data without bcache:

If bcache is not available in the kernel, a filesystem on the backing
device is still available at an 8KiB offset. So either via a loopdev
of the backing device created with --offset 8K, or any value defined by
--data-offset when you originally formatted bcache with `make-bcache`.

For example:
losetup -o 8192 /dev/loop0 /dev/your_bcache_backing_dev

This should present your unmodified backing device data in /dev/loop0

If your cache is in writethrough mode, then you can safely discard the
cache device without loosing data.

**Comment by Alkaid-Benetnash** [comment]
已经使用内核文档中提到的方法关闭bcache并挂载backing device到loop #49 
此外发现了其他的问题，外部阵列的第一个raid6现在读取速度在500KB/s-30MB/s之间极不稳定，而另一个raid6稳定在100MB/s
我猜测与外部阵列坏盘相关，今天ID:1的希捷盘又出media error了，但还没有到failure然后rebuild的程度
所以说今天的问题不能全怨bcache（虽然它现在已经被关闭了）
现在可以测试测试是否不用bcache就不会出现进程全部D住的现象。

PS：要注意监测裸raid6的读性能

**Comment by zhsj** [comment]
在 Rebuild 的是哪个磁盘啊？

![image](https://cloud.githubusercontent.com/assets/227180/20257348/f82c10f0-aa83-11e6-9cba-4c5704a3b398.png)

sde 负载明显高于其他两个，另外 sde 上还有 bcache ？不过并没有对于的 ssd 磁盘。

![image](https://cloud.githubusercontent.com/assets/227180/20257372/25d37b2e-aa84-11e6-8474-0a82c53dd66b.png)

是不是把 sde umount 掉，把流量转移到 TUNA 比较好啊？

**Comment by Alkaid-Benetnash** [comment]
> 在 Rebuild 的是哪个磁盘啊？
> sde 负载明显高于其他两个，另外 sde 上还有 bcache ？

在Rebuild的是sde，bcache我也不知道怎么回事，我才是因为fstab里写的是bcache的UUID，我现在已经把这两行bcache注释掉了，重启想着手动挂下loop

> 不过并没有对于的 ssd 磁盘。

 sdb sdc就是ssd啊
