### ISSUE TITLE
GitLab内存不足

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#56]
近日经常收到邮件：

```
Target: gitlab Previous Status: Green New Status: Yellow

Alarm Definition: ([Yellow metric Is above 85%; Red metric Is above 95%])

Current values for metric/state:

Metric Memory Usage = 90%
Description: Alarm ‘Virtual machine memory usage’ on gitlab changed from Green to Yellow
```

建议:

1. swarm.s.u.o 新增一块虚拟磁盘（或者直接用nfs作docker后端存储）
2. swarm.s.u.o扩容到8GB RAM
3. 将gitlab.s.u.o与swarm.s.u.o合并

**Comment by bojieli** [comment]
这个给 gitlab 加内存的提议有什么进展吗？

今天 4:28 从校内 IP git pull 一个仓库，用了 10 分钟才 pull 下来，其中前5分钟在 compress，后5分钟在传输，传输数据量只有 200 MB。从下面的 ganglia load 和 network 图也可以看出。

https://status.ustclug.org/?r=hour&cs=12%2F13%2F2016+04%3A20+&ce=12%2F13%2F2016+04%3A40+&m=load_one&s=by+name&c=gitlab&h=&host_regex=&max_graphs=0&tab=m&vn=&hide-hf=false&sh=1&z=small&hc=4

原因可能是（1）内存不足（2）磁盘过慢。（磁盘过慢的问题另开一个 thread）

**Comment by gaoyifan** [comment]
很可能是内存不足。目前可用内存稀少，且大量使用swap。
vSphere改成bcache后，磁盘速度还不错。

要说进展嘛，vCenter坏了后一直没人修(#61)。所以，给GitLab加内存就变得比较麻烦了。

**Comment by zhsj** [comment]
@gaoyifan gitlab这种服务既然使用率很高，又是耗资源的，应该转移回网络中心的服务器上，让网络中心提供更多资源，并把gitlab上升到校级服务，并非lug服务。毕竟现在gitlab校内很多实验室在用（也许，有数据能说明更好）。

**Comment by gaoyifan** [comment]
@zhsj  之前@knight42 曾经尝试将gitlab迁移到docker2，以缓解内存压力，不知道进展如何。

如果真打算变成校级服务，可以考虑申请一个xxx.ustc.edu.cn的域名，再询问一下张老师能否新增一个虚拟机。 @bg6cq

**Comment by knight42** [comment]
并没有多大进展... 正在沉迷汇编/编译 ...

我支持让 gitlab 变成校级服务. 一来减少我们的机器负担, 二来也算是扩大知名度. 现在 gitlab 的使用人数还是挺多的
![2016-12-13-172654_1292x231_scrot](https://cloud.githubusercontent.com/assets/4237254/21134569/7d10d120-c159-11e6-9d49-aa81337593be.png)

**Comment by bojieli** [comment]
支持 @zhsj 

看到 @knight42 的数据还是很 exciting 的，我们 GitLab 竟然有这么多用户了。

谁去给张老师发个邮件问问？

**Comment by gaoyifan** [comment]
其实服务器也没有多大压力。
我们的用户中有60%没有创建过任何仓库，
活跃用户（1个月内有一次活动）少于130人，
1个月内更新过的仓库不足90个。

我印象中，前年将GitLab移交给 @knight42 时，用户数大约是1100人。

本来想统计一下登录IP地址，看看科大用户有多少，结果发现IP地址全是 10.254.0.252 -_-//

**Comment by gaoyifan** [comment]
下午与张老师讨论了一下。张老师表示支持将gitlab作为校级服务，可以提供给我们一台虚拟机用于运行gitlab。

**Comment by gaoyifan** [comment]
@knight42  建议将虚拟机整体迁移至esxi-5

**Comment by knight42** [comment]
已将 gitlab 迁移至 esxi-5
