### ISSUE TITLE
LUG FTP `LIST` 操作超时

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#62]
如题。握手正常，可`PASV`进入被动模式，但是`LIST`操作无响应直到超时。

**Comment by gaoyifan** [comment]
我这边测试是正常的：

![screen shot 2016-11-24 at 11 16 29 pm](https://cloud.githubusercontent.com/assets/5450996/20603352/27fe7410-b29c-11e6-9127-1a5214fb90d7.png)

要不直接切换到sftp吧，ftp协议太古老了，映射端口也比较坑。issue: #50

**Comment by hosiet** [comment]
![_078](https://cloud.githubusercontent.com/assets/8443926/20603505/c090b670-b29c-11e6-91d7-96abb33fa588.png)

切换到 sftp 和仍然使用 FTP 应该不冲突。

**Comment by gaoyifan** [comment]
能提供两端的抓包记录吗？ 我这边无法复现。

**Comment by hosiet** [comment]
@gaoyifan 我不知道怎么登录 ftp 所在服务器。另，本地显示抓包到发送 LIST 后就没反应了，直接20秒超时。同理，EHLO 之后发 AUTH TLS 也会无反应直到超时。

**Comment by gaoyifan** [comment]
@hosiet 
LUG FTP位于docker2 (https://github.com/ustclug/documentations/blob/master/services/ftp/README.md).

需要先连接LUGI VPN.

**Comment by hosiet** [comment]
[lugftp_client_filezilla.pcapng.txt](https://github.com/ustclug/discussions/files/611700/lugftp_client_filezilla.pcapng.txt)

**Comment by hosiet** [comment]
@gaoyifan docker 母鸡网络太乱，不知道该监听哪个设备🌚网卡怎么调成 monitor mode🌚以及 tshark 不太会用🌚

**Comment by gaoyifan** [comment]
@hosiet tcpdump监听eth1

**Comment by gaoyifan** [comment]
经调试发现：docker2中未配置基于连接的策略路由，导致数据包从错误的出口发送出去。因此，返回的数据包被外部网关的源路由检查丢弃了。

校内主机之所以能正常连接ftp，是由于校内的网络设备没有源路由检查。

解决方法：为docker2配置基于连接的源路由检查(iptables mark + ip rule).  
有人想试试吗？可以参考gateway-el

**Comment by gaoyifan** [comment]
fixed
