### ISSUE TITLE
backup失联

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#63]
开个issue用于追踪backup的故障情况

**Comment by bojieli** [comment]
backup 是少院机房一台独立的物理机吧？现在少院网络应该是正常的，怎么就失联了？

**Comment by gaoyifan** [comment]
@Alkaid-Benetnash ?

**Comment by Alkaid-Benetnash** [comment]
那天去了一趟机房，断网了，ldap和root密钥都用不了，可能是我更新包导致的，没带livecd，我今天再去一趟
(机房钥匙不在我这了，我只能晚上等机房开跳进去)

**Comment by gaoyifan** [comment]
@Alkaid-Benetnash  如果依赖问题不好解决，可以考虑升级到DebianStretch

BTW, 求教，如何跳进少院机房？

**Comment by Alkaid-Benetnash** [comment]
> @Alkaid-Benetnash 如果依赖问题不好解决，可以考虑升级到DebianStretch

就是升到了Stretch

> BTW, 求教，如何跳进少院机房？

如果外面的大机房（网吧）开了的话，可以从靠近主控室的那个窗户跳进去，注意脚下的内存和硬盘。

**Comment by Alkaid-Benetnash** [comment]
done
live-cd进去拿root
发现是上次卡死在安装包的阶段，dpkg --reconfigure -a 继续安装新内核，重启就没问题了
