### ISSUE TITLE
Wiki 历史记录疑似丢失

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#65]
各个页面旧的历史都无法打开了

![image](https://cloud.githubusercontent.com/assets/227180/20616479/848d7d08-b31d-11e6-8cc6-b95ff3f6f396.png)

只有前三条（大概10月份之后的）能打开

**Comment by gaoyifan** [comment]
不太清楚wiki记录历史的原理...  
无论是docker化前，还是docker化后，git中都没有早期的提交记录

**Comment by hosiet** [comment]
@gaoyifan 历史是否在转换为 git 管理时丢失？

**Comment by gaoyifan** [comment]
@hosiet  不太清楚呢~  我没有改过git插件

**Comment by gaoyifan** [comment]
来自 #116 。 @zhsj  安装php5-zip后没有任何起色。

**Comment by gaoyifan** [comment]
@zhsj  多谢！https://github.com/ustclug/lugwiki/commit/390194df2605d2604a26077a22255740cfc8ad1a

**Comment by zhsj** [comment]
![image](https://cloud.githubusercontent.com/assets/227180/24717747/173402ee-1a66-11e7-84ce-8b1504fc4d01.png)

然后那些没有 gzip 的就看不了了。。。。。
手动去 gzip 下？

**Comment by gaoyifan** [comment]
😝
