### ISSUE TITLE
考虑停止解析 debian.ustc.edu.cn

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#66]
如题。

近期不太可能。但应该考虑先发通知出去，适当时机处理这个问题。

* * *

事件备忘：

- [x] <立即>发布公告：域名调整计划
- [x] <立即>设置301跳转
- [x] <立即>通知网络信息中心
- [x] <立即>通知centos调整域名
- [x] <2017.7> 关闭rsync
- [ ] <2018.1> 停止解析

**Comment by gaoyifan** [comment]
为了降低维护难度吗？

**Comment by hosiet** [comment]
@gaoyifan 这个域名不方便部署 https 证书，也不可控，无法在必要时候切换解析，所以最好是早日停止使用。

**Comment by gaoyifan** [comment]
@hosiet debian.ustc.edu.cn CNAME到了mirrors.ustc.edu.cn，是随mirrors.u.e.c同步切换的。
HTTPS的确是个麻烦事.....

**Comment by zhsj** [comment]
@hosiet https可以用le证书。。。。

**Comment by gaoyifan** [comment]
1. 在servers.u.o发布公告：debian.u.e.c即将弃用。HTTP设置301跳转。
2. 将debian.u.e.c解析到其他IP。HTTP继续跳转。rsync停止服务器，返回通知。
3. 彻底废弃

我们订个时间表？ @hosiet

**Comment by hosiet** [comment]
个人建议

1. 立即，同时向网络中心发一封邮件
2. 六个月以后
3. 十二个月以后

补充：同样适用于 centos.ustc.edu.cn

Yifan Gao <notifications@github.com>于2016年11月26日周六 12:13写道：

**Comment by gaoyifan** [comment]
赞成~  我觉得可以立即开始实施~

**Comment by hosiet** [comment]
这个事情要推动一下。准备发通知，域名包括：

* oss.ustc.edu.cn
* debian.ustc.edu.cn
* centos.ustc.edu.cn

**Comment by gaoyifan** [comment]
是否需要给debian、centos上游发个通知？

**Comment by gaoyifan** [comment]
事件备忘：

- [x] <立即>发布公告：域名调整计划
- [ ] <立即>通知网络信息中心
- [ ] <立即>通知centos调整域名
- [ ] <2017.7> 关闭rsync
- [ ] <2018.1> 停止解析

**Comment by gaoyifan** [comment]
刚看了下iso安装debian，network mirrors list中还是debian.ustc.edu.cn

**Comment by zhsj** [comment]
debian 上游应该前期都通知过了，估计 ISO 那边生效要很久。

**Comment by hosiet** [comment]
@zhsj 安装器（debian-installer）是单独团队负责的，有可能需要单独提醒。能否给出具体位置（例如截图）？

**Comment by zhsj** [comment]
@hosiet 那确实没和 debian-installer 联系过，只修改过 ftp-master 那边的信息，然后就是最近和 syncproxy2.wna.d.o 的。

**Comment by gaoyifan** [comment]
centos.ustc.edu.cn似乎可以直接CNAME给ctos.ustc.edu.cn

**Comment by zhsj** [comment]
@gaoyifan 这个issue提出 @hosiet 是希望 *停止* 解析吧。。。 CNAME到 ctos.ustc.edu.cn 和 CNAME 到 mirrors.ustc.edu.cn 又有何区别。。。

**Comment by hosiet** [comment]
@gaoyifan 能不能给一下 iso 中的具体位置呢？我在 debian-installer 源代码里面没找到相关字符串

**Comment by StephenPCG** [comment]
@hosiet 这个代码不在 d-i 里面，而是在 choose-mirror 这个 udeb 里面。

jessie 中的 choose-mirror udeb 的版本是 2.62 （下载 [jessie的udeb.list](http://mirrors.ustc.edu.cn/debian/dists/jessie/main/installer-amd64/current/images/udeb.list) 可以查看到。）

choose-mirror 的源码在：https://anonscm.debian.org/cgit/d-i/choose-mirror.git/tree/
也可以git clone获取：git://anonscm.debian.org/d-i/choose-mirror.git

我搜索了一下debian.ustc.edu.cn：
```
git log -S debian.ustc.edu.cn
commit 39597768ca40b35b448024c4f214e03ecb2c0c19
Author: Cyril Brulebois <kibi@debian.org>
Date:   Wed Oct 19 02:11:25 2016 +0200

    Update Mirrors.masterlist

commit f72e756a86e81db9f261283d065ef5581adf90ba
Author: Cyril Brulebois <kibi@debian.org>
Date:   Sat Oct 12 17:03:45 2013 +0200

    Start tracking Mirrors.masterlist instead of only including it when building the source package.
    
    - Sync it as of 2013-10-12.
    - Remove it from .gitignore accordingly.
```

进一步通过 ``git show 39597768ca40b35b448024c4f214e03ecb2c0c19`` 确认，在2016年10月19日的这一次commit中已经移除了debian.ustc.edu.cn。然而，通过查看 debian/changelog 发现 2.62是2015年4月14日发布的，因此，在jessie的安装中，确实有debian.ustc.edu.cn。

**Comment by gaoyifan** [comment]
@hosiet  ISO: http://mirrors.ustc.edu.cn/debian-cd/8.6.0/amd64/iso-cd/debian-8.6.0-amd64-CD-1.iso

<img width="800" alt="debian m u e-1" src="https://cloud.githubusercontent.com/assets/5450996/21918657/97b396be-d98e-11e6-8ab4-fa2563f19c3e.png">
<img width="799" alt="debian u e c-2" src="https://cloud.githubusercontent.com/assets/5450996/21918658/97bf247a-d98e-11e6-89a6-9fed4f8e9a30.png">

**Comment by zhsj** [comment]
ISO的更新估计要debian发下一个版本了，也许 8.7，也许直接 9（

**Comment by zhsj** [comment]
centos 有人联系了吗？

**Comment by StephenPCG** [comment]
看了一下前面的讨论，停止解析似乎最主要的原因就是https。我觉得这似乎不是一个必须要“停止解析”的理由。这个域名我们从来没有宣传过支持https，因此它不支持https也无所谓。

我觉得：

* 存量用户，往往都是写在配置文件里的（sources.list），这些用户可能不知道我们要打算弃用debian.u.e.c这个域名，即使我们发了通告也不一定会发现（可能都不记得自己曾经在配置文件中写过这个域名，以为写的是mirrors.u.e.c）。
* 新用户/通过浏览器访问的用户，我觉得在访问时，给一个页面提示跳转，然后跳转到mirrors就行了。

具体操作上，我建议搞一个nginx，把所有我们过期的域名都解析到这个nginx上。当有浏览器访问一个我们启用的域名时，显示一个页面，给出迁移的提示，等待约5秒后跳转到新的地址（或合适的地方），当有工具访问时（比如apt），我们尽可能提供正确的302，尽可能让工具仍然可以继续工作。

**Comment by zhsj** [comment]
@StephenPCG 但联系上游更新域名的事情还是要做，并不冲突。。。至于怎么给旧域名提供兼容性，这个可以等正式放弃使用时再讨论。

**Comment by StephenPCG** [comment]
@zhsj 通知上游的事情是要继续的。

**Comment by hosiet** [comment]
fix blocking by ustclug/mirrorhelp#53

**Comment by gaoyifan** [comment]
@hosiet  2018年1月已经到了。是不是可以继续推进一下？

**Comment by hosiet** [comment]
可以。

需要找 @bg6cq 张老师商量一下 debian.ustc.edu.cn 停止解析的问题……或者 CNAME 会不会更好？

**Comment by gaoyifan** [comment]
@hosiet  目前就是CNAME

**Comment by zhsj** [comment]
我建议再等待几个月，但我们现在开始，停止 debian.ustc.edu.cn 提供内容，仅提供一个停止服务的说明页面。这样这几个月里，用户运行 apt 等命令就会出错。
只有真正造成用户无法使用，他们才会意识到需要采取措施。相比于我们只发个公告来说，好的多。

**Comment by iBug** [comment]
再挖一铲，Debian Jessie 已经抛弃一年多了，Stretch 里面的 choose-mirror 2.79 也没有 debian.ustc.edu.cn 了，CentOS 6 也不用管了，CentOS 7 似乎没有在软件包里写死 mirror 列表而是动态获取的。也就是说我们现在可以放心申请停止解析旧域名了

**Comment by iBug** [comment]
Aug 5, 2021: `debian`, `debian6`, `oss`, `oss6` 已 404 并返回 text/html:

> We have moved to mirrors.ustc.edu.cn for many years. Update your system settings now!

`centos` 目前 301，过段时间改 404，如果这批域名 404 一段时间（比如半年）之后没人开 issue 的话就可以停止解析了。

**Comment by iBug** [comment]
根据 8 月 5 日的 301 统计结果，现在 `mirrors[12346]` 也开始 404 了

```
      15  mirrors3.ustc.edu.cn
      34  mirrors4.ustc.edu.cn
       5  mirrors6.ustc.edu.cn
   11102    centos.ustc.edu.cn
      19  mirrors1.ustc.edu.cn
      10  mirrors2.ustc.edu.cn
   11185                $total
```

**Comment by iBug** [comment]
根据内部群聊天记录，这几个域名的解析已经在 2023-05-17 请张老师移除，mirrors 上的相关域名配置也删除了。
