### ISSUE TITLE
gateway-el磁盘空间耗尽

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#69]
![screen shot 2016-11-30 at 10 44 02 pm](https://cloud.githubusercontent.com/assets/5450996/20756679/8df93f64-b74e-11e6-8af9-2c71d974dba0.png)

大部分空间被日志占用，建议将logrotate周期改为1小时。

上次发生类似事件 #38

**Comment by knight42** [comment]
已经修改 logrotate 配置, 改为 hourly

**Comment by gaoyifan** [comment]
logroutate由cron触发....   而cron是每日任务.....

**Comment by knight42** [comment]
我把 logrotate 移到 cron.hourly 里了 (不是很明白为什么最小间隔是 hour, 却放到 cron.daily 里)
