### ISSUE TITLE
dirperm1 breaks the protection

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#7]
```
Aug 24 17:10:05 mirrors kernel: [35882343.990374] aufs au_opts_verify:1570:dockerd[1948]: dirperm1 breaks the protection by the permission bits on the lower branch
```

**Comment by gaoyifan** [comment]
建议切换至devicemapper @knight42

**Comment by knight42** [comment]
看上去是 kernel 的锅: https://github.com/docker/docker/issues/13940, https://github.com/docker/docker/issues/21081 .

不如最近筹划一次重启, 顺便升级下内核, 加上 bcache?

**Comment by gaoyifan** [comment]
打算升级到哪个版本呢？

**Comment by knight42** [comment]
唔... debian 的内核版本比我想像中的稳定... 那就重启顺便加上 cgroup 参数?

**Comment by gaoyifan** [comment]
顺便重新编译一个内核吧，现在的内核私钥丢了。

**Comment by gaoyifan** [comment]
已切换至overlayfs2
