### ISSUE TITLE
防污染DNS邮件列表

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#70]
近期，多位用户通过多种渠道询问防污染DNS的服务状况。

我们是不是考虑增加一个邮件列表，转发servers.u.o中的相关通知？

大家觉得有必要吗？

**Comment by zhsj** [comment]
防污染DNS的用户群是谁？给校外使用的话，为啥在 servers.u.o 上仅校内可见？

**Comment by gaoyifan** [comment]
之前Amamiya提到防污染DNS风险比较大，因此我将公开的页面都设置为校内访问了，以免搞出个大新闻。
邮件列表也是对用户的一种筛选，不像公开页面这样树大招风。

**Comment by ChizuruAmamiya** [comment]
阿里云上搭建公共防污染DNS，有被阿里云暂停主机服务的先例，所以当时确实是出于善意提醒了一下Yifan, 其实如果想知道服务地址的话，archive.org上就有（可以追踪到3月的记录）。

**Comment by gaoyifan** [comment]
https://groups.google.com/d/forum/neat-dns

**Comment by hosiet** [comment]
@gaoyifan 喂喂，这个名字太宽了吧，不是很适合的感觉

**Comment by gaoyifan** [comment]
@hosiet 有什么建议吗？

不知道还能不能改....

**Comment by ChizuruAmamiya** [comment]
呃，USTC-Neat-DNS?
