### ISSUE TITLE
考虑给 GitLab 使用纯 SSD 数据盘

### ISSUE THREAD

**Issue by bojieli** [ustclug/discussions#75]
GitLab 上的 git 仓库容量应在 200G 以下，git 仓库的访问经常会涉及大量小文件。现在 512G SSD 的价格在千元左右，如果使用纯 SSD 数据盘并且本地挂载（即不通过 NFS），可能会显著提高大 git 仓库访问的性能。大家有什么看法？

**Comment by gaoyifan** [comment]
好主意，我们可以搞台纯SSD的docker宿主。

**Comment by bojieli** [comment]
@gaoyifan 如果我们的 dm-cache 性能足够好，也就是对热数据能够发挥出 SSD 的高随机 I/O 性能的话，我同意你的观点。

我主要担心的是两点，（1）通过 NFS 挂载，NFS 是否会成为瓶颈；（2）dm-cache 在 cache hit 的情况下，是否能够充分发挥出 SSD 的随机 I/O 性能。我们可以做一些 benchmark。

**Comment by gaoyifan** [comment]
@bojieli 202.38.93.205的架构与LUG集群的架构是完全一样的(vsphere+nfs+bcache)，可以在icourse上测试.

**Comment by bojieli** [comment]
@gaoyifan Thanks!

上次测试发现随机读性能 2800 次每秒，连续读性能 80 MB/s。不过 @gaoyifan 指出 SSD 的随机读性能只有 2000 次每秒。这是由于 dm-cache 层在内存里有缓存，因此没有真正测到 SSD 的速度。由于 fio 总要先写一遍测试文件，没办法在不爆内存的情况下绕过内存缓存。有一种办法是随机读裸的磁盘（/dev/sda），基本上不太可能在缓存里，不知道工具是否支持。不管是不是由于内存缓存的原因，既然能够达到比裸 SSD 盘更高的读性能，自然是更好的。

连续读 SSD 本来应该是 200 MB/s 以上，实测 80 MB/s 是因为使用网络挂载，被千兆网卡 bound 住了。gitlab 应该不需要很快的连续读。

**Comment by gaoyifan** [comment]
@bojieli  那就暂时不需要纯SSD的服务器了。
另外，张老师同意提供一台8G的虚拟机用于Gitlab。这个issue先关了...
