### ISSUE TITLE
是否可以把 icourse.club 迁移到 LUG 集群

### ISSUE THREAD

**Issue by bojieli** [ustclug/discussions#76]
icourse.club（评课社区）网站现运行在 sonnie 在图书馆的虚拟机上。之前 QQ 讨论组讨论过该网站迁移到 LUG 服务器的可行性，不过后来没有跟进。

该虚拟机只有单核 1 GB 内存（8G swap），而且硬盘较慢。访问某些页面的时候由于需要数十个 SQL 查询，页面打开时间是秒级的。平时这 1G 内存是够用的。不过导入数据的时候，由于内存不足和硬盘较慢，在笔记本上只需运行15分钟的导入脚本，在服务器上需要运行数小时，甚至可能由于内存不足而导入失败。（之前的做法是我把数据库下载到笔记本上，导入完再上传回去，希望这个过程中没人更新数据库）此外，该网站缺少定期备份机制。

VMWare 应该支持动态分配内存，即虚拟机释放的内存可以回到宿主机的资源池中。如果可以，该虚拟机将仅在导入数据时占用较多内存，在导入完成后自动释放。

图书馆应该是没有基于 SSD 的虚拟机，而且不便动态分配内存。

不知道各位是否考虑把评课社区作为一项 LUG 网络服务（其实是我想从 LUG 搞一台配置好点的虚拟机，然后如果谁感兴趣的话就把这个锅甩出去……）

目前该网站 MySQL 数据库 431 MB，所有数据 2.3 GB，而且增长速度较慢，不会消耗很多存储资源。Python 3 的 web server 原则上说是可以放在 docker 里面的，但为了导入数据的方便，我觉得虚拟机更省事一些。

迁移过程不会很复杂，给个 base system 我就可以搞定。备份用 mysqldump + rsync 就行，跟 blog 一样。

**Comment by gaoyifan** [comment]
![screen shot 2016-12-13 at 10 01 10 am](https://cloud.githubusercontent.com/assets/5450996/21124653/2397cfe2-c11b-11e6-9d35-177cad3b503e.png)
查了一下vSphere虚拟机的内存选项。“动态分配内存”具体在什么位置呢？

我建议像评课社区这种需要突发内存的设备，使用docker与其他服务共享资源。以节约资源。
其实，python有自己的依赖管理（pip install -r），迁移到docker蛮容易的。

**Comment by bojieli** [comment]
@gaoyifan 这个图中就是动态分配内存的意思。也就是默认就是动态分配内存。如果不使用“预留”，虚拟机释放内存后就会回到母机的内存资源池。

“内存”指的是预分配的内存数量，这些内存如果虚拟机不用，也是会还给母机的。“限制”指的是虚拟机最大内存限制。总的“限制”数量可能会超过物理内存数，就是超售。使用“预留”的话，预留部分的内存即使不用也不会归还给母机。

评课社区确实是用 pip 管理依赖的，pip install -r 就行。
https://github.com/JING-TIME/ustc-course/blob/master/README.md

不过我需要把导入的原始数据文件传到服务器上，然后运行导入脚本，如果用 docker 的话，在母机上做感觉并不和谐……如果在 docker 里面开 ssh（不管是不是同一个 docker），感觉都不像 docker 的正经用法。不知道你们是怎么处理这种需要不定期维护数据卷的问题的。

**Comment by bojieli** [comment]
@gaoyifan 在他自己的服务器上（也托管在图书馆）开了一个虚拟机，非常感谢 @gaoyifan 同学！暂时不用 LUG 集群的服务器了。
