### ISSUE TITLE
Mirrors FTP 服务不正常

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#77]
所有目录无法列出。

**Comment by gaoyifan** [comment]
未能复现。sftp,  ftp,  http协议列出目录均正常。
![screen shot 2016-12-14 at 12 01 35 pm](https://cloud.githubusercontent.com/assets/5450996/21169233/6a38e938-c1f5-11e6-8b37-b407fefdd8d3.png)
![screen shot 2016-12-14 at 12 02 05 pm](https://cloud.githubusercontent.com/assets/5450996/21169235/6ca49ee2-c1f5-11e6-9102-27f236aae306.png)
![screen shot 2016-12-14 at 12 03 11 pm](https://cloud.githubusercontent.com/assets/5450996/21169239/70749e32-c1f5-11e6-9271-6bf9e266871e.png)

**Comment by hosiet** [comment]
@gaoyifan 是 mirrors.ustc.edu.cn

**Comment by gaoyifan** [comment]
我看错了.....

**Comment by gaoyifan** [comment]
似乎也挺正常的
![screen shot 2016-12-14 at 12 08 07 pm](https://cloud.githubusercontent.com/assets/5450996/21169303/ff6a8afc-c1f5-11e6-96c9-c374b6b5caab.png)

**Comment by hosiet** [comment]
@gaoyifan 进任何一个子目录看看？

**Comment by gaoyifan** [comment]
子目录的确列不出来

要不乘此机会直接关掉ftp？

**Comment by hosiet** [comment]
@gaoyifan 你需要遍历一遍上游看看哪些上游需要 FTP。至少 Debian 没 FTP 的话大概是不能作为官方源的

**Comment by gaoyifan** [comment]
原因是添加dm设备后，没有重新挂载bind mount目录。执行`mount -a`后恢复正常。

**Comment by Alkaid-Benetnash** [comment]
dm开机不能自动挂载，ftp每次开机都不能挂上
fstab并不能写dm的规则，上次查了一下，目前知道的解决途径是在initramfs里加local-pre-mount脚本
