### ISSUE TITLE
mirrors切换新服务器与分级服务

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#78]
明天我和 @knight42 去机房安装SD卡，至此新mirrors就算正式上线了。
P.S. 周一下午2:20在网络信息中心，有人一起去吗?

* * *

我有些想法，大家看看是否合适？

1. 待数据迁移完毕后，外部阵列重做为RAID10（防止坏盘时性能大幅下降）。
2. 新mirrors内部阵列存放热门的镜像源。原外部阵列连接到新mirrors，外部阵列存储较冷门的镜像。
3. 旧mirrors可以用作“日志服务器”，“存储服务器”，etc...  

P.S.  
新mirrors内部存储6T * 12。做成RAID10，可用空间约32.8T。
原外部阵列 2T * 16。做成RAID10，可用空间约14.6T。
目前mirrors现有数据总量约25.6T

**Comment by zhsj** [comment]
@gaoyifan 为什么我感觉sd卡是个flag。。。

**Comment by gaoyifan** [comment]
@zhsj  https://item.jd.com/3521457.html

**Comment by 1997cui** [comment]
@zhsj 需要报销么？管指委这边应该还有配额

**Comment by gaoyifan** [comment]
@1997cui 需要报销。实物发票在曾键那儿，你下午在东区吗？

**Comment by 1997cui** [comment]
@gaoyifan 啊 很悲剧 刚刚问了下分管委员，这学期没报销了😂 下学期编计划书我把这个钱编进去吧 PS: 现在网购发票，电子产品都可以报销了，策划书也不用写明细了，只填总金额就成。

**Comment by gaoyifan** [comment]
update:  新mirrors已配置完成，正在从旧mirrors同步数据

**Comment by gaoyifan** [comment]
update:  内网、LDAP已配置，主机名： mirrors2.s.ustclug.org

**Comment by gaoyifan** [comment]
新服务器已部署完成，存储使用zfs RAIDZ-3：
冗余后约42.3TB容量（足够存下所有镜像）
连续写入性能约1.1GB/s
连续读取性能约600MB/s

旧服务器安装ESXi，存储重建为RAID 10，可用空间2T * 8 / 2 == 8T。用于运行GitLab等较为消耗资源的服务。
