### ISSUE TITLE
SMART error

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#8]
```
Aug 24 17:03:04 mirrors smartd[17310]: Device: /dev/bus/0 [megaraid_disk_14] [SAT], SMART Prefailure Attribute: 1 Raw_Read_Error_Rate changed from 115 to 116
```

**Comment by Alkaid-Benetnash** [comment]
问题不知道是不是严重啊，我才注意到这个issue
看了下[smart](https://github.com/ustclug/discussions/files/601920/megaraid_disk_14_smart.txt)信息，这些错误吓人吗？
真的有问题的话，我觉得应该联系james换块盘了，不然很危险，内部是[raid5](https://github.com/ustclug/discussions/files/601921/megaraid_c0_show.txt)的，且没有多余盘位了
如果在恢复的时候再挂一块就完蛋了

**Comment by bojieli** [comment]
从 115 升到 116，这个变化不吓人，但出现了读错误本身就是值得警惕的（正常情况下读错误应该是0），而且 SMART 已经说是
pre-failure 了。感觉 SMART 报告 pre-failure 状态就可以考虑换盘了。

**Comment by lshw** [comment]
偶尔有个读错误还好吧，不用太紧张

**Comment by gaoyifan** [comment]
目前Raw_Read_Error_Rate已经飙升至185787496

**Comment by gaoyifan** [comment]
这台机器已经不再用作mirrors。  阵列也重做成了RAID10。
