### ISSUE TITLE
Canonical 赞助事宜

### ISSUE THREAD

**Issue by hosiet** [ustclug/discussions#80]
1000元，详见邮件。

有这几样事情要做：

* [x] 确认用途（需要开发票）
* [x] 确认收款方式 @cuihaoleo 你哪里可以吗？
* [x] 回复邮件
* [x] 设备购买，发票寄出
* [x] 确认 Ubuntu Core 镜像内容（是否存在？）
* [x] 发新闻稿感谢赞助（分类 mirrors 以便挂在主页上）

事项一个一个来。

**Comment by hosiet** [comment]
回复邮件已发出。有需求的话，赶紧买买买啊

**Comment by gaoyifan** [comment]
可以考虑购买奶牛老师提到的SSD。可能还需要使用一些经费。
https://item.jd.com/10386029835.html

**Comment by hosiet** [comment]
可以考虑就尽快下单吧

**Comment by hosiet** [comment]
@gaoyifan 之前说过要买的尽早下单，快没有时间了

**Comment by gaoyifan** [comment]
@hosiet  钱在谁那儿？

**Comment by hosiet** [comment]
@gaoyifan @cuihao 已经收到钱了

**Comment by gaoyifan** [comment]
@Alkaid-Benetnash 社长觉得没问题就买呗

**Comment by gaoyifan** [comment]
@hosiet 
与 @Alkaid-Benetnash 沟通了一下，确认购买SSD。已下单。
![screen shot 2017-01-05 at 11 51 09 pm](https://cloud.githubusercontent.com/assets/5450996/21686861/e2e069de-d3a1-11e6-94c4-ce8a2d0dc4df.png)

**Comment by hosiet** [comment]
@gaoyifan 收到，到货后请更新一下情况

**Comment by knight42** [comment]
SSD 已收到

**Comment by hosiet** [comment]
所有任务已完成

**Comment by gaoyifan** [comment]
@hosiet  我们有发新闻稿吗？

**Comment by hosiet** [comment]
@gaoyifan 在安装 ssd 的新闻后附上了内容。
