### ISSUE TITLE
anheng.com.cn 从rsync.ustc.edu.cn 同步Debian很慢

### ISSUE THREAD

**Issue by lshw** [ustclug/discussions#81]
我不能确定是因为anheng.com.cn被DDoS的原因，还是目前rsync.ustc.edu.cn对rsync有限速，
请帮我确认一下。另外，听说你们在telegram群聊的热闹，申请加入，谢谢，liushiwei@gmail.com

**Comment by zhsj** [comment]
@lshw mirrors要更换新硬件了，到时rsync速度应该会有改观。telegram群需要你的 telegram id。

**Comment by StephenPCG** [comment]
@zhsj tg群里我已经邀请了 @lshw 了。

**Comment by gaoyifan** [comment]
近期科大镜像站负载不高，可以尝试通过不同的出口同步：
cernet.mirrors.ustc.edu.cn
mobile.mirrors.ustc.edu.cn

**Comment by lshw** [comment]
好的。
