### ISSUE TITLE
zfs-modules-3.16.36-ustclugsigned+deb8u2 无法正常载入

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#87]
重启进签名内核后zfs未能正常加载。目前已换回debian官方内核。@zhsj

**Comment by zhsj** [comment]
@gaoyifan 那我今晚测试下，可能会重启mirrors2服务器

**Comment by gaoyifan** [comment]
@zhsj 随便重启，现在mirrors2处于闲置状态

**Comment by zhsj** [comment]
装完 kernel 和自编译的 module 之后忘记 depmod 了。

zfs-module 和 spl-module 的 postinst 里写的都是 `depmod`，而单纯运行 `depmod` 只对当前使用的版本的内核（即没签名的那个内核版本）生效，所以这个 postinst 其实执行失败了（

要改deb package的话，得把内核版本写死进 postinst，即 `depmod 3.16.36-ustclugsigned+deb8u2`，感觉不是很优雅，就索性不改了。。。

总之只要手动运行下 `depmod 3.16.36-ustclugsigned+deb8u2` 就好了

**Comment by gaoyifan** [comment]
如果将包名改为`linux-image-3.16.0-4-ustclugsigned-amd64`，每次编译内核时只修改版本号，不改包名是不是会更优雅一些？

**Comment by zhsj** [comment]
这样kernel的包名确实比较科学点，不过和zfs-module/spl-module打包没关系，反正都得往里填kernel的版本。
