### ISSUE TITLE
mirrors切换IP失败

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#89]
由于操作失误，目前旧mirrors失联，但仍然绑定了 2001:da8:d800:95::110。
mirrors2的ipv4已更换为旧地址。

需要去机房救回旧mirrors

**Comment by bojieli** [comment]
祝贺新 mirrors 即将上线！ @gaoyifan 辛苦了～

**Comment by knight42** [comment]
旧 mirrors 已恢复
