### ISSUE TITLE
Fedora, EPEL, RPMFusion URL change

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#95]
这些源的 URL 改变了，但没有修改帮助文档，以及通知上游修改信息

提议：先在 nginx 做临时转跳，待各处信息修改生效后再去除转跳。但 FTP/RSYNC 等仍没有办法及时通知。

**Comment by knight42** [comment]
不是很熟 fedora...

看上去 fedora, epel, rpmfusion 的帮助文档并没有问题, 应该是 @gaoyifan 已经改过了.

我现在加了个 `/fedora/epel` -> `/epel` 的跳转

**Comment by zhsj** [comment]
这些rpm源都默认用fastmirror的，所以上游那边不改的话，就没办法跳到这边来了

**Comment by gaoyifan** [comment]
@zhsj 可以发个公告告知rsync变化
