### ISSUE TITLE
rename debian-multimedia to deb-multimedia

### ISSUE THREAD

**Issue by zhsj** [ustclug/discussions#98]
并不知道上游是什么时候改的名字，但这个项目确实和 debian 没有任何关系。

https://wiki.debian.org/DebianMultimedia/FAQ

Edit by hosiet:
* [X] zfs volume 重命名
* [X] 挂载点重命名
* [X] 发布迁移公告
* [ ] 取消旧有兼容链接/rsync配置并公告（预期2017年7月）

**Comment by zhsj** [comment]
@zhsj 大约 12 年时改的名字。。 https://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2012-May/026678.html

**Comment by hosiet** [comment]
@gaoyifan 看起来这个也不是重命名一下就可以解决的，是否也需要在文件系统层面上进行修改（zfs volume）？

**Comment by gaoyifan** [comment]
@hosiet 可以用`zfs rename`命令重命名。

**Comment by gaoyifan** [comment]
ping @zhsj 
最后一项可以实施了？

**Comment by zhsj** [comment]
可以啊，距离公告已经半年了 https://servers.ustclug.org/2017/04/ustc-mirrors-debian-multimedia-rename-to-deb-multimedia/

**Comment by hosiet** [comment]
fixed via https://servers.ustclug.org/2017/10/ustc-mirrors-debian-multimedia-rename-done/
